### ISSUE TITLE
Jira down causing issue with release promotion to staging

### ISSUE THREAD

**Issue by bhavikbhagat93** [icgc-argo/roadmap#1017]
## Description
Jira auth is broken which is preventing ARGO push to staging because the evn breaks.

1. Need to investigate the issue and document potential solution.
2. we have a feature flag on jira on the API but not the UI, so we’ll deploy with the contact disabled but still appearing in the UI

## Exit Criteria

1. When jira support is down. it should not block the release promotion from dev -> QA ->Stage -> prod
2. Feature flag should be able to handle the integration error and make sure ARGO is running without downtime

**Comment by justincorrigible** [comment]
Closing ticket as superseded by https://github.com/icgc-argo/roadmap/issues/1079
