### ISSUE TITLE
DEV - Homepage not visible after login

### ISSUE THREAD

**Issue by bhavikbhagat93** [icgc-argo/roadmap#1024]
## Description

Once logged in to Fed RDPC, user is not able to view All programs page

## Acceptance criteria

User once logged in should be able to see list of all program

1. programs visible must be based on the geo location of node - eg: programs in toronto should be visible in toronto RDPC only
2. programs visible must be based on the log in role
3.  Program page: options for each program should be visible based on the logged in user role - Eg: Suboptions under ALEXIS-CA program

![image](https://github.com/icgc-argo/roadmap/assets/87338996/de8ec2a6-893b-4d09-9728-39409d177cf0)

**Comment by Buwujiu** [comment]
This is dependedt on Ciaran's PR, close to finish.
