### ISSUE TITLE
Evaluate the technical impacts of clinical exceptions on fields from Non-exception list

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/roadmap#1026]
Due to technical limitations, we are currently not able to allow exceptions on fields from [Non-exception list](https://docs.google.com/spreadsheets/d/1wS6Q-xGgpRY2v7F_kkyP9mkO3kzWdNkXkVQseZz8u1o/edit#gid=0). 

This is a discussion item we will raise during NYC ARGO workshop.To facilitate the discussion, we want to gather and evaluate the possible technical impacts of granting clinical exceptions on Non-exceptional fields, especially the interval related fields.

- [x] update the Non-exception list with latest exceptions status
- [ ] evaluate the technical impacts for the following non-exceptional `interval` fields
      - [ ] specimen: specimen_acquisition_interval
      - [ ] treatment: treatment_start_interval
      - [ ] treatment: treatment_duration
      - [ ] follow_up: interval_of_followup
      - [ ] follow_up: relapse_interval

**Comment by justincorrigible** [comment]
Closing as Done
