### ISSUE TITLE
Make sure the New RDPC Gateway API Are Ready in QA

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/roadmap#1036]
## Goal
Clinical and RDPC gateway API are deployed in culmulus dev and QA, we need to test the RDPC API to make sure the endpoints are ready to connect with UI.

**Comment by demariadaniel** [comment]
Dev Testing Dec 7

Swagger Endpoints
https://api.rdpc-dev.cumulus.genomeinformatics.org/api-docs/

Template All
All Clinical Data
Template Schema
Registration
- Working

**Comment by demariadaniel** [comment]
Dev Testing Dec 7

GQL Resolvers
https://api.rdpc-dev.cumulus.genomeinformatics.org/graphql

clinicalSubmissionTypesList
clinicalSubmissionSystemDisabled
clinicalSubmissionSchemaVersion
clinicalRegistration
clinicalSubmissions
clinicalSearchResults
- Working
 
Fixed bugs related to empty DB + misnamed query resolvers

**Comment by demariadaniel** [comment]
QA Testing Dec 11

Swagger
https://api.rdpc-qa.cumulus.genomeinformatics.org/api-docs/
Working:
- All Clinical Data
- Submission Templates: download works, Zip file name is blank
- Template
- Registration

**Comment by demariadaniel** [comment]
QA Testing Dec 11

GQL
https://api.rdpc-qa.cumulus.genomeinformatics.org/graphql
Working:
- clinicalSubmissionSystemDisabled
- clinicalSubmissionSchemaVersion
- clinicalSubmissionTypesList
- clinicalSubmissions
- clinicalRegistration
- clinicalSearchResults

**Comment by joneubank** [comment]
Service is available and in use by RDPC UI
