### ISSUE TITLE
Get Approval For Core Completion policy

### ISSUE THREAD

**Issue by bhavikbhagat93** [icgc-argo/roadmap#1040]
## Description

Create policy proposal for MUTO-INTL, After lost to follow up field update, there is no data for Treatment and follow up tables which leads to core completion % not summing to 100 leading to data being called not "core complete".

Action Items:
1. Make Draft proposal for the Policy Change.
2. Melanie to review and provide feedback
3. Get Approval from Working Group.

**Comment by bhavikbhagat93** [comment]
1. How to request. (Operation)
2. How to record request (CRUD Endpoints) (Operation)
3. Develop the service and calculations based on request (Backend)
4. How data is handled when shown back to User (UI)

**Comment by lindaxiang** [comment]
Draft proposal: https://docs.google.com/document/d/1cBKwH-BAt32p7fWy8ujFDCUjDkJ298B8dzidK93ixg4/edit?usp=sharing
