### ISSUE TITLE
Embargo lift - P1000-US

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/roadmap#1042]
P1000-US is collaborating with ~10 institutions. 
- They have internal embargo periods which vary by sets of donors across different cohorts and will typically span between now until early 2025. 
- They want to grant select institutions of collaborators limited view access to sets of donors with the ability to download molecular and clinical data. 
- The would like different collaborators to have access to different subsets of donors

**Comment by justincorrigible** [comment]
Program has agreed to lift their embargo state. Closing ticket as completed
