### ISSUE TITLE
ARGO Release 43 - Homepage Announcement

### ISSUE THREAD

**Issue by bhavikbhagat93** [icgc-argo/roadmap#1074]
## Detailed Description

1. Add a new announcement to the top:
```
 February 14, 2024: [ARGO Dictionary 1.21](https://docs.icgc-argo.org/dictionary) sees one new permissible term added to treatment_type and updated validation scripts to take into account clinical exception values.
```

2. Remove the oldest announcement:
```
October 18, 2023: We are excited to announce Lost to follow up feature and [Dictionary 1.19](https://docs.icgc-argo.org/dictionary) is now available.
```

**Comment by lindaxiang** [comment]
- Dictionary update:
[ARGO Dictionary 1.21](https://docs.icgc-argo.org/docs/release-notes/dictionary-releases#release-121) sees one new permissible term added to `treatment_type` and updated validation scripts  to take into account clinical exception values.

**Comment by mcourtot** [comment]
February 14, 2024: A new release of the ARGO Dictionary, [version 1.21](https://docs.icgc-argo.org/dictionary), sees one new permissible term added to `treatment_type` and updated validation scripts to take into account clinical exception values.
