### ISSUE TITLE
ARGO Release 43 - Software Release Notes 

### ISSUE THREAD

**Issue by bhavikbhagat93** [icgc-argo/roadmap#1075]
February 14, 2024: Clinical Exceptions Enhancement

Data Platform - UI ?- API ?

- Update to entity level exceptions: when enabled, exception rules will apply to one or many numeric fields can accept "Unknown" and "Not Applicable" values for those field
- Missing entity exception : when enabled, exception rules will provide submitters with the option to exclude the uploading of core entity schemas (such as treatment and follow-up) for certain donors.

**Note: Final Text in comments from Mitchell**

**Comment by MitchellShiell** [comment]
# February 14, 2024: New Entity Exception Features​

**Data Platform - UI 1.125.4 - API 3.42.2**

We've listened to your feedback on our submission process and are excited to announce these updates:

- With this release, we have introduced **enhanced entity-level exceptions for numeric fields**. These exception rules allow numeric fields to accept "Unknown" and "Not Applicable" values when enabled. This enhancement dramatically improves the flexibility of data submissions.


- Additionally, we are excited to introduce the **missing entity exception feature**. This feature, when enabled, allows submitters the flexibility to exclude core entity fields, such as treatments and follow-ups, for specific donors. With this feature, data submitters have more options to manage their submissions efficiently, especially when certain information is unavailable.

For more information on gaining access to entity exceptions, see our [clinical data exception policy](https://www.icgc-argo.org/page/79/quality-standards-of-samples#:~:text=Clinical%20Data%20Exceptions%20Policy%C2%A0). We encourage data submitters to explore these new features and look forward to your feedback.

**Comment by MitchellShiell** [comment]
Applying principles from the ARGO writing guide I sent over, change as needed to ensure the accuracy of information.

**Comment by MitchellShiell** [comment]
If these updates were not made due to solicited feedback, then you can open with: We've improved our submission process and are excited to announce the following updates: ...

**Comment by MitchellShiell** [comment]
If there is no feedback channel to point to remove the last line

**Comment by MitchellShiell** [comment]
**Data Platform - UI  1.125.4 - API  3.42.2**

This release sees the addition of new ways for data submitters to accommodate missing values or data:

1. **Enhanced Entity-Level Exceptions for Numeric Fields**: These exception rules now permit numeric fields to accept "Unknown" and "Not Applicable" values when enabled.

2. **New Missing Entity Exception Feature**: This feature allows submitters to exclude core entity fields, such as treatments and follow-ups, for specific donors.

See our  [clinical data exception policy](https://www.icgc-argo.org/page/79/quality-standards-of-samples#:~:text=Clinical%20Data%20Exceptions%20Policy%C2%A0) for more information on gaining access to entity exceptions. We encourage data submitters to explore these new features and welcome any [feedback](https://www.icgc-argo.org/page/69/contact-us) they may have.
