### ISSUE TITLE
Program: POG-CA exceptions

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/roadmap#1076]
- [ ] Exception requests received on Dec.18, 2023

Specimen: requesting exceptions on 8 Conditional Fields (Core for tumour samples): https://github.com/icgc-argo/roadmap/issues/1077
- pathological_tumour_staging_system: Unknown
- pathological_t_category: Unknown
- pathological_n_category: Unknown
- pathological_m_category: Unknown
- pathological_stage_group: Unknown
- tumour_histological_type: Unknown
- tumour_grading_system: Unknown
- tumour_grade: Unknown

**Comment by justincorrigible** [comment]
Closing as Done
