### ISSUE TITLE
Program level exception request - Specimen - 8 fields

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/roadmap#1077]
POG-CA: the following 8 fields are not reported in most patients at the time of pathological assessment, they need to request exceptions of "Unknown"
- [ ] pathological_tumour_staging_system
- [ ] pathological_t_category
- [ ] pathological_n_category
- [ ] pathological_m_category
- [ ] pathological_stage_group
- [ ] tumour_histological_type
- [ ] tumour_grading_system
- [ ] tumour_grade

**Comment by justincorrigible** [comment]
To be tested in prod, as a condition to be able to close this ticket.

**Comment by lindaxiang** [comment]
POG-CA: the  field core conditional "is_primary_treatment"  is not readily available, they request to populate the 
"is_primary_treatment"  with "Unknown"  for all of the ~3500 treatment records.
- [ ] is_primary_treatment

**Comment by justincorrigible** [comment]
Closing as Done
