### ISSUE TITLE
Platform Contact Us Page showing error

### ISSUE THREAD

**Issue by bhavikbhagat93** [icgc-argo/roadmap#1079]
## Description

When the user submits a message in the `Contact us` page, a toast error is displayed on the UI. 

![image](https://github.com/icgc-argo/roadmap/assets/2107110/f1413f0a-ef31-4c00-bc52-d6d85319f71c)

The cause of this is a trickle down consequence from tickets #1017 and #1018, described as follows:
- Message submission was disabled at the Argo Gateway level, because authentication of the app into the Jira Helpdesk was failing. There doesn't seem to be any documentation on what the issue was on their end, but it was blocking release deployments, so it was turned off "temporarily".
- The contact page itself, at the UI level, doesn't have a complementary feature flag to disable or hide the message form in these cases, so it will seem to allow submissions that the gateway will reject. Though we have an error toast to account for something going wrong, we ought to be able to disable the functionality on both layers consistently.
- Upon checking today, Jira authentication is failing (unclear whether this is the same issue faced in October, or a different one), and so we're unable to reactivate things to their normal function.

Action items:
- We need a new low-priority ticket in the Platform UI repo, which will account for the feature flag implementation. Doesn't need to be assigned immediately, but it'll be good to at least have it as a form of "we know" for the future.
- @justincorrigible opened a ticket with IT to request access and troubleshoot the authentication issues. They will follow up later on in this here ticket through comments.

**Comment by justincorrigible** [comment]
PR opened, and under review

**Comment by justincorrigible** [comment]
PR merged, updating Jira secret, ReCaptcha keys in vault etc.
For future reference so that others won't have to go doing archeology/forensics:
- Keys are manage keys at https://www.google.com/u/2/recaptcha/admin, under devops@icgc-argo.org
- Jira login details can be found in the relevant gateway secret at argo prod vault
- the personal access token must be renewed once a year in jira, and the expiration date also updated in the same aforementioned secret

(cc @joneubank for insight)

**Comment by justincorrigible** [comment]
Some of the JIRA endpoints are responding with errors, so I had to comb through Attlassians' weird documentation.
Finally found the right ones here https://developer.atlassian.com/cloud/jira/service-desk/rest/
