### ISSUE TITLE
2. Allow data upload with exception on number field

### ISSUE THREAD

**Issue by bhavikbhagat93** [icgc-argo/roadmap#1083]
## Description

When number exception is set on number field, user should be allowed to 

1. Upload data with blank values on exception fields.
2. Validate data with blank values on exception fields.
3. Approve data with blank values on exception fields.

## Acceptance criteria

For MUTO - INTL, user should be able to perform above action with exception on following fields

specimen_acquisition_interval
treatment_start_interval
treatment_duration

**Comment by demariadaniel** [comment]
Test case # 1
Successful exception submitted for field `treatment_start_interval`
Record successfully passes schema validation and clinical validation with field empty

Test records:
(Zenhub does not allow TSV uploads)
[treatment_test_exception1.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1B2QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d4389a7027db28e0c70bdb5c4cdfd0272d38e187/treatment_test_exception1.txt)

Exception record:
[exception_test1.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2J2QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d210728a394fa63b11f5215f5ca8fb5c9fbd6054/exception_test1.txt)

<img width="800" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2p2QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--655fdad6bd168fd1b91c678a25124c747d17ae0d/Screenshot%202024-01-19%20at%203.40.44%20PM.png" alt="Screenshot 2024-01-19 at 3.40.44 PM.png" />


<img width="836" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2Z2QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e9abf7678edfb9e1e7d3b7939f5fdbe30c08ecb2/Screenshot%202024-01-23%20at%2011.28.55%20AM.png" alt="Screenshot 2024-01-23 at 11.28.55 AM.png" />

**Comment by demariadaniel** [comment]
Test Case 2

Successful exception submitted for field `treatment_duration`
Record successfully passes schema validation and clinical validation with field empty

[exception_test2.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFR2QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d1bfc7dd6b1c97a6a980b3adf4ecdc581935c029/exception_test2.txt)

[treatment_test_exception2.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGZ2QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1db4bea4dda9c27c7bc90faac74925166361e1f6/treatment_test_exception2.txt)

<img width="754" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUR2QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--87f901859db0afd8cd9923f388cc1b4783dff748/Screenshot%202024-01-19%20at%203.51.42%20PM.png" alt="Screenshot 2024-01-19 at 3.51.42 PM.png" />

<img width="846" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUh2QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a04606e12eea311289a4721989e5090b34a7c04b/Screenshot%202024-01-23%20at%2011.38.06%20AM.png" alt="Screenshot 2024-01-23 at 11.38.06 AM.png" />

**Comment by demariadaniel** [comment]
Test Case 3

Successful exception submitted for field `specimen_acquisition_interval`
Record successfully passes schema validation and clinical validation with field empty

[exception_test3.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTd2QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--778952064b2a6d5fde7714e56acdcc18c2192eaa/exception_test3.txt)

[specimen_test_exception1.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNS92QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cb9a93fbb1c6f7d1dff0f7ba69580cfb121ee49d/specimen_test_exception1.txt)

<img width="920" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkh2QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--20dfaa09527852b75f0c10314833298ceac95e2b/Screenshot%202024-01-19%20at%204.13.21%20PM.png" alt="Screenshot 2024-01-19 at 4.13.21 PM.png" />

<img width="846" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkx2QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0b907ad7e419c335f9e57bf9b7efff7a7bf6fe82/Screenshot%202024-01-23%20at%2011.46.26%20AM.png" alt="Screenshot 2024-01-23 at 11.46.26 AM.png" />

**Comment by demariadaniel** [comment]
Edge case: Lost to Follow Up

If you submit/validate/approve Test Case #1 above, this will create a treatment record with blank `treatment_start_interval` and `treatment_duration` of 1 as `TR-7`

If you then submit a Donor record with Lost to Follow Up Event ID of `TR-7`, there will be multiple validation errors as all preceding events will have interval values higher than the Lost to Follow Up interval

[donor_test_exception1.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOG52QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--de4e085c094aa6e44d5a32596dfd7ec97e3d7ef5/donor_test_exception1.txt)

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHJ2QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5d94206068e2b87567a13291681f26c8a6fa9ca0/Screenshot%202024-01-23%20at%2012.12.37%20PM.png" alt="Screenshot 2024-01-23 at 12.12.37 PM.png" />

**Comment by demariadaniel** [comment]
Updated Specimen exception for testing entity exceptions

[exception_entity_test3.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK253QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9e6410a21223a7374ef69fe9d60ad13be5b7a753/exception_entity_test3.txt)

**Comment by demariadaniel** [comment]
PR: https://github.com/icgc-argo/argo-clinical/pull/1108
