### ISSUE TITLE
Program dashboard does not correctly reflect the workflow running status

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/roadmap#1087]
There are already 3 jobs completed based on graphQL query:
```
{
    runs(
      page: {from: 0, size: 10000}
      filter: {
        studyId: "P1000-US", state: "COMPLETE"
      }
    ) 
  {
        info {
          totalHits
          contentCount
        }
}
```
![Screenshot 2024-01-09 at 6 45 39 PM](https://github.com/icgc-argo/roadmap/assets/7522294/f225f7dc-4050-436c-ac02-bf9aed2d6646)

However, the program dashboard does not correctly reflect the workflow running status. It indicates:
- 4 running jobs, 3 failed jobs. no completed jobs. 

![Screenshot 2024-01-09 at 6 46 08 PM](https://github.com/icgc-argo/roadmap/assets/7522294/63b6a5fb-2c02-4cb9-8134-617824a64f75)

**Comment by edsu7** [comment]
MUTO-INTL is reporting another inconsistency:
-The error is in the prod dashboard and submitted data counts where dashboard is showing 0 raw data counts
![image](https://github.com/icgc-argo/roadmap/assets/22638361/706a5475-aa94-49d0-9a49-607a611a7733)
but looking into song there's two analyses

```
https://submission-song.rdpc.argo.genomeinformatics.org/studies/MUTO-INTL/analysis/search/id?donorId=DO253156
```

**Comment by demariadaniel** [comment]
Issue fixed by reindexing Maestro:
https://oicr.slack.com/archives/C04FHCTJ3AR/p1704911853813129?thread_ts=1704899421.697379&cid=C04FHCTJ3AR
