### ISSUE TITLE
Donor level exception request for `treatment` schema

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/roadmap#1089]
P1000-US requested donor level exception for `treatment` schema. 
- Currently donor level exception is supported only for `specimen` and `follow_up` schemas, further development is needed to support donor level exception for `treatment` schema. 
- However the program level exception is already supported for `treatment` schema

**Comment by demariadaniel** [comment]
Covered by https://app.zenhub.com/workspaces/icgc-argo-platform-dk-production-board-5e542d38415f5034e9fed89d/issues/gh/icgc-argo/roadmap/1103

**Comment by demariadaniel** [comment]
https://github.com/icgc-argo/argo-clinical/pull/1116
