### ISSUE TITLE
gql `clinicalData` query not returning results

### ISSUE THREAD

**Issue by ciaranschutte** [icgc-argo/roadmap#1115]
`clinicalData` gql query not returning results

possible source of issue is here in the mongoose filtering: 
https://github.com/icgc-argo/argo-clinical/blob/develop/src/clinical/donor-repo.ts#L256
```
    const result = await DonorModel.paginate(
      {
        programId,
        ...completionState,
        ...searchQuery,
      },
      {
        projection,
        sort,
        page,
        limit,
      },
    );
``` 
`completionState` is being spread but it's a string resulting in `{0: 'a', 1:'l', 2:'l'}`
<img width="309" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0psQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1898dacdcd89eab6ffb72a741270cd2834a4998a/Screenshot%202024-02-16%20at%202.19.00%E2%80%AFAM.png" alt="Screenshot 2024-02-16 at 2.19.00 AM.png" />

<img width="684" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM05sQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--254c1d4ee72b0f800d571744aa51f9aa7292a605/Screenshot%202024-02-16%20at%203.28.10%E2%80%AFAM.png" alt="Screenshot 2024-02-16 at 3.28.10 AM.png" />

**Comment by demariadaniel** [comment]
See ClinicalApi: https://github.com/icgc-argo/argo-clinical/blob/develop/src/clinical/api/clinical-api.ts#L204

CompletionState `string` sent by API is then used to access a key on `completionFilters` which yields an object
Obviously something is not connected right however based on the Mongoose.find() screenshot

Assuming this is RDPC UI -> RDPC Gateway?
Starting point to review is clinicalData resolver at: https://github.com/icgc-argo/argo-clinical/blob/develop/src/schemas/clinical-resolvers/clinicalData.ts

**Comment by demariadaniel** [comment]
Two additional bugs addressed in PR:
- Prevents error if 'sort' field is empty in query filters
- Handles errors where requested clinicalError schema not found in data dictionary
