### ISSUE TITLE
MUTO-Missing entity exception request

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/roadmap#1121]
Here is the list of donors which have enable the lost_to_followup feature and request the missing entity exception. 
[MUTO-INTL. EntityExceptionRequest.list_submitter_losttofup.txt](https://github.com/icgc-argo/roadmap/files/14423484/MUTO-INTL.EntityExceptionRequest.list_submitter_losttofup.txt)

The exceptions have been granted from api on Feb27, 2024

**Comment by justincorrigible** [comment]
Closing as Done
