### ISSUE TITLE
ARGO Data Release 8 -  Homepage News Announcement

### ISSUE THREAD

**Issue by bhavikbhagat93** [icgc-argo/roadmap#1123]
## Detailed Description

1. Add a new announcement to the top:

 March 07, 2024: [Data Release 8.0](https://docs.icgc-argo.org/docs/release-notes/data-releases) is now available, adding molecular and clinical data for 515 new donors from [MUTO-INTL](https://www.icgc-argo.org/page/99/mutographs) and  [P1000-US](https://www.icgc-argo.org/page/115/p-1000) Programs.

2. Remove the oldest announcement:
```
October 18, 2023: This release sees the addition of a new optional field called lost_to_followup_after_clinical_event_id to the Donor table, allowing data submitters to indicate when a donor was lost to follow up after a clinical event. Information on additional metadata fields can be found in ARGO Dictionary 1.19.
```

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjI2QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0ae676f5bf067b4df74baf0f32c872e6fd2b08df/image.png" alt="image.png" />

**Comment by joneubank** [comment]
proposed new announcement text:
> Data Release 8.0 is now available, adding molecular and clinical data for 515 new donors from MUTO-INTL and P1000-US programs.
