### ISSUE TITLE
ARGO Data Release 8 - Data Release Notes

### ISSUE THREAD

**Issue by bhavikbhagat93** [icgc-argo/roadmap#1124]
## Detailed Description

Page Location: https://master--argo-docs.netlify.app/docs/release-notes/data-releases

1. Add a new announcement to the top:

Data Release 8.0

Release Date: March 07, 2024

New Updates​
~~ICGC ARGO is excited to announce the release of new data available for Mutographs ([MUTO-INTL](https://www.icgc-argo.org/page/99/mutographs)) and Polyethnic-1000 ([P1000-US](https://www.icgc-argo.org/page/115/p-1000)).~~

Data Release 8.0 includes new clinical and molecular data Mutographs ([MUTO-INTL](https://www.icgc-argo.org/page/99/mutographs)) and Polyethnic-1000 ([P1000-US](https://www.icgc-argo.org/page/115/p-1000)).

This release includes:

- MUTO-INTL: New 448 donors with clinical data, aligned WGS reads, and Mutect2 variant calls
   - MUTO-INTL: 285/448 donors additionally have Sanger variant calls
   - MUTO-INTL: 9/448 donors have open access Sanger variant Calls
- P1000-US: New 67 donors with clinical data, aligned WGS reads, and Mutect2 variant calls

**Comment by joneubank** [comment]
Let's rephrase to make this statement of facts, we no longer want to use the "excited to announce language".

**Comment by mcourtot** [comment]
update release date
Data Release 8.0 includes new clinical and molecular data from the Mutographs (MUTO-INTL) and Polyethnic-1000 (P1000-US) programs. 

(with the hyperlinks for the programs please)
