### ISSUE TITLE
ARGO Data Release 8 -  Homepage Number Update

### ISSUE THREAD

**Issue by bhavikbhagat93** [icgc-argo/roadmap#1128]
## Description

As a user, I should be able to see following count on homepage hero section

- No of program : 7
- No of donors : 1546
- No of files : 55159

Section that needs update 
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGU2QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9d70153e7c56a65bfc8a326ff2fc7b7609e092c3/image.png" alt="image.png" />

**Comment by ciaranschutte** [comment]
updated from calling backend
