### ISSUE TITLE
ARGO Data Release 9.0 - Data Release Notes

### ISSUE THREAD

**Issue by bhavikbhagat93** [icgc-argo/roadmap#1132]
## Detailed Description

Page Location: https://docs.icgc-argo.org/docs/release-notes/data-releases

1. Add a new announcement to the top:

Data Release 9.0

Release Date: May 23 , 2024

New Updates​

Data Release 9.0 includes new clinical and molecular data from the CRUK Grand Challenge – Mutographs ([MUTO-INTL](https://www.icgc-argo.org/page/99/mutographs)), BC Cancer Personalised OncoGenics Program ([POG-CA](https://www.icgc-argo.org/page/97/bc-pogp)) and Polyethnic-1000 ([P1000-US](https://www.icgc-argo.org/page/115/p-1000)).

This release includes:

- MUTO-INTL: 913 new donors and 102 updated donors
  - 913 new donors with clinical data, and aligned WGS reads.
  - 912/913 donors additionally have Mutect2 variant calls
  - 809/913 donors additionally have Sanger variant calls
  - 102 previously released donors have new Sanger variant calls
- POG-CA: 300 new donors
  - 300 new donors with clinical data, aligned WGS reads, and Mutect2 variant calls
  - 58/300 donors additionally have Sanger variant calls
- P1000-US: 10 new donors and 53 updated donors
  - 4/10 new donors with clinical data, aligned WGS reads, and Mutect2 variant calls
  - 6/10 new donors with clinical data, aligned RNA-Seq reads
  - 13 previously released donors have new Sanger variant calls
  - 53 previously released donors have new aligned RNA-Seq reads

**Comment by mcourtot** [comment]
1. Use full program names, eg: BC Cancer (BC Cancer)’s Personalized OncoGenomics (POG), CRUK Grand Challenge – Mutographs etc at first occurrence
2. the numbers are confusing eg for P1000, 4 new donors and then 14 and 60. I understand this include existing donors. Maybe having a total count of donors for the program would help?
3. POG-CA entry: "New 300 donors" -> "300 new donors"
4. Why are we repeating the program name under each program heading?

**Comment by bhavikbhagat93** [comment]
1. Done
2. for this release we can have a total count for Eg: "60 donors (4 new donors) with clinical data, aligned WGS reads, and Mutect2 variant calls", going forward if the release includes count from existing donors, i will work with bio info to come up with a consistent format for sharing donor count.
3. Done.
4. We are just following the format from the old data release, if it feels like information overload we can remove the program names from next release.

**Comment by mcourtot** [comment]
4. any reason not to remove them from this release?

**Comment by edsu7** [comment]
>MUTO-INTL: 1015 donors (913 new donors) with clinical data, and aligned WGS reads.

Would something like this be better?
- MUTO-INTL : Updates to 1015 donors 
  -  913 new donors with clinical and aligned WGS

**Comment by edsu7** [comment]
- **1217 new donors**
- MUTO-INTL : Update to 1015 donors
  -    **913 new donors with clinical data and aligned WGS reads**
  -   912 donors additionally have Mutect2 variant calls
  -   911 donors additionally have Sanger variant calls
- POG-CA : Update to 300 donors
  -   **300 new donors with clinical data, aligned WGS reads, and Mutect2 variant calls**
  -   58 donors additionally have Sanger variant calls
- P1000-US : Update to **63** donors
  -   **4 new donors with clinical data, aligned WGS reads and Mutect2 variant calls**
  -   14 previously released donors have new Sanger variant calls
  -   60 previously released donors have new RNA-Seq alignments

**Comment by lindaxiang** [comment]
@edsu7 is the number of P1000 correct? The portal indicates that there're 67 donors already release in DR8.0, and after adding 4 new donors, should it be `71` donors in total?

- MUTO-INTL: 1015 donors are released in total
  - 913 new donors with clinical data, and aligned WGS reads.
  - 912/913 donors additionally have Mutect2 variant calls
  - 911/913 donors additionally have Sanger variant calls
- POG-CA: 300 donors are released in total
  - 300 new donors with clinical data, aligned WGS reads, and Mutect2 variant calls
  - 58/300 donors additionally have Sanger variant calls
- P1000-US: **71** donors are released in total
  - 4 new donors with clinical data, aligned WGS reads, and Mutect2 variant calls
  - 14 previously released donors have new Sanger variant calls
  - 60 previously released donors have new RNA-Seq alignments

**Comment by edsu7** [comment]
@lindaxiang 
>The portal indicates that there're 67 donors already release in DR8.0, and after adding 4 new donors, should it be 71 donors in total?

The total should be `77` including previously released donors. What I'm trying to describe is # of donors updated include newly released, that being `63`

Perhaps your query did not include RNAseq?

![image](https://github.com/icgc-argo/roadmap/assets/22638361/fc53b394-0233-407a-bd2c-d59e85931ba8)
![image](https://github.com/icgc-argo/roadmap/assets/22638361/d7e63c0c-9536-4e45-84e4-edd38d87b355)

**Comment by lindaxiang** [comment]
correct the numbers following @edsu7 comments
- MUTO-INTL: 913 new donors and 102 updated donors 
		- 913 new donors with clinical data, and aligned WGS reads.
		- 912/913 donors additionally have Mutect2 variant calls
		- 809/913 donors additionally have Sanger variant calls
		- 102 previously released donors have new Sanger variant calls
- POG-CA: 300 new donors 
		- 300 new donors with clinical data, aligned WGS reads, and Mutect2 variant calls
		- 58/300 donors additionally have Sanger variant calls
- P1000-US:  10 new donors and 53 updated donors
		- 4/10 new donors with clinical data, aligned WGS reads, and Mutect2 variant calls
		- 6/10 new donors with clinical data, aligned RNA-Seq reads
		- 13 previously released donors have new Sanger variant calls
                - 53 previously released donors have new aligned RNA-Seq reads

**Comment by edsu7** [comment]
@lindaxiang 

>  911/913 donors additionally have Sanger variant calls

**809**/913 donors additionally have Sanger variant calls

> P1000-US: 10 new donors and 54 updated donors

P1000-US: 10 new donors and **53** updated donors
> 14 previously released donors have new Sanger variant calls

**13** previously released donors have new Sanger variant calls

> 54 previously released donors have new aligned RNA-Seq reads

**53** previously released donors have new aligned RNA-Seq reads
