### ISSUE TITLE
ARGO Data Release 9.0 -  Homepage News Announcement

### ISSUE THREAD

**Issue by bhavikbhagat93** [icgc-argo/roadmap#1133]
## Detailed Description

1. Add a new announcement to the top:

May 23, 2024: 
~~[Data Release 9.0](https://docs.icgc-argo.org/docs/release-notes/data-releases) is now available, adding new molecular and clinical data for 1217 new donors and new molecular data for 115 existing donor from [MUTO-INTL](https://www.icgc-argo.org/page/99/mutographs), [POG-CA](https://www.icgc-argo.org/page/97/bc-pogp) and  [P1000-US](https://www.icgc-argo.org/page/115/p-1000) Programs.~~

[Data Release 9.0](https://docs.icgc-argo.org/docs/release-notes/data-releases) adds 1,223 new donors and 43,107 new molecular files and clinical data. This includes the first release of data from the BC Cancer Personalised OncoGenics Program [(POG-CA)](https://www.icgc-argo.org/page/97/bc-pogp) and updates from the CRUK Grand Challenge—Autographs [(MUTO-INTL)](https://www.icgc-argo.org/page/99/mutographs) and Polyethnic-1000 [(P1000-US)](https://www.icgc-argo.org/page/115/p-1000) programs.

2. Remove the oldest announcement:

November 30, 2023:
The Toronto Data Center has moved to new infrastructure. There are minor changes to the data upload and download processes, so please review the documentation for Molecular Data Submission and File Download.

To ensure proper service during submissions and downloads, please upgrade your score-client to v5.10.0 and argo-data-submission workflow to v1.1.0.

**Comment by mcourtot** [comment]
Same - should we use full program names?

**Comment by bhavikbhagat93** [comment]
Since its a short announcement with hyperlink to the program page where full name exists, we can skip the full names for homepage.

**Comment by edsu7** [comment]
Update existing donor count:

~~Data Release 9.0 is now available, adding new molecular and clinical data for 1217 new donors and new molecular data for **161** existing donor from MUTO-INTL, POG-CA and P1000-US Programs.~~

**Comment by lindaxiang** [comment]
Can I suggest the following:

Data Release 9.0 is now available, adding 1 new program P1000-US, 1217 new donors and *** new molecular files from MUTO-INTL, POG-CA and P1000-US Programs.

@edsu7 , can you help to get that *** new molecular files?

**Comment by justincorrigible** [comment]
we can (should?) spell projects out, as done in the previous announcement `Mutographs (MUTO-INTL) and Polyethnic-1000 (P1000-US) programs.`
https://docs.icgc-argo.org/docs/release-notes/data-releases#data-release-80

**Comment by edsu7** [comment]
Data Release 9.0 is now available: adding 1217 new donors, first data release from BC Cancer Personalised OncoGenics Program [(POG-CA)](https://www.icgc-argo.org/page/97/bc-pogp),  and new molecular files from Mutographs [(MUTO-INTL)](https://www.icgc-argo.org/page/99/mutographs) and Polyethnic-1000 [(P1000-US)](https://www.icgc-argo.org/page/115/p-1000) totalling 43,107 files.

**Comment by lindaxiang** [comment]
~~Data Release 9.0 is now available, including 1,223 new donors, 43,107 new molecular files and associated clinical data from the CRUK Grand Challenge – Mutographs (MUTO-INTL), Polyethnic-1000 (P1000-US) and first release of whole genome sequencing (WGS) data for BC Cancer Personalised OncoGenics Program (POG-CA).~~

**Comment by bhavikbhagat93** [comment]
Final Text 23/05/2024 

Data Release 9.0 adds 1,223 new donors and 43,107 new molecular files and clinical data. This includes the first release of data from the BC Cancer Personalised OncoGenics Program (POG-CA) and updates from the CRUK Grand Challenge—Autographs (MUTO-INTL) and Polyethnic-1000 (P1000-US) programs.
