### ISSUE TITLE
ARGO Platform Release 44 - Homepage Announcement

### ISSUE THREAD

**Issue by bhavikbhagat93** [icgc-argo/roadmap#1138]
## Detailed Description

1. Add a new announcement to the top:

April ??, 2024: This release sees the addition of a exception manifest, this additional file in clinical data download zip includes information related to all applications applied to a program

2. Remove the oldest announcement:

November 6, 2023: Clinical data is now available to download! You can access the clinical data that corresponds to any file's donor through the download dropdown of the File Repository.

Additionally, a new version of the Treatment schema has been released which includes validation changes that permit clinical exceptions for treatment_type: ARGO Dictionary 1.20.

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0pQQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--630b590a83f717b7f0426775438fa9148bff20bb/image.png" alt="image.png" />

Update footer values for Data release and API version as per below details
- [Data Release 8.0](https://docs.icgc-argo.org/docs/release-notes/data-releases#data-release-80)
- [Software Release UI ?? - API ??](https://docs.icgc-argo.org/docs/release-notes/software-releases#february-14-2024-new-entity-exception-features)

**Comment by joneubank** [comment]
> April ??, 2024: This release sees the addition of a exception manifest, this additional file in clinical data download zip includes information related to all applications applied to a program

Suggested revision:

Downloads of ARGO clinical data will now include an Exceptions Manifest file. This new file includes a detailed list of any exceptions to the ARGO data dictionary that affect the donors included in the download.
