### ISSUE TITLE
ARGO Platform Release 44 - Software release note

### ISSUE THREAD

**Issue by bhavikbhagat93** [icgc-argo/roadmap#1139]
April ??, 2024: Clinical Exceptions Enhancement and Exception Manifest

Data Platform - UI ?- API ?

New Features​

- This release sees the addition of new ways for data submitters to accommodate missing values or data:
 -- **Treatment details exception**: This feature allows submitters to exclude entity, such as treatments details, for specific donors.

- Exception manifest: Clinical download zip will now include an additional file called exception manifest which includes information related to all exceptions applied to a program.

See our  [clinical data exception policy](https://www.icgc-argo.org/page/79/quality-standards-of-samples#:~:text=Clinical%20Data%20Exceptions%20Policy%C2%A0) for more information on gaining access to entity exceptions. We encourage data submitters to explore these new features and welcome any [feedback](https://www.icgc-argo.org/page/69/contact-us) they may have.

**Comment by joneubank** [comment]
Suggested updates:

This release adds another clinical data exception - **Treatment Details Exceptions** - which will accommodate submissions for donors that where a treatment was know to have occurred but none of the details of that treatment are available. **Treatment Detail exceptions** allow a donor to include treatments without their corresponding treatment detail entity being submitted.

Additionally, downloads of ARGO clinical data will now include an **Exceptions Manifest** file. This new file includes a detailed list of any exceptions to the ARGO data dictionary that affect the donors included in the download.
