### ISSUE TITLE
Bug - Missing Exception manifest from clinical download zip (File Repository)

### ISSUE THREAD

**Issue by bhavikbhagat93** [icgc-argo/roadmap#1141]
## Description

As a user when i visit File repository page -> filter on clinical data = Available -> Click on 'Download clinical data' -> The zip is missing the exception manifest tsv file

Programs tested on : - APGI-AU/HELLO-GB/SEQ-CA

## Acceptance 

Exception manifest should be part of clinical download zip on the  file repository page.

**Comment by demariadaniel** [comment]
This feature hypothetically allows downloading files from multiple programs
Example out put showing exceptions manifest w/ data from two programs (last record is TEST-QA, rest are PACA-CA)

<img width="483" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelptQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6b3cae4c3c898bb8f816082d9ba35ce271e3f8e3/Screenshot%202024-04-16%20at%2011.53.06%E2%80%AFAM.png" alt="Screenshot 2024-04-16 at 11.53.06 AM.png" />
