### ISSUE TITLE
Program: POG-CA exceptions follow up

### ISSUE THREAD

**Issue by edsu7** [icgc-argo/roadmap#1142]
- POG-CA collects some outcome data but not enough to flesh out a follow-up table (e.g. no follow up interval nor staging)
- presents a challenge as follow up is core
- a possible implement as follows:
1) Non-deceased donors - Add all treatments and indicated `lost_to_follow_up` on last treatment
2) Decease donors - add a "follow-up" record following last treatment

- Solution will be presented to metadata working group

**Comment by lindaxiang** [comment]
Exceptions were requested and approved by CMD

**Comment by edsu7** [comment]
Exceptions implemented and completed.
