### ISSUE TITLE
🐛 No Programs showing up on All program sidebar

### ISSUE THREAD

**Issue by bhavikbhagat93** [icgc-argo/roadmap#1154]
## Description

As a user [DCC admin]. when i login, I am unable to see the list of programs in the RDPC. 

<img width="260" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0t3QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--22f4cc082e1eb8ca537151be959d424d396aeaf3/image.png" alt="image.png" />

## Acceptance criteria

As a user, i should be able to see all programs list.

This is applicable for all roles [ DCC admin, RDPC admin, Program admin, Data submitter, Collaborator]

**Comment by UmmulkiramR** [comment]
adding the user to groups `dcc-admin` and  `PROGRAM-DASH-CA-ADMIN` made it work.
