### ISSUE TITLE
Banner for song download not available 

### ISSUE THREAD

**Issue by bhavikbhagat93** [icgc-argo/roadmap#1159]
## Description

With move from Azure to Cumulus for song and score. We have a known issue of file download not available for song.

Need following banner till the bug is resolved. 

TItle: File downloads not available
Description: Please be advised that there is a scheduled maintenance planned for the ICGC-ARGO platform. During this period, file downloads from song will be unavailable.

## Acceptance criteria

This banner should be available alongside current IT on ARGO prod.

**Comment by jmimico** [comment]
Suggested revision to text: Description: Please be advised that there is a scheduled maintenance planned for the ICGC-ARGO platform. During this period, protected data downloads will be unavailable.

**Comment by joneubank** [comment]
Slightly edited suggestion?

TItle: File downloads temporarily unavailable
Description: The ICGC ARGO platform is currently undergoing maintenance. During this time, file downloads will be unavailable. We expect to return to normal service before Friday Jun 28, 2024.
