### ISSUE TITLE
DR10 - Data release notes

### ISSUE THREAD

**Issue by edsu7** [icgc-argo/roadmap#1172]

**Comment by edsu7** [comment]
## Current
Data release 10 features new **296** donors and updates to 397 existing donors from programs:
- CRUK Grand Challenge – Mutographs ([MUTO-INTL](https://www.icgc-argo.org/page/99/mutographs))
- BC Cancer Personalized OncoGenomics Program ([POG-CA](https://www.icgc-argo.org/page/97/bc-pogp))
- Polyethnic-1000 ([P1000-US](https://www.icgc-argo.org/page/115/p-1000))

<table>
    <thead>
        <tr>
            <th>Program</th>
            <th></th>
            <th>Clinical</th>
            <th>DNA-Seq Alignment</th>
            <th>Mutect Variant</th>
            <th>Sanger Variant</th>
            <th>Total Changes</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td rowspan=2>POG-CA</td>
            <td rowspan=1>New</td>
            <td rowspan=1>217</td>
            <td rowspan=1>217</td>
            <td rowspan=1>216</td>
            <td rowspan=1>216</td>
            <td rowspan=1>217</td>
        </tr>
        <tr>
            <td rowspan=1>Update</td>
            <td rowspan=1></td>
            <td rowspan=1></td>
            <td rowspan=1></td>
            <td rowspan=1>239</td>
            <td rowspan=1>239</td>
        </tr>
        <tr>
            <td rowspan=2>MUTO-INTL</td>
            <td rowspan=1>New</td>
            <td rowspan=1>79</td>
            <td rowspan=1>79</td>
            <td rowspan=1>79</td>
            <td rowspan=1>78</td>
            <td rowspan=1>79</td>
       </tr>
       <tr>
            <td rowspan=1>Update</td>
            <td rowspan=1></td>
            <td rowspan=1></td>
            <td rowspan=1>1</td>
            <td rowspan=1>155</td>
            <td rowspan=1>156</td>
        </tr>
        <tr>
            <td rowspan=2>P1000-US</td>
            <td rowspan=1>New</td>
            <td rowspan=1></td>
            <td rowspan=1></td>
            <td rowspan=1></td>
            <td rowspan=1></td>
            <td rowspan=1></td>
       </tr>
       <tr>
            <td rowspan=1>Update</td>
            <td rowspan=1></td>
            <td rowspan=1>1</td>
            <td rowspan=1>1</td>
            <td rowspan=1>1</td>
            <td rowspan=1>2</td>
        </tr>
        <tr>
            <td rowspan=2>DR10.0 Summary</td>
            <td rowspan=1>New</td>
            <td rowspan=1>296</td>
            <td rowspan=1>296</td>
            <td rowspan=1>295</td>
            <td rowspan=1>294</td>
            <td rowspan=1><b>296<b></td>
       </tr>
       <tr>
            <td rowspan=1>Update</td>
            <td rowspan=1></td>
            <td rowspan=1>1</td>
            <td rowspan=1>2</td>
            <td rowspan=1>395</td>
            <td rowspan=1><b>397<b></td>
        </tr>
    </tbody>
</table>

## Old Version
Data release 10 features new **297** donors and updates to **396** existing donors from programs:
CRUK Grand Challenge – Mutographs ([MUTO-INTL](https://www.icgc-argo.org/page/99/mutographs))
BC Cancer Personalised OncoGenics Program ([POG-CA](https://www.icgc-argo.org/page/97/bc-pogp))
Polyethnic-1000 ([P1000-US](https://www.icgc-argo.org/page/115/p-1000))

<table>
    <thead>
        <tr>
            <th>Program</th>
            <th></th>
            <th>Clinical</th>
            <th>DNA-Seq Alignment</th>
            <th>Mutect Variant</th>
            <th>Sanger Variant</th>
            <th>Total Changes</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td rowspan=2>POG-CA</td>
            <td rowspan=1>New</td>
            <td rowspan=1>217</td>
            <td rowspan=1>217</td>
            <td rowspan=1>216</td>
            <td rowspan=1>216</td>
            <td rowspan=1>217</td>
        </tr>
        <tr>
            <td rowspan=1>Update</td>
            <td rowspan=1></td>
            <td rowspan=1></td>
            <td rowspan=1></td>
            <td rowspan=1>239</td>
            <td rowspan=1>239</td>
        </tr>
        <tr>
            <td rowspan=2>MUTO-INTL</td>
            <td rowspan=1>New</td>
            <td rowspan=1>79</td>
            <td rowspan=1>79</td>
            <td rowspan=1>79</td>
            <td rowspan=1>78</td>
            <td rowspan=1>79</td>
       </tr>
       <tr>
            <td rowspan=1>Update</td>
            <td rowspan=1></td>
            <td rowspan=1></td>
            <td rowspan=1>1</td>
            <td rowspan=1>155</td>
            <td rowspan=1>156</td>
        </tr>
        <tr>
            <td rowspan=2>P1000-US</td>
            <td rowspan=1>New</td>
            <td rowspan=1>1</td>
            <td rowspan=1>1</td>
            <td rowspan=1>1</td>
            <td rowspan=1></td>
            <td rowspan=1>1</td>
       </tr>
       <tr>
            <td rowspan=1>Update</td>
            <td rowspan=1></td>
            <td rowspan=1></td>
            <td rowspan=1></td>
            <td rowspan=1>1</td>
            <td rowspan=1>1</td>
        </tr>
        <tr>
            <td rowspan=2>DR10.0 Summary</td>
            <td rowspan=1>New</td>
            <td rowspan=1>297</td>
            <td rowspan=1>297</td>
            <td rowspan=1>296</td>
            <td rowspan=1>294</td>
            <td rowspan=1><b>297<b></td>
       </tr>
       <tr>
            <td rowspan=1>Update</td>
            <td rowspan=1></td>
            <td rowspan=1></td>
            <td rowspan=1>1</td>
            <td rowspan=1>395</td>
            <td rowspan=1><b>396<b></td>
        </tr>
    </tbody>
</table>

|Program| Clinical | DNA-Seq Alignment | Mutect Variant | Sanger Variant |
|--|--|--|--|--|
|POG-CA| $${\color{blue}217}$$ | $${\color{blue}217}$$ | $${\color{blue}216}$$ | $${\color{blue}216}$$ |
||  | | |$${\color{red}239}$$|
|MUTO-INTL| $${\color{blue}12}$$ | $${\color{blue}12}$$ | $${\color{blue}12}$$ | $${\color{blue}12}$$ |
||  |  | $${\color{red}1}$$ | $${\color{red}155}$$|
|P1000-US| $${\color{blue}1}$$ | $${\color{blue}1}$$ | $${\color{blue}1}$$||
|| |  | | $${\color{red}1}$$|
|Total| $${\color{blue}230}$$|$${\color{blue}230}$$ |$${\color{blue}229}$$ | $${\color{blue}228}$$|
|| |  |  $${\color{red}1}$$| $${\color{red}365}$$|

$${\color{blue}New\ Donors}$$

$${\color{red}Updated\ Donors}$$



|Program| Clinical | DNA-Seq Alignment | Mutect Variant | Sanger Variant |
|--|--|--|--|--|
|POG-CA| $${\color{blue}217}$$ | $${\color{blue}217}$$ | $${\color{blue}216}$$ | $${\color{blue}216}$$ $${\color{red}239}$$|
|MUTO-INTL| $${\color{blue}12}$$ | $${\color{blue}12}$$ | $${\color{blue}12}$$ $${\color{red}1}$$ | $${\color{blue}12}$$ $${\color{red}155}$$|
|P1000-US| $${\color{blue}1}$$ | $${\color{blue}1}$$ | $${\color{blue}1}$$| $${\color{red}1}$$|

$${\color{blue}New\ Donors}$$

$${\color{red}Updated\ Donors}$$

Notes:
- update numbers to reflect P1000-US "new" donor as "updated"

**Comment by lindaxiang** [comment]
The numbers are correct to me. Thanks @edsu7 !

**Comment by ciaranschutte** [comment]
@bhavikbhagat93 this data release has been completed. I will close this ticket.
