### ISSUE TITLE
Remove POG-CA donors and sample

### ISSUE THREAD

**Issue by edsu7** [icgc-argo/roadmap#1179]
Steve indicated the following samples were incorrectly submitted and needs to be cleaned from the dashboard.
Due to the clinical delete API not functioning, developers had to modify the database directly.

|DonorId|SubmitterDonorId|Status SONG| Status Clinical|
|---|---|---|---|
|DO254256|26034|No data|No data|
|DO254253|27319|No data|No data|
|DO254255|25435|No data|No data|
|DO254254|26182|No data|No data|

|SpecimenId|SubmitterSpecimenId|Status SONG| Status Clinical|
|---|---|---|---|
|SP217818|27319-OCT-1-P00814|No data|No data|
|SP217816|26182-OCT-1-P00447|No data|No data|
|SP217819|25435-OCT-1-P00603|No data|No data|
| |26034-OCT-1-P00277|Deleted|Deleted|

|SampleId|SubmitterSampleId|Status SONG| Status Clinical|
|---|---|---|---|
|SA617968|P00814|No data|No data|
|SA617965|P00447|No data|No data|
|SA617966|P00603|No data|No data|
| |P00277| Deleted| Deleted |

**Comment by joneubank** [comment]
Donors have been removed from the Clinical DB.

**Comment by edsu7** [comment]
Notified Steve, can close when he confirms.

**Comment by edsu7** [comment]
Steve confirmed removal. Closing
