### ISSUE TITLE
ICGC25k/PCAWG: add capturing chip design files for the PCAWG Pilot-50 validation dataset to ICGC25k release open/controlled buckets

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/roadmap#1182]
We received ARGO helpdesk request asking for the target region BED files for the PCAWG Pilot-50 validation dataset. It would be beneficial to the researcher if we could share these region BED files into the ICGC25k release open/controlled buckets.

Todo
- [x]  Please ungzip the attached [pilot50_capture-design-files.tar.gz](https://github.com/user-attachments/files/17231006/pilot50_capture-design-files.tar.gz), and upload the whole folder (`pilot50_capture-design-files`) to both open & controlled release buckets under directory `/PCAWG` as subfolder.

Reference:
- How to access ICGC-25k release data: https://docs.icgc-argo.org/docs/data-access/icgc-25k-data#accessing-icgc-25k-release-data

**Comment by yalturmes** [comment]
Data from the archive has been uploaded to both open and controlled buckets successfully.
