### ISSUE TITLE
DR11 - Rename P1000-US samples

### ISSUE THREAD

**Issue by edsu7** [icgc-argo/roadmap#1192]
P1000-US would like to convert the following sample IDs:

|old submitter_sample_id|new submitter_sample_id|
|--|--|
|JVV004T|JVV004T-L1-XUDM569|
|JVV006T|JVV006T-L2-NFGU004|
|JVV009T|JVV009T-L2-GHSJ273|
|JVV010T|JVV010T-L2-SLJJ778|
|JVV011T|JVV011T-L1-XGGS072|
|JVV013T|JVV013T-L1-VBXO772|
|JVV017T|JVV017T-L1-OJGU960|
|JVV018T|JVV018T-L1-EIKV043|
|JVV020T|JVV020T-L2-CWFC429|
|JVV021T|JVV021T-L2-VPGE753|
|JVV022T|JVV022T-L2-DCKH469|
|JVV024T|JVV024T-L2-BXLZ430|
|JVV027T|JVV027T-L2-YGCK063|
|JVV031T|JVV031T-L2-WXOV966|
|JVV033T|JVV033T-L2-MAII842|
|JVV034T|JVV034T-L1-ZZTR357|
|JVV036T|JVV036T-L2-INDL458|
|JVV038T|JVV038T-L1-NPQX836|

- no molecular data has been submitted yet
- only **sample** IDs, should not affect other clinical records

For reference:
Donor IDs
|donor|donor_argo|specimen|specimen_argo|sample|sample_argo|
|--|--|--|--|--|--|
|JVV006|DO256475|JVV006T|SP221238|JVV006T|SA621381|
|JVV011|DO256476|JVV011T|SP221240|JVV011T|SA621384|
|JVV033|DO256477|JVV033T|SP221261|JVV033T|SA621419|
|JVV021|DO256478|JVV021T|SP221253|JVV021T|SA621403|
|JVV013|DO256479|JVV013T|SP221239|JVV013T|SA621394|
|JVV009|DO256480|JVV009T|SP221237|JVV009T|SA621387|
|JVV034|DO256481|JVV034T|SP221270|JVV034T|SA621418|
|JVV036|DO256482|JVV036T|SP221268|JVV036T|SA621407|
|JVV004|DO256483|JVV004T|SP221236|JVV004T|SA621383|
|JVV020|DO256484|JVV020T|SP221265|JVV020T|SA621404|
|JVV038|DO256485|JVV038T|SP221256|JVV038T|SA621401|
|JVV010|DO256487|JVV010T|SP221234|JVV010T|SA621391|
|JVV024|DO256489|JVV024T|SP221246|JVV024T|SA621415|
|JVV018|DO256490|JVV018T|SP221247|JVV018T|SA621416|
|JVV031|DO256491|JVV031T|SP221255|JVV031T|SA621402|
|JVV022|DO256492|JVV022T|SP221248|JVV022T|SA621410|
|JVV017|DO256493|JVV017T|SP221258|JVV017T|SA621393|
|JVV027|DO256494|JVV027T|SP221269|JVV027T|SA621406|

**Comment by joneubank** [comment]
18  donors updated, sample submitter IDs have been replaced with the new values.

**Comment by edsu7** [comment]
Francis is a happy camper. Closing
