### ISSUE TITLE
DR11 - Remove POG-CA samples V2

### ISSUE THREAD

**Issue by edsu7** [icgc-argo/roadmap#1193]
The following specimens need to be removed from clinical:

|specimenId|argo_specimen_Id|
|--|--|
|65248-FFPE-1-F130022|SP221333|
|65248-OCT-1-F138870|SP221470|
|65248-PB-F138869|SP221471|

Which have the following samples:
|sampleId|argo_sample_Id|
|--|--|
|F130022|SA621512|
|F138870|SA621619|
|F138869|SA621620|

associated with the following donor:
|donorId|argo_donor_Id|
|--|--|
|65248|DO256498|

- specimens do not have data in song
- no additional clinical data attached to specimens
- Note donor has other specimens that must be kept.

**Comment by joneubank** [comment]
Updated Donor, removed 3 specimens.

**Comment by edsu7** [comment]
Notified program.

**Comment by edsu7** [comment]
Steve is a happy camper. Closing
