### ISSUE TITLE
Deploy and configure SMTP

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/roadmap#164]
What are we going to use as our SMTP to send email? 
-- We would like to use the SMTP server that is already set up 
-- request access from Peter

**Comment by rosibaj** [comment]
@akachru-github mailhog is not a production service - it was for the dev testing only.  We should discus with @joneubank what we want to do here as a solution

**Comment by rosibaj** [comment]
Discussion - we would like to use the established gmail server

**Comment by blabadi** [comment]
https://support.google.com/a/answer/176600?hl=en

**Comment by blabadi** [comment]
what we need is to use option 2 (Gmail SMTP Server requirements)  - allows up to 2k mails per day, more than enough.

they need to:
- create argo an email account (something-for-argo@icgc-argo.org, password) and provide that to us

**Comment by rosibaj** [comment]
dcc@icgc-argo.org has been set-up as the account for this.

**Comment by rosibaj** [comment]
Still needs to be tested in production environment - Jan 29, 2020
