### ISSUE TITLE
Investigate Kafka brokering 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#174]
https://wiki.oicr.on.ca/display/icgcargotech/Phase+One+Infrastructure

need to make kafka deployable cause cant do it in K8s

**Comment by lepsalex** [comment]
@andricDu @rosibaj 

Please read and let me know any feedback:

https://wiki.oicr.on.ca/display/icgcargotech/Kafka+Deployment+Infrastructure

**Comment by lepsalex** [comment]
Approved by @andricDu
