### ISSUE TITLE
Deployment to Production Environment 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#191]
For each of these services, deploy the services required for OICR deployment:

- [x] Ego
- [x] Lectern
- [x] Clinical
- [x] Platform UI
- [x] Program Service 
- [x] Gateway API
- [x] Mail Server 
- Jenkins is set up, so the charts need to set up for each of these.
- new production folder in argo-infra

**Comment by blabadi** [comment]
services deployed
links on wiki 
jenkins task created and tested - uses argo-infra
