### ISSUE TITLE
Production Data Test 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#202]
- [x] Create the dcc + daco groups and policies 
- [x] Create application groups and policies 
- [x] Snapshot this exact setup for restore late 
- [x] Smoke test the set-up and make sure that all data/services are communicating properly.

**Comment by blabadi** [comment]
https://wiki.oicr.on.ca/display/icgcargotech/How+to+Dump+databases

**Comment by blabadi** [comment]
only smoke test left, tomorrow will create program and submit donors to it then restore db

**Comment by blabadi** [comment]
tested clinical registration and submission through the UI and all went good, smoke test is done

I rolled back the databases of :
ego, program_service, clinical back to initial state
