### ISSUE TITLE
 Daco2Ego cron job for Production Ego 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#203]
@andricDu  details pls!

**Comment by andricDu** [comment]
Please refer to this: https://wiki.oicr.on.ca/display/icgcargotech/Daco2Ego+Prod
This page has restricted viewership.

**Comment by blabadi** [comment]
waiting on access from IT to add the argo config

**Comment by blabadi** [comment]
config added, we need to work with IT now to add the new cron job and test it against the new configs

**Comment by blabadi** [comment]
IT added the job, but there is a network issue from the host to our cluster, working with Henrich on that

**Comment by blabadi** [comment]
the job ran this morning and all is good
