### ISSUE TITLE
Develop the Production Nextflow Workflow Formula

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#213]
https://wiki.oicr.on.ca/display/icgcargotech/Nextflow+Workflow+Requirements+and+Style+Guide

Define things like this::
- required parameters
- styling
- retryable errors 

## Exit Criteria
- specs for workflow generation on the wiki 
- requirements for the workflow to be optimized on the cluster

**Comment by lepsalex** [comment]
styling and required params successfully implemented with Junjun and team, retry-able errors will come later. closing for now.
