### ISSUE TITLE
Set up kibana for dev/qa ES

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#220]
We have es set up for dev, but not Kibana. 

http://es.dev.argo.cancercollaboratory.org/
http://es.qa.argo.cancercollaboratory.org/

**Comment by hlminh2000** [comment]
Kibana has been set up on dev and qa at:
- dev: http://kibana.dev.argo.cancercollaboratory.org/
- qa: http://kibana.qa.argo.cancercollaboratory.org/

A new provision job was created on Jenkins for this task: https://jenkins.qa.cancercollaboratory.org/blue/organizations/jenkins/ARGO%2Fprovision%2Fkibana/activity
