### ISSUE TITLE
Investigate: Migration solution for clinical/lectern

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#221]
Services that use a Mongo datastore need to have a tool that manages migrations. 

The scope of this ticket is to investigate options and select a tool to use for migrations. 

Options to consider:
- https://www.npmjs.com/package/migrate-mongo

**Comment by blabadi** [comment]
clinical side implemented in PR https://github.com/icgc-argo/argo-clinical/pull/386/
