### ISSUE TITLE
General Kafka connector to services like Maestro 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#222]
- RDPCs will be writing events to a locally installed Kafka. 
- Maestro will be running here, at the OICR/DCC.  
- The events that get sent to the Kafka within the RDPC need to be communicated out to teh OICR Kafka/Maestro for file indexing to proceed. 

There will be 
1. A service built that will be installed as part of each RDPC

The scope of this ticket is to make thee service that will live at the RDPC.

**Comment by blabadi** [comment]
wild service appeared ! 
https://github.com/icgc-argo/kship/tree/develop
helm chart created and published 
will deploy it when the platform gateway side of things is ready to integrate things together
no test needed for this now

**Comment by rosibaj** [comment]
It was super effective!

**Comment by blabadi** [comment]
blocked until I do the gateway part, will test both together and close them when ready
