### ISSUE TITLE
Deploy Maestro to the RDPC production environment 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#242]
- [ ] Deploy the latest version of Maestro to the RDPC 
- [ ] If there are any issues with the connection between Maestro and the latests version of Songs
--- ask @blabadi  for guidance on changes
--- investigate what changes would need to be made

**Comment by blabadi** [comment]
@rosibaj I thought Maestro will live in the argo platform cluster not in RDPCs

**Comment by rosibaj** [comment]
@blabadi Within the RDPC, there is a need to search and know which analysis have been compelted. 

This needs to be independent of all other systems, so a maestro deployed with the RDPC setup can index song and be extended by workflow information.  @lepsalex can help explain how this will work. 

This does not change the need for a maestro in the Argo Platform Cluster.
