### ISSUE TITLE
NFS Clean-up Strategy

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#247]
- [ ] Automate deletion of all intermediate files on a successful workflow run, by adding a step in the workflow after publish.  Explore if Nextflow has a mechanism to do this.  
- [ ] Develop a specification of how files can be cleared, including how to develop a method to target the files of failed.

**Comment by lepsalex** [comment]
Integrated as part of workflow: https://github.com/icgc-argo/dna-seq-processing-wfs/blob/78f53ca80471b726388c4518c21489cf3e310fe7/dna-seq-alignment/main.nf#L257

In the future we can look at a more complicated solution if necessary but for now this simple solution accomplishes the majority of our needs.
