### ISSUE TITLE
Update clincal docker containers to run as non-root 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#251]
Update platform docker containers to run as non-root 
- [x] argo-clinical (https://github.com/icgc-argo/argo-clinical/blob/master/Dockerfile)

-- need to verify that each one runs as non-root user

**Comment by blabadi** [comment]
verifed on argo-dev
```
/app $ ls -trl
total 24
drwxr-xr-x    1 node     node          4096 Feb 14 16:27 dist
drwxr-xr-x    1 node     node         20480 Feb 14 16:28 node_modules
/app $ id
uid=1000(node) gid=1000(node) groups=1000(node)
/app $ 
```

related PR https://github.com/icgc-argo/argo-clinical/pull/374

**Comment by blabadi** [comment]
chart also updated: https://github.com/icgc-argo/charts/pull/50/files
