### ISSUE TITLE
Verify Licences on all ARGO Platform code

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#255]
- make sure all repositories have the AGPLv3 licence added
- should be on every file like this: 
https://github.com/icgc-dcc/dcc-portal/blob/develop/dcc-portal-server/src/main/java/org/icgc/dcc/portal/server/ServerMain.java 

- make sure licence is update/

- the blurb should say:

```
Copyright (c) 2020 The Ontario Institute for Cancer Research. All rights reserved

This program and the accompanying materials are made available under the terms of 
the GNU Affero General Public License v3.0. You should have received a copy of the 
GNU Affero General Public License along with this program.
 If not, see <http://www.gnu.org/licenses/>.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY                           
EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES                          
OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT                           
SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,                                
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED                          
TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;                               
OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER                              
IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN                         
ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 


```

Repositories to update:
- [x] platform-ui (https://github.com/icgc-argo/platform-ui/pull/1528)
- [x] platform-api (https://github.com/icgc-argo/platform-api/pull/239/)
- [x] clinical (https://github.com/icgc-argo/argo-clinical/pull/548)
- [x] argo-docs (https://github.com/icgc-argo/argo-docs/pull/272)
- [x] ago-dictionary (https://github.com/icgc-argo/argo-dictionary/pull/176)
- [x] program-service (https://github.com/icgc-argo/program-service/pull/332)
- [x] ego-token-utils  (https://github.com/icgc-argo/ego-token-utils/pull/42)

Verify github repo

Check License file on Github:
- [x] platform-ui
- [x] platform-api
- [x] clinical
- [x] argo-docs
- [x] ago-dictionary
- [x] program-service
- [x] ego-token-utils
- [x] icgc-argo/charts

**Comment by blabadi** [comment]
you can use Intellj in the following steps:

1- go to `settings` 
2- search for `copyright` and go to sub item `copyright profiles`

3- create a copy right profile with the following text (copy paste this) and give it a name:
```
Copyright (c) $today.year The Ontario Institute for Cancer Research. All rights reserved

This program and the accompanying materials are made available under the terms of 
the GNU Affero General Public License v3.0. You should have received a copy of the 
GNU Affero General Public License along with this program.
 If not, see <http://www.gnu.org/licenses/>.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY                           
EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES                          
OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT                           
SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,                                
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED                          
TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;                               
OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER                              
IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN                         
ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

```

4- hit apply
5- go back to top level `Copyright`, 
6- click the `+` and add that to `All`, then `Apply` and close settings
7- right click the module root folder
8- hit `Update Copyrights`
9- Profit

also it's useful to check in the `.idea/copyrights` folder for future changes and updates
