### ISSUE TITLE
Deploy Rollcall 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#256]
- [ ] Do the stuff to deploy it
- [ ] Make a chart
- [ ] Provision pipeline

**Comment by hlminh2000** [comment]
associated PRs: 
- https://github.com/overture-stack/helm-charts/pull/20
- https://github.com/overture-stack/charts-server/pull/9
- https://github.com/OICR/argo-infra/pull/58


then trigger new pipeline at: https://jenkins.qa.cancercollaboratory.org/blue/organizations/jenkins/ARGO%2Fprovision%2Frollcall/activity
also, re-provision lectern in argo

Rollcall is deployed at:
- Dev: https://rollcall.dev.argo.cancercollaboratory.org/
- QA: https://rollcall.qa.argo.cancercollaboratory.org/

Note: there's an application bug in rollcall that prevents the app from working. @jaserud is aware.
