### ISSUE TITLE
Create new project with song-rdpc-collab-backups

### ISSUE THREAD

**Issue by rtisma** [icgc-argo/roadmap#264]
## Purpose
For backing up song-rdpc-collab postgres data to an s3 bucket, using S3 credentials that cannot access the `icgc-argo-collab` bucket

## Problem
Since S3 credentials are scoped to a project and not bucket, it is not possible to create the backup bucket in the same project containing the `icgc-argo-collab` bucket that has S3 credentials that can ONLY access the backup bucket and not the `icgc-argo-collab` bucket.

Song should not have any access to controlled data. This adds a layer of security.

## Solution
Create another project just for song backups, and S3 credentials with RW access to buckets.  The bucketname that will be use is `song-rdpc-collab-backups`

**Comment by akachru-github** [comment]
re-used an old project. complete.
