### ISSUE TITLE
Update migration of lectern

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#265]
Followup to #221
@blabadi implemented the migration for the clinical Mongodb, Lectern needs to be done in a similar fashion

**Comment by rosibaj** [comment]
@blabadi @hlminh2000 @andricDu Is this ticket still valid/needed?

**Comment by hlminh2000** [comment]
Unless there's a migration that needs to be run, I don't think there's anything we need to do. For when we do have a migration to run though, we can note to to implement it in the same way as clinical.
