### ISSUE TITLE
Deploy Infrastructure for production dashboard

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#272]
- [x] Aggregator 
- [x] Rollcall
- [x] Kakfka Topic configuration 
- [x] Please update the Kakfa topics that get created here:
https://wiki.oicr.on.ca/display/icgcargotech/Kafka+Topics
- [x] Update Vault with new secrets.
- [x] Update argo-infra with secrets 
https://github.com/OICR/argo-infra

**Comment by rosibaj** [comment]
need to decide password protection

**Comment by hlminh2000** [comment]
aggregator and rollcall has both been deployed to prod. I've also updated prod config for gateway as well, without applying it to prod yet, will leave this in awaiting deploy to reflect the gateway status

**Comment by rosibaj** [comment]
verified indexing is working on dashboard
