### ISSUE TITLE
Platform Environment Parity: Upgrade Kafka in argo-qa (5.2.1) to version in argo-prod (5.4.0)

### ISSUE THREAD

**Issue by rtisma** [icgc-argo/roadmap#275]
version in argo-qa and argo-dev is 5.2.1
version in argo-prod and rdpc-collab is 5.4.0

**Comment by rosibaj** [comment]
needs to be confirmed for validity

**Comment by blabadi** [comment]
I've confirmed all environments now run the same kafka image 
`docker.io/bitnami/kafka:2.4.0-debian-10-r39 `
and same helm chart version 7.3.1

**Comment by akachru-github** [comment]
woooo!
