### ISSUE TITLE
Update argo-gatway-dev (1.5.2-b453085) to 1.5.2

### ISSUE THREAD

**Issue by rtisma** [icgc-argo/roadmap#278]
argo gateway should match qa

**Comment by akachru-github** [comment]
argo-dev	1.5.2-b453085
argo-prod	1.5.2
argo-qa	1.5.2

Are you saying the difference here is because argo-dev is a snapshot? Just wanted to confirm.

**Comment by rtisma** [comment]
closing since argo-dev is ahead of qa
