### ISSUE TITLE
Create rdpc-collab-qa namespace on rdpc dev cluster

### ISSUE THREAD

**Issue by rtisma** [icgc-argo/roadmap#291]
https://wiki.oicr.on.ca/pages/viewpage.action?spaceKey=icgcargotech&title=Environments

currently, only the rdpc-collab-dev namespace exists. A rdpc-collab-qa namespace will be needed for...qa-ing

**Comment by akachru-github** [comment]
Correct. We had talked about this as a team and built a workflow development process that does not at this point required an rdpc-collab-qa environment. We will be using rdpc-collab-dev and rdpc-collab (prod) only for now. 

If we find a need down the road, we can build rdpc-collab-qa namespace.
