### ISSUE TITLE
Kubernetes config - audit logging - fluentd input

### ISSUE THREAD

**Issue by henro001** [icgc-argo/roadmap#297]
Audit logging is enabled on Kube clusters but fluentd does not forward.Enable input in fluentd

- [x] Argo prod
- [x] Argo QA
- [x] RDPC prod
- [x] RDPC dev

**Comment by rosibaj** [comment]
Currently we have the logging set up, but not all of the filters set up in kibnana. 

moving this out of sprint to be completed later.
