### ISSUE TITLE
Design & Tech Meeting

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#3]
Decide the technologies and contracts that we want to commit to. Decide:
- Framework for Program API
- Over the wire formats
- API design
- Database (postgeres, access etc)

Meet Thursday the 20th

**Comment by alekspejovic** [comment]
Meeting decisions for architecture:

- Framework :  SpringBoot (JDK 11, build with Maven)
- Communication framework : GRPC (HTTP/2, Protocol Buffers - investigate v2 vs v3)
- Database : Postgres

- Devops : Docker, Kubernetes, Istio (supports service deployment on Kubernetes - Bashar will prepare demo)
