### ISSUE TITLE
RDPC prod cluster: Jenkins configuration

### ISSUE THREAD

**Issue by rtisma** [icgc-argo/roadmap#302]
A jenkins server will be installed on the rdpc prod cluster. this will be responsible for deploying prod services. For now, @rtisma and @henro001 should have admin access to this jenkins server

This jenkins instance will be similar to the argo-prod jenkins server. It will be responsible for provisioning the rdpc-collab (prod) namespace.

**Comment by rosibaj** [comment]
confirmed this ticket is a duplicate; jenkins server already installed by Dusan.
