### ISSUE TITLE
RDPC Backups: Jenkins configuration

### ISSUE THREAD

**Issue by rtisma** [icgc-argo/roadmap#310]
- This ticket includes the documentation, implementation and testing of the backup and restore process.

**Comment by akachru-github** [comment]
@yalturmes , @henro001 , when we set up the RDPC Jenkins, did that include the backups as well?

**Comment by yalturmes** [comment]
Jenkins backups for RDPC DEV/QA and PROD have been configured.
Detailed step-by-step instructions have been documented here:
https://wiki.oicr.on.ca/display/icgcargotech/Jenkins+backup+setup+for+RDPC
