### ISSUE TITLE
Workflow pod - Change service account

### ISSUE THREAD

**Issue by henro001** [icgc-argo/roadmap#311]
Workflow pods (pods with access to Kubernetes API) run with `default` service account, with `edit` permission in the namespace. This should be changed to explicitly defined account.

- If the management is running in its own service account, and it launches new pods, will they be under the same service accounts?
- need to verify if nextflow can define a service account or if it determines the launch service account from the parent 
- one executor pod and multiple processor pods (by label) 

For workflow-management: 
- [ ] update helm chart to create a service account 
- [ ] use the service account in the kubernetes scope of the nextflow config 
- [ ] add rbac for the parent service account in the chart  ( @yalturmes  to help here)

**Comment by rosibaj** [comment]
- needs deployment 
- check with devops before deploying to prod
