### ISSUE TITLE
DACO2EGO is performing different actions for ICGC Prod vs ARGO Prod

### ISSUE THREAD

**Issue by christinayung** [icgc-argo/roadmap#312]
![image.png](https://images.zenhubusercontent.com/5bbe9c22307bc60241e3aa93/a2de79e9-5e63-4f5c-8929-d02ae28d97be)

**Comment by rosibaj** [comment]
- make channel 
- separate scripts to each channel 
- diagnose the issues

**Comment by rosibaj** [comment]
this was covered in another ticket - closing as duplicate
