### ISSUE TITLE
Move dev/qa Kafka connections to new Kafka deploy

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#318]
Two services need to be pointed to the new Kafka: 
- [ ] clinical 
- [ ] aggregator

**Comment by rosibaj** [comment]
@blabadi so that i understand the process, this does not need to be moved through different deploy/release columns?

**Comment by blabadi** [comment]
> @blabadi so that i understand the process, this does not need to be moved through different deploy/release columns?

This was only for Dev and QA envs, clinical on prod doesn't talk to kafka
