### ISSUE TITLE
Sample registration: specimen_tissue_source = 'Solid tissue'🐛 

### ISSUE THREAD

**Issue by c4cam** [icgc-argo/roadmap#321]
## Describe the bug

When I enter 'Solid tissue' in specimen_tissue_source, no matter how I format it ('Solid tissue' or 'Solid Tissue'), I get the error: The value does not match the previously registered value of Solid Tissue. Please correct your file or contact DCC to update the registered data. Maybe I'm doing something wrong? Help!

![image](https://user-images.githubusercontent.com/7540951/76547140-9ebf0180-6484-11ea-8496-d9af6ea42973.png)

**Comment by rosibaj** [comment]
@c4cam  Can you please let us know which sample id you are experiencing this error?

**Comment by wajiha-oicr** [comment]
Additionally, can we get the name of the program that this is regarding?

**Comment by c4cam** [comment]
Sure thing, @wajiha-oicr, it's 'OCCAMS-GB', I'll need to check the sample id when I get back in tomorrow, sorry. Thanks so much for looking into this :)

**Comment by rosibaj** [comment]
Hi again @c4cam!

It looks like this might have been the same issue as #322 - Let us know if you still experience this issue tomorrow when you try uploading again :)

**Comment by c4cam** [comment]
Awesome! Thanks @rosibaj!

**Comment by c4cam** [comment]
Success! @wajiha-oicr @rosibaj thank you so much!
