### ISSUE TITLE
Sample registration: sample_type = 'SAMPLE_TYPE_PLACEHOLDER'🐛 

### ISSUE THREAD

**Issue by c4cam** [icgc-argo/roadmap#322]
## Describe the bug

I get this error: The value does not match the previously registered value of SAMPLE_TYPE_PLACEHOLDER. Please correct your file or contact DCC to update the registered data.

When I try putting in 'SAMPLE_TYPE_PLACEHOLDER' I get a validation error. Do I need to update my previous DCC submission (sorry!)
![image](https://user-images.githubusercontent.com/7540951/76547367-f5c4d680-6484-11ea-84b8-e41377267da3.png)

**Comment by rosibaj** [comment]
Hi @c4cam! 

It looks like we had some leftover temporary testing data in your program . 
Can you please try registering your samples again now?

Rosi

**Comment by c4cam** [comment]
Thanks so much @rosibaj! Unfortunately it's evening time now in the UK and I can't test it from home (my IP isn't registered). I'll give it whirl first thing tomorrow though!

It's all looking good, well done :)

**Comment by c4cam** [comment]
Woooo! It works, happy days!!! Thanks @rosibaj :)
