### ISSUE TITLE
Deploy Arranger in ARGO 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#346]
follow up to https://github.com/icgc-argo/roadmap/issues/337 

- [ ] deploy and configure arranger in ARGO after changes 
- [ ] point it at a basic mapping and some fake documents provided on wiki 
https://wiki.oicr.on.ca/pages/viewpage.action?spaceKey=icgcargotech&title=File+Repository+Specification

**Comment by hlminh2000** [comment]
this is handled by #338 already. for Prod, this will be bind feature flag until data is ready in elasticsearch

**Comment by rosibaj** [comment]
@hlminh2000 i cant find a ticket #338 that makes sense - can you paste the full link here?

**Comment by hlminh2000** [comment]
Sorry, I transferred the ticket over to the gateway repo: https://github.com/icgc-argo/platform-api/issues/213
