### ISSUE TITLE
Platform Network Config: Ego - Ingress configuration

### ISSUE THREAD

**Issue by henro001** [icgc-argo/roadmap#350]
Ego ingress uses single ingress resource, with path based routing for both API and UI. to independently control access to each of them, we will need two separate ingress resources

**Comment by rosibaj** [comment]
@blabadi Can we discuss you helping with this?  We have quite a few infrastrucutre tasks to work towards production release?  @henro001 and I are wondering if you would be able to help setting this one up?

**Comment by blabadi** [comment]
yeah no problem
