### ISSUE TITLE
RDPC Ingress controller design 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#354]
We need a second instance of ingress controller in the RDPC

- 1st ingress controller will be for private, internal traffic
- 2nd ingress controller will be for public services (e.g. song/score)

This will be different than #350 because Platform is hosted with OICR and they use a load balancer.

**Comment by akachru-github** [comment]
https://wiki.oicr.on.ca/display/icgcargotech/Ingress+controller+configuration
