### ISSUE TITLE
Implement RDPC Network Policies

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#355]
- for all applications apply the network policy

**Comment by rosibaj** [comment]
@jmimico We'd like to have you help out on this setup! 
- the platform cluster has already had this set up so that can be an example 
- @henro001 can help supply additional details as well.

**Comment by lepsalex** [comment]
@jmimico as discussed on slack I've created a network topology diagram to help illustrate all the interconnection between pods better, hopefully this helps!

https://wiki.oicr.on.ca/display/icgcargotech/Pod+Networking+Diagram

**Comment by akachru-github** [comment]
Network policies have been applied to RDPC DEV, QA and PROD. 
Closing this ticket.
