### ISSUE TITLE
Ego - PSQL - Replication

### ISSUE THREAD

**Issue by henro001** [icgc-argo/roadmap#356]

**Comment by rosibaj** [comment]
@akachru-github is this handled in another ticket? or should it be on devops board?

**Comment by akachru-github** [comment]
I think this is irrelevant now. @henro001 , can you confirm?

**Comment by henro001** [comment]
@akachru-github i think the ultimate goal was to replicate across data centres to create secondary read-only db instance. at the moment we have HA postgres but no replication. Not sure if this is still the goal.

**Comment by akachru-github** [comment]
Ah, I see. OK. I think we can close this for now. We can create a new Epic to track this effort holistically.
