### ISSUE TITLE
Platform Monitoring: External cluster monitoring enabled

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/roadmap#365]
- We want external cluster monitoring in case the Kubs cluster goes down. 
- We can set this up like Collab via Uptime Robot:
  - Integrated with email and Slack. Supports up to 50 checks (we are using 2 for Collab) at 5 minute interval for free tier. We should use this as a general external monitor for something that is publicly accessible and implemented as the canary in the coal mine.

**Comment by akachru-github** [comment]
What is the most generic check for platform monitoring? What can tell us whether something is on fire? Consult dev team. Not a big effort, just need to know what to look for.

**Comment by akachru-github** [comment]
@blabadi , @andricDu , do you guys have thoughts on what basic external check we can do that can tell us whether something is on fire for the Platform?

**Comment by jmimico** [comment]
I've set up uptime robot to monitor https://docs.icgc-argo.org since it's a public site. It might be wise to have one more publicly accessible site to monitor that lives in the ARGO Platform environment.
