### ISSUE TITLE
Platform Backups: Support backup / restore for Postgres (Ego, Program Service)

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/roadmap#366]
- Using the template "Service Backup" Helm chart developed by Henrich, modify the chart to support postgres services. 
- This ticket includes testing and documenting the backup and restore process. 
---
Helm chart for etcd backups used as a template:
https://github.com/icgc-argo/kube-infra/tree/master/etcd-backup
Installation documentation:
https://wiki.oicr.on.ca/pages/viewpage.action?spaceKey=icgcargotech&title=ETCD+backups

**Comment by rosibaj** [comment]
@andricDu to confirm, this is deployed to production?  if no response, will close ticket.
