### ISSUE TITLE
Platform Backups: Replicate Cumulus NFS backup store to Collaboratory backup store

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/roadmap#370]
- Original intention:  Isilon will be the short term on-site backup store for the Platform
- What we have now: We are backing up to a Cumulus VM with NFS store while we wait for IT to plan out the adoption of Kerberos to satisfy our security needs on Isilon. 
- This will need to be synced to an off-site backup (Collab)

**Comment by jmimico** [comment]
Offsite backups have been set up. Details about implementation are in https://wiki.oicr.on.ca/display/icgcargotech/Backups+and+Restoration

**Comment by akachru-github** [comment]
@andricDu and @blabadi :

Right now: VM in Cumulus with attached storage is being used as the target for backups. This is now being replicated to Collab. This fulfills  our offsite requirement and security concerns.

You can see the details here: https://wiki.oicr.on.ca/display/icgcargotech/Backups+and+Restoration#BackupsandRestoration-Whereisitbeingbackedupandhowlongisitbeingkeptfor

Do we NEED to use Isilon for launch? We do not see a reason why until IT has completed their assessment of security and kerberos integration. Right now we feel we can launch with the VM solution. Let us know if you see an issue with this. If not, we can close this ticket.

**Comment by blabadi** [comment]
@akachru-github  I'm not aware of anything related to Kerberos and how things got there, so I really don't have an opinion here and it's better that decisions are made consistently.

**Comment by akachru-github** [comment]
Hi @andricDu , let me know if you have any strong feelings on this. If not, we will move ahead with this implementation and close this ticket as this replication is now set up. As backups are taken and stored in this location, the backups will automatically be replicated over to Collab.

**Comment by akachru-github** [comment]
Spoke to @andricDu , no issues with our current implementation. Will update the ticket to reflect the changes and close it out.
