### ISSUE TITLE
Initialize Maestro In Argo environments

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#375]
- Deploy the latest 3.0.0 RC Maestro in Platform in Dev.  An older maestro is there; that needs to be updated.
- We can use the RC branch to test; if there are no issues we will proceed to a full release
- connect it to the DEV RDPC Songs
- Index one-time the "whole song" repository
- connect with @henro001 if there needs to be any network policy information applied?
- note to minh; maestro doesn't have an ingress so might need to part forward to connect to the first index 

## Expected Outcome: 
A `file_centric` index generated by maestro is available in the platform ES to develop against.

**Comment by blabadi** [comment]
we have this tag ready with latest changes from develop: `overture/maestro:3.0.0.44f4e92-RC`
let's test that in `argo-dev` and if all good i'll tag `3.0.0` for QA

**Comment by blabadi** [comment]
@hlminh2000 get familiar with Maestro values please in here https://github.com/overture-stack/maestro/tree/master/maestro-app/src/main/resources/config

and if you need a quick walk through on how to trigger manual index requests (this: https://github.com/overture-stack/maestro/blob/master/maestro-app/src/main/java/bio/overture/maestro/app/infra/adapter/inbound/webapi/ManagementController.java#L108) let me know, but ideally you will need:
0- make sure the index is created and has the correct mapping 
1- port forward / use ingress if available
2- hit the url with postman (no swagger available) 
3- observe the logs and response

**Comment by blabadi** [comment]
there maybe egress rules (outbound traffict) that prevent maestro from reaching RDPC song, in case you notice a connectivity issue

**Comment by Buwujiu** [comment]
@hlminh2000 , here is maestro rdpc helm values: https://github.com/icgc-argo/rdpc-infra/blob/master/helm/maestro/dev/values.yaml

line 17 - 23 are song config, you can use the same config for argp deployment.
line 12 is ES url, you need to update this to argo ES url.
line 32 and 33 you also need to use argo ES password and username. 

QA helm values are here: 
https://github.com/icgc-argo/rdpc-infra/blob/master/helm/maestro/qa/values.yaml

**Comment by blabadi** [comment]
https://github.com/OICR/argo-infra/pull/278

**Comment by rosibaj** [comment]
@blabadi I tested on Friday and this worked great - I was able to take an analysis all the way from being a payload to being visible on the file repository. 

One question:  Would it be possible to point at the Song prod and index the whole repository so we can get a data preview of how it will look once we index?

**Comment by blabadi** [comment]
@rosibaj yes, I'll do that now and let you know

**Comment by rosibaj** [comment]
working great!

**Comment by blabadi** [comment]
maestro deployment updated in staging
mapping updated
collab rdpc qa song indexed
