### ISSUE TITLE
Platform Monitoring: Implement endpoint monitoring for Vault

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/roadmap#380]
Vault is not responding (from #361). Vault will be fixed once we have dedicated private ingress. Vault ingress has been deployed with private ingress IPs. Once there is private ingress, DNS will need to updated. Once completed, we can enable monitoring for vault.

**Comment by jmimico** [comment]
Adding Henro since this is more his wheelhouse.

**Comment by akachru-github** [comment]
Vault is currently being monitored by using a proxy that allows for internal network access. This satisfies the scope of this ticket.
