### ISSUE TITLE
RDPC Backups: Audit Database Restore Process

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/roadmap#382]
In the event that we have a restore, we need to complete an audit of restore

This ticket is to document the processs in restore:
- make sure that any orphaned records are removed
- release a report

**Comment by rosibaj** [comment]
@akachru-github @henro001 is this still needed?  I think we have completed this.

**Comment by akachru-github** [comment]
Technically we have done this only for individual services, but not as a complete system recovery of interdependent services, which is more of a disaster recovery scenario.
