### ISSUE TITLE
Spec the wes-argo-api schema 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#385]
Expected outcome: a graphql scheama for the wes-argo-api that we can work towards

User Stories: https://wiki.oicr.on.ca/pages/viewpage.action?pageId=123539599
Gateway Wiki: https://wiki.oicr.on.ca/display/icgcargotech/WES-ARGO-API+Design

**Comment by andricDu** [comment]
@rosibaj I've uploaded the schema to https://wiki.oicr.on.ca/display/icgcargotech/WES-ARGO-API+Design

It should be enough to meet what we require out of the MVP and I've tried to normalize the fieldname naming convention for IDs. We can continue to iterate on this as we work towards it. 

Please feel free to reopen this if I've missed the mark on something big or obvious. 

### Known Issues 
- Donor information at the moment is minimal and can be expanded later if we are required to connect to clinical.
