### ISSUE TITLE
Update Ego Ingress Configs (all environments)

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#386]
Deploy solutino from Network Config: Ego - Ingress configuration #350

Upgrade ego helm chart for all environments 
- [x] dev 
- [x] qa
- [x] prod

**Comment by blabadi** [comment]
deployed chart 1.0.0 to prod 
updated redirect uri to the new url
tested login and was able to access https://ui.ego.icgc-argo.org
also tested the backend url for regression and it seems working

**Comment by rosibaj** [comment]
verified on prod
- can login on downstream services correctly
- documentation updated with new url
- can login to ego ui and interact with swagger
