### ISSUE TITLE
Define heuristics to describe rate limiting scenarios

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/roadmap#389]
- We need to better understand how our system reacts to load: Which flows that, if over burdened, could cause crippling ripple effects across the platform?
-  Output: Document that describes what data we will need to track to define what "bad" performance scenarios there are. We can use these definitions to signal up stream to the F5 for rate limiting connections causing the performance problem.  
- Strategy at the Platform UI and API Gateway for identifying and classifying traffic

Write up on wiki and present to development group for review.

**Comment by hlminh2000** [comment]
# gateway traffics

## Primary traffic (minimal rate limit)
  - Authenticated traffic (contains `authorization` header in format `"Bearer ..."`)
  - Traffic from platform UI
    + `referrer` header containing platform-ui.dev.argo.cancercollaboratory.org with `user-agent` specifying a browser. 
    + Priority given to:
      + computer-based OS: `Windows`, `Macintosh`, `macOS`, `Mac OS X`, `Mac`, `Linux`, `NetBSD`, `OpenBSD`, `freeBSD`
      + common tablet: `iPad`
  - `/kafka` endpoint: white list to specific IPs only. 
## Best-effort traffic (limit under heavy traffic)
  - Traffic from non-browsers (`user-agent` header specifying non-browsers (`curl`,...))
  - Traffic with no `user-agent` header
  - unauthenticated traffic (does not contain `authorization` header)
## Undesired traffic
  - `/kafka` coming from unknown IPs

In future, we can add more identifiers to our graphql requests from the UI to further categorize this group of traffic by pages.

This note has been added to: https://wiki.oicr.on.ca/display/icgcargotech/Gateway+traffic+classification

**Comment by rosibaj** [comment]
Discussed with IT team May 21,2020

Current setup will be used by IT.  Additional changes requested will be covered on future tickets.
