### ISSUE TITLE
Create fake `file_repository` index for development

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#403]
- [ ] Data Source https://song.rdpc-qa.cancercollaboratory.org/studies/EUCANCAN-BE/analysis/4bd435c5-62fa-47b7-9435-c562fad7b7bb

- [ ] Mapping to transform doucments too https://github.com/icgc-argo/argo-metadata-schemas/blob/master/mappings/maestro_file_centric.json

# Expected outcome
Transform data into an index of test documents, which are then submitted to Dev/QA Platform Elasticsearch as a `file_centric` index.

**Comment by rosibaj** [comment]
@andricDu before i close, i just want to make sure these made it to the dev clusters?

**Comment by andricDu** [comment]
@rosibaj it did not, doing that today.

**Comment by rosibaj** [comment]
submitted to dev confirmed.
