### ISSUE TITLE
Platform: Upgrade Jenkins chart

### ISSUE THREAD

**Issue by blabadi** [icgc-argo/roadmap#404]
Production Jenkins chart is at 1.9.10
QA chart at 0.36.x 
Latest chart is at 1.17.x 

another thing to keep in sync is the docker tag because it's not accurate and the QA jenkins is using jenkins:lts 
 
Jenkins needs some love

**Comment by akachru-github** [comment]
These are community charts. We should stay up to date.

**Comment by yalturmes** [comment]
Jenkins core, plugins and helm chart are updated on monthly basis. This covers all jenkins kubernetes instances. The ticket no longer relevant.
