### ISSUE TITLE
Remove Beta Data Submission

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#408]
We have completed the Beta test of the ICGC-ARGO Platform.

We got a lot of good feedback, but now we need to return prod to the fresh state it deserves! 
- [x] Clear the clinical data that has been submitted for all projects.
- [x] Clear the ego entries for all added people 
- [x] Clear the Elasticsearch of dashboard indices. 
- [x] Clear the Program Service Entries.

**Comment by hlminh2000** [comment]
Ego, program service, clinical and elasticsearch in prod has been cleared using this script: https://github.com/OICR/argo-infra/tree/master/tasks/dbClearing

**Comment by rosibaj** [comment]
Logged in and everything look cleared to me - access  in ego mainted and see rest of the stuff! 

Thanks @hlminh2000 !
