### ISSUE TITLE
Platform Backups: Backup /restore for MongoDB (Lectern)

### ISSUE THREAD

**Issue by hlminh2000** [icgc-argo/roadmap#409]
- New chart, copying clinical (https://github.com/icgc-argo/kube-infra/tree/master/clinical-mongo-backup)
- modify `backup.sh` to read lectern vault secret

**Comment by rosibaj** [comment]
@rtisma Is this ready to be worked on based on your work in lectern/vault?

**Comment by andricDu** [comment]
This has been deployed to prod.

There are differences between how lectern is deployed in dev/qa and prod/staging.

This should be fixed as it means the chart deployed to prod is not compatible with QA. 

That is described here: https://github.com/icgc-argo/roadmap/issues/424
