### ISSUE TITLE
Fix restart on Platform Services pods when coming back up

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#411]
When the platform is restarted, some pod do not restart correctly:

- [x] Program service 
- [x] Rollcall
- [x] Ego

These services need to have the pod restart when coming back

set spring cloud vault fail fast flag to true as env variable in the values/application yaml

**Comment by jaserud** [comment]
This applies to Rollcall too as it doesn't restart properly when not able to get to vault.

**Comment by rosibaj** [comment]
@jaserud added rollcall to list.

**Comment by andricDu** [comment]
Ego will also need to updated.

**Comment by andricDu** [comment]
@blabadi solved the 403 vault issue that was tripping the fail fast when we didn't intend it to. He verified the modifications in dev and qa for Program Service and Ego.

**Comment by andricDu** [comment]
Ego and Program Service have been updated in staging.

**Comment by andricDu** [comment]
prod vault policies updated for ego and ps

**Comment by andricDu** [comment]
prod updated for ego and ps

**Comment by andricDu** [comment]
Rollcall has been updated in staging and prod. 

I noticed differences in naming convention between environments I have put in the tech debt ticket here: https://github.com/icgc-argo/roadmap/issues/507

Also rollcall did not set its application name through the `SPRING_APPLICATION_NAME` env var which caused issues with vault. This has now been fixed.
