### ISSUE TITLE
Figure out how to host / deliver the maintenance page

### ISSUE THREAD

**Issue by hlminh2000** [icgc-argo/roadmap#422]
Following https://github.com/icgc-argo/platform-ui/issues/1452, we have the static content to host during maintenance. Depending on how our talk with IT goes, we will either deliver this to them, or figure out a way to host this ourselves.

## From call with IT:
They will be hosting the site, while polling endpoints we provide to figure out if the site should be up. For this, we will be delivering the following:

- [x] The static bundle. I've uploaded the bundle we have here: https://drive.google.com/open?id=1K-y53Os_6Dq3chB6-l9bp1hJYgyOcLX5
- [ ] ~An endpoint from the Gateway API to indicate it is healthy. We need to be able to update this endpoint status without completely killing the gateway.~
- [ ] ~An endpoint from the UI server to indicate it is healthy. We need to be able to update this endpoint status without completely killing the gateway.~

## From internal discussin:
- [x] An endpoint from Ego to act as system health check for IT to poll. This can be: https://ego.icgc-argo.org/api/actuator/health
- [x] An environment variable in the UI to show the splash page for every request, for our team to control

**Comment by hlminh2000** [comment]
after a discussion with @andricDu we have decided on the following update to the strategy:
1. We will provide IT with the ego health endpoint https://ego.icgc-argo.org/api/actuator/health to poll. Ego is only expected to be unavailable during a full system outage, and we need traffic to continue to reach ego otherwise to keep workflows running. The IT-hosted splash page will only be triggered when ego is down.
2. For a splash page that we can control, we will host this through our existing UI application, through a flag we can control through the apps' environment variable.

**Comment by rosibaj** [comment]
tested on production with Dusan; the maintenance page responded quickly, with the correct display. 

Thanks @hlminh2000 and @andricDu !!
