### ISSUE TITLE
Lectern differences between environments

### ISSUE THREAD

**Issue by andricDu** [icgc-argo/roadmap#424]
Lectern has differences between prod/staging and qa/dev that make so charts to perform backups are incompatible between the clusters.

### Differences
- Vault Secret Structure
- Dev/QA is not using mongo replica set.  

- update the connection string 
- vault secret structure should mimic the staaging/prod environments.

**Comment by rosibaj** [comment]
@akachru-github we had a lot of discussion about this in planning - can you confirm
- is this still needed?
- is this something the devops team can take on?

**Comment by akachru-github** [comment]
@rosibaj this is still an issue. This is already in the devops queue.

**Comment by akachru-github** [comment]
@blabadi took care of this difference with the Helm 3 upgrade. Closing.
