### ISSUE TITLE
Finalize backup tools

### ISSUE THREAD

**Issue by andricDu** [icgc-argo/roadmap#425]
- [x] Use a helm repo for hosting charts. These can go in the ARGO repo. 
- [x] Have values files in private repos. We can use argo-infra private repo. Do this the same way as we do with other Values
- [x] After helm repo for hosting charts and values are centralized, configure backups to occur nightly except ETCD, which will be every 12 hours. 
- [x] Bundle Vault and JQ into the mongo backup image. 
- [x] Create separate dockerhub repos for each backup
- [x] Audit public charts and scripts to ensure no private information about infra is disclosed
- [x] Update encryption passwords, right now this is the default one left in the values file. 

Other notes:
- If we decide to restore backusp into staging immediately after they are taken, make sure that we do not butt heads with upcoming migrations for new versions of our software into staging. 
- ETCD backups done last. Let's increase frequency here. Every 12 hours.  cc @henro001 
- Decide on encryption key strategy. Broke this out into a new ticket icgc-argo/roadmap#426 to document this strategy.

**Comment by akachru-github** [comment]
- [ ] Use a helm repo for hosting charts. These can go in the ARGO repo. 
- [ ] Have values files in private repos. We can use argo-infra private repo. Do this the same way as we do with other Values
- [ ] After helm repo for hosting charts and values are centralized, configure backups to occur nightly except ETCD, which will be every 12 hours. 
- [ ] Bundle Vault and JQ into the mongo backup image. 
- [ ] Create separate dockerhub repos for each backup
- [ ] Audit public charts and scripts to ensure no private information about infra is disclosed

Other notes:
- If we decide to restore backusp into staging immediately after they are taken, make sure that we do not butt heads with upcoming migrations for new versions of our software into staging. 
- ETCD backups done last. Let's increase frequency here. Every 12 hours.  cc @henro001 
- Decide on encryption key strategy. Broke this out into a new ticket icgc-argo/roadmap#426 to document this strategy.

**Comment by akachru-github** [comment]
Ego failing silently in QA. 
- Generate report on backups?
- Fix the script
