### ISSUE TITLE
Platform Backups: Document encryption key strategy for Backups

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/roadmap#426]
Decide on encryption key strategy
- If we experience a DR scenario, encryption keys will be lost and we will be locked out of our own backups.
- MVP proposal: store on NFS / Isilon. Encryption key stored with multiple users who will be required to store it responsibly. Preferably under their mattress.

**Comment by akachru-github** [comment]
@henro001  to send the keys out to 
- Christina
- Atul
- Dusan
- Jared
- Yelizar

**Comment by henro001** [comment]
The keys have been distributed. 
Docs: https://wiki.oicr.on.ca/display/icgcargotech/Kube+backups
