### ISSUE TITLE
Update Links to the Argo Platform - POST RELEASE

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#435]
mentioned in planning - need list of places to communicate new links

**Comment by rosibaj** [comment]
@kcullion can you help me get this list of links filled out with Christina?  Im not sure off all the places that would need this updates.

**Comment by kcullion** [comment]
@rosibaj here's a start...but I'll ask Christina what an action item would be for this. Like if we need to prepare mocks for guidance on copy etc.

https://www.icgc-argo.org/
https://dcc.icgc.org/
https://icgc.org/
https://www.overture.bio/case-studies
https://softeng.oicr.on.ca/
https://news.oicr.on.ca/
https://oicr.on.ca/investigators/christina-yung/
https://www.ga4gh.org/genomic-data-toolkit/ or https://www.ga4gh.org/news ??
