### ISSUE TITLE
FIX FAILING E2E NIGHTLY TESTS

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#438]
E2E tests have been failing, and are being ignored by multuple people. 

**Last stable build (#159), 3 mo 22 days ago**
**Last successful build (#159), 3 mo 22 days ago**

E2E test *MUST BE PASSING*. 

Issue Analysis:  Something is making the tests hit a 404
![image.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/14ded7d6-67b7-4575-9843-edee8fbe3b9d)

Appears to be failing on this step:
![image.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/f0b03fe6-b1cd-4a3b-81fa-283d2e59757

**Comment by ciaranschutte** [comment]
- invalid program region
  previous: ['North America', 'South America']
  now: ['Canada']

- sample reg upload not loading on refresh
  good test data is invalid, not loading "success" upload which has element `id` defined in test

- `disabled` getAttribute invalid

- modal success string incorrect

- clinical data invalid (Do we have a good way to keep this in sync?)

- join-program: startpath potentially breaking `PACAU-AU` may not exist

- edit-program: https://github.com/icgc-argo/platform-ui/issues/1619

- All data is hardcoded: https://github.com/icgc-argo/e2e-test/issues/34

**Comment by rosibaj** [comment]
@hlminh2000 @ciaranschutte analysis is completed so closing this ticket as we abstracted the next steps for the next sprint.
