### ISSUE TITLE
Platform Backups: Document manual backup and restore process for each service

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/roadmap#440]
- This ticket can be closed when a wiki is drafted that runs through the validated steps for backing up and restoring each service (backups have bene documented, add the restore process to this):
- [x] Ego (Postgres)
- [x] Program Service (Postgres)
- [x] Lectern (Mongo)
- [x] Clinical (Mongo)
- [x] ETCD (specific ticket https://app.zenhub.com/workspaces/argo-mega-board-all-repos-5c8c8637777e5f767e486217/issues/icgc-argo/roadmap/508)
- [x] Jenkins

Moved to separate ticket (https://github.com/icgc-argo/roadmap/issues/562):
- Consul

**Comment by akachru-github** [comment]
Started documenting the Jenkins process.

**Comment by yalturmes** [comment]
Progress update:
Argo Platform Jenkins backup/restore wiki draft has been published on confluence:
https://wiki.oicr.on.ca/display/icgcargotech/ARGO+Platform+-+Jenkins+backups

**Comment by yalturmes** [comment]
Progress update:
Argo Platform EGO and Program services backup wiki draft has been published on confluence:
https://wiki.oicr.on.ca/display/icgcargotech/ARGO+Platform+-+EGO+and+Program+Services+backup

**Comment by yalturmes** [comment]
Progress update:
Argo Platform Clinical and Lectern services backup wiki draft has been published on confluence:
https://wiki.oicr.on.ca/display/icgcargotech/ARGO+Platform+-+Clinical+and+Lectern+backup

**Comment by akachru-github** [comment]
Created https://github.com/icgc-argo/roadmap/issues/562 for the Consul documentation as a separate ticket. Closing this as all other documentation is completed.
