### ISSUE TITLE
RDPC: Make required services public with whitelist

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/roadmap#441]
When we decide to go public with the Platform, Song and Score will also need to be available publicly. 

---

Confirm the list of public ingresses!

score.rdpc.cancercollaboratory.org
song.rdpc.cancercollaboratory.org

- allow limited access to ingress resources (ingress nodes) from OICR ranges

- update DNS for public services to public ingress IP addresses (song,score) - TTL is 5 minutes

- update ingress annotation to switch to public ingress controller (song,score)

kubectl annotate ingress <ingress-name> kubernetes.io/ingress.class=argo-rdpc-public

- remove limited access to ingress resources (ingress nodes) from OICR ranges (open to public)

- notify team that this may interrupt upload/download steps for song in running workflows. 

**Whitelisted IPs**

Junjun: 99.229.72.92
Rosi: 23.233.79.123
Hardeep: 69.165.159.19

**Comment by akachru-github** [comment]
@henro001 , can you flesh this out a bit with a set of steps that need to be taken? This will need to be done on the same day we make the platform changes. Would help to write out the general steps we will need to follow. thanks!

**Comment by akachru-github** [comment]
Added more context to this ticket: We will want to make the services public with a whitelist! Let's fold that into the instructions @henro001

**Comment by akachru-github** [comment]
- Add helm values to github
- Missing default config map

**Comment by yalturmes** [comment]
Security groups created and applied in order to allow temorary access for:
Junjun: 99.229.72.92
Rosi: 23.233.79.123
Hardeep: 69.165.159.19

Security group name:
public_access_temp

EDITED on 17/06/2020:
Added one more entry to the security group above on @akachru-github request:
Hardeep: 24.141.27.243
