### ISSUE TITLE
Update Model T to allow multiple runs/work directory

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#444]
- Sanger is very efficient on hard-drive usage
- need to be able to run multiple runs on a single work directory 
- get the usage output to analzye the cpu/mem metrics to analyze how many jobs we can do 

Update the Model T to be allowed to do this.

**Comment by lepsalex** [comment]
model-tee update complete.

Also, since we often need to get resources available and there isnt the easiest way of doing that I documented the command here: https://wiki.oicr.on.ca/display/icgcargotech/Useful+KubeCtl+Commands
