### ISSUE TITLE
Investigation: Move infrastructure directories from ARGO infra repo to OICR DevOps org

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/roadmap#447]
Move infrastructure directories from ARGO infra repo to OICR DevOps org

**Comment by akachru-github** [comment]
cc. @andricDu

**Comment by akachru-github** [comment]
This move would break a lot of stuff. We need to be ready when doing this. 

Potential steps:
- update all references, queue it up for merge
- make the move
- merge the changes

**Comment by puneet-oicr** [comment]
Priority and strategy TBD by team - Low priority, organically happening already
Ticket not as relevant, since its already happening
