### ISSUE TITLE
Mailhog values update

### ISSUE THREAD

**Issue by henro001** [icgc-argo/roadmap#452]
Values in github are missing nodeselector and host port. Need update

**Comment by rtisma** [comment]
The PR for this was never merged
https://github.com/OICR/argo-infra/pull/228

it contains the network policies and program service values that were deployed locally to argo-dev, but forgot to merge.

**Comment by rosibaj** [comment]
@hlminh2000 @henro001 @andricDu is this still needed/valid ticket?
