### ISSUE TITLE
Set up first legacy programs in Prod

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#453]
- [x] Complete the legacy migration for programs ` PACA-CA` and `OCCAMS-GB (formerly ESAD-UK` into production
https://wiki.oicr.on.ca/display/icgcargotech/Activating+Legacy+ICGC+Programs+in+ARGO

- [x] Initialize the clincal samples for these programs:  https://wiki.oicr.on.ca/pages/viewpage.action?spaceKey=icgcargotech&title=Initializing+the+ICGC+dataset+in+ARGO#InitializingtheICGCdatasetinARGO-DataImportInstructions

**Comment by andricDu** [comment]
fin
