### ISSUE TITLE
Switch Song Prod to point to Song clinical

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#459]
We have completed the import of the clinical data for PACA-CA and OCCAMS-GB to `prod clinical`
We want to test that when we switch over form the QA song, everything works as expected. 

- [x] To ensure consistency, we need to take song offline, check all its donor ids, sampleids and specimen ids exist in clinical prod, and if that check passes, we can point song to clinical prod and turn on song
- [x] Once the id set is verified, update the configuration to point ot prod song
- [x] Make sure workflows run successfully

**Comment by rosibaj** [comment]
waiting on confirmation once a wf initiates download or upload 🤞 

@lepsalex ^ can you please let me know if anything happens?

**Comment by lepsalex** [comment]
jobs appear to be running normally, Model-Tee scheduled 6 new jobs overnight with no problems.

**Comment by rosibaj** [comment]
thanks for confirming!

**Comment by rtisma** [comment]
@lepsalex @junjun-zhang I have forgotten about song's caching abilities. This means, running successful workflows does not necessarily mean the sampleId, specimenId or donorId was fetched from clinical, becuase if it already existed in song's cache, there would be no need to make a call to clinical.

Can either one of you include atleast 1 new, never before registered  sample in the workflow? This will ensure that song makes a call to clinical, and will verify the work for this ticket is complete.

I would do it my self, but that would mean i have to create a new study, register fake/dummy donors and therefore create a fake/dummy program....not something that should be done in prod. Which means i have no nice way to test, other than a unique workflow

**Comment by junjun-zhang** [comment]
@rtisma we are running Sanger WGS variant calling workflow, all of the candidate jobs are from donors/specimens/samples previously processed in BWA alignment workflow, so there is no new sample could be used to trigger a real call from clinical.

**Comment by rtisma** [comment]
Actually, I can do a negative test: i will attempt to submit a payload for a non-existent sampleId. If the connection to clinical is good, i should get back a 404 indicating song.prod is communicating with clinica.prod. If there is an issue with the connection, i will get back 502 bad gateway, indicating song.prod cannot reach clinical.prod

**Comment by rtisma** [comment]
Confirmed that 404s are returned for the negative test for both intermediate-song.prod and song.prod
```
{
  "errorId": "id.not.found",
  "httpStatusCode": 404,
  "httpStatusName": "NOT_FOUND",
  "requestUrl": "http://intermediate-song.rdpc.cancercollaboratory.org/submit/PACA-CA",
  "datetime": "2020-06-04T18:05:23.075Z[GMT]",
  "timestamp": 1591293923075,
  "message": "[DonorService::id.not.found] - The donorId for studyId 'PACA-CA' and donorSubmitterId 'DEMO_DO_1' was not found",
  "debugMessage": "N/A",
```
 and
```
{
  "errorId": "id.not.found",
  "httpStatusCode": 404,
  "httpStatusName": "NOT_FOUND",
  "requestUrl": "http://song.rdpc.cancercollaboratory.org/submit/PACA-CA",
  "datetime": "2020-06-04T18:07:04.364Z[GMT]",
  "timestamp": 1591294024364,
  "message": "[DonorService::id.not.found] - The donorId for studyId 'PACA-CA' and donorSubmitterId 'DEMO_DO_1' was not found",
  "debugMessage": "N/A",
```
Also kubectl exec'd into both pods and ensured the both songs are configured to use clincal.prod

This ticket is therefore, done

**Comment by rosibaj** [comment]
@rtisma thank you for the extra confirmation!!!!
