### ISSUE TITLE
Initialize LUCA-KR in production

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#460]
- [x] Ego, PS, and Clinical should be backuped up first (in case of fat-fingering)

- [x]  Complete the legacy migration for programs `LUCA-KR`  (Note, this program `is` changing their legacy name from `LUSC-KR`)

- [x]  Complete the legacy migration for program `THCA-SA` .  this project `IS` changing its project code to `PTC-SA`  

https://wiki.oicr.on.ca/display/icgcargotech/Activating+Legacy+ICGC+Programs+in+ARGO

- [ ] Initialize the clinical samples for these programs: https://wiki.oicr.on.ca/pages/viewpage.action?spaceKey=icgcargotech&title=Initializing+the+ICGC+dataset+in+ARGO#InitializingtheICGCdatasetinARGO-DataImportInstructions

**Comment by blabadi** [comment]
backup taken

**Comment by blabadi** [comment]
programs activated in all environments 
clinical data for PTC-SA imported in all environments  (PTC not indexed in staging)
clinical data for LUCA-KR not done in prod yet, pending QA

**Comment by rosibaj** [comment]
@blabadi Luca-KR looks good to go to prod!

**Comment by andricDu** [comment]
@rtisma will follow SOP and follow this through and re-verify with @blabadi on Monday.

**Comment by rtisma** [comment]
@blabadi I have imported LUSC-KR as LUCA-KR using the instructions from the SOP.

**Comment by rosibaj** [comment]
@rtisma did you complete the import of clinical donors for LUCA-KR? I see 0 registered donors:
![image](https://user-images.githubusercontent.com/15824252/86599582-d0e0fb80-bf6c-11ea-8446-f004e2172c1a.png)

**Comment by rosibaj** [comment]
re-verified on production; dashboards now show the correct numbers for these projects.
