### ISSUE TITLE
Create user accounts in COVID Ego

### ISSUE THREAD

**Issue by christinayung** [icgc-argo/roadmap#463]
- [ ] Create accounts using PHO emails (Christina will send the list to Rob).  They will belong to a group PHO

- [ ] Generate tokens that allow upload and download for each user

- [ ] For each user, put the token in whisper.oicr.on.ca with 4 weeks as expiration, and email each individual the URL.  **Michelle Xin can do this**. Email message: Please retrieve your API token at <URL>.  The link will expire in 4 weeks.  The token will enable you to upload/download data (instructions to follow), and should never be shared with anyone.
- [ ]  In Song, create a study named "COVID-Testing" and grant the PHO group access.
- [ ] 6 month expiry on api tokens

**Comment by rtisma** [comment]
In COVID ego
- create group PHO
- create policy `PROGRAMDATA-COVID-Testing`
- create group permession with policy `PROGRAMDATA-COVID-Testing` and with `WRITE` mask
- for each email
    - create user (of type `USER`)  and add them to the PHO group
    - generate access token with scope `PROGRAMDATA-COVID-Testing.WRITE`
    - create whisper link with token
    - send email
