### ISSUE TITLE
Define Production Maestro Indexing Rules 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#468]
We want to only Include the current Alignment and VCF files. For example, these are the only files we want to release currently: 
https://platform-ui.qa.argo.cancercollaboratory.org/repository?filters=%7B%22content%22%3A%5B%7B%22content%22%3A%7B%22field%22%3A%22file_type%22%2C%22value%22%3A%5B%22CRAM%22%2C%22VCF%22%5D%7D%2C%22op%22%3A%22in%22%7D%5D%2C%22op%22%3A%22and%22%7D

- Index the whole Song production database
- delete all files from any analysis type EXCEPT `sequencing_alignment` and `variant_calling` from the `file_centric` index in elasticsearch

This operation may need to be done 1-2 more times before we complete the maestro changes; Tentatively we will want to update the next batch of VCF files, which means we have to wait for alignment and variant calling workflows to finish on ~ 200 samples.

**Comment by blabadi** [comment]
Index the whole Song production database was done yesterday

**Comment by rosibaj** [comment]
After reviewing the production numbers, we have 4 donors in question: 

- DO50387 - appears that there was a sanger run duplication
- DO51492 - appears that there was a sanger run duplication
- DO35148 - normal was failed and did NOT get the aligned cram at all. so NO sanger results generated. doc_count=1
- DO50319 - only the tumour sample (no normal) was aligned. 

Can we additionally remove the document associated to these  from the index for release tomorrow?  it should total `22` documents for removal.
