### ISSUE TITLE
Normalizing run_id , run_name, and session_id

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#469]
Currently, services contain one or both of run_id or run_name, and sometimes warp the concepts. 

After discussion and investigation of the Nextflow system, it was decided:

- `run_name` is the most unique element, and has an actual status (complete/not complete) associated with it 
- `session_id` from Nextflow is the id of the workflow session that can group multiple jobs. 
- `run_id` = `session_id` in nextflow. 

Nextflow has a bug in which upon resume, if `run_name` is provided, it will default the `run_id` to the last `session_id`.  This is very misleading, as it then assigns NON-UNIQUE identifiers to runs. 

Thus, to work around this issue, we will: 
-  [x] Step 1:  Update workflow-relay to:
- transform `runName` from Nextflow into `runId` in our recorded ES index.  Also, `sessionId` will be added as a new concept. 
- Redeploy this version of relay
- Reindex the history of Kakfta to reinstate the indices with the new shape updates, including `runId` and `sessionId`.

-  [x] Step 2:  Update workflow UI to connect to the workflow-search graphQL with correctly resolved fields (per step 1)
https://github.com/icgc-argo/workflow-ui/issues/32
-  [x] Step 3: Add `session_id` in song schemas
https://github.com/icgc-argo/argo-metadata-schemas/issues/36
-  [x] Step 4:  Update the workflow `song payload generation` step to include `session_id`
https://github.com/icgc-argo/data-processing-utility-tools/issues/72

-  [x] Step 6: Update maestro analysis_centric mappings to include `session_id`
-  [x] Step 8: Re index song_prod in rdpc environment. 

Note:  All sange jobs will be finished Monday the 15th.  Good time to do maintenance

**Comment by junjun-zhang** [comment]
This is certainly a good call. There are two different concepts here: one represents a peice of work to be done (from the business side), the other represents the action(s) actually carrying out the work (from the operations side). We could call the former a `job`, the latter a `run`. This way it would be more clear.

A `job` may have a stable, user-friendly idenfier. For example, `{studyId}.{donorId}.{sampleId}.{experiemental_strategy}.{analysis}`, concretely `TEST-PR.DO250122.SA610149.wgs.aln` could be used to represent a WGS alignment job. Similarly, a naming pattern can be used for variant calling jobs.

A `job` may have one or more runs that try to get the job done. UUID would be a good fit to use as idenfier for a `run`.

Actual terms can be different than `job` / `run`, the key is that there are two different concepts.

**Comment by rosibaj** [comment]
From Slack: 
well ... according to the tracing section of the Nextflow docs runId is "The workflow execution unique ID" (https://www.nextflow.io/docs/latest/tracing.html?highlight=runid). Under the workflow introspection section they mention that sessionId is the "Unique identifier (UUID) associated to current execution." (https://www.nextflow.io/docs/latest/metadata.html?highlight=sessionid) (edited) 


if runId was easily accessible inside the workflows which one would assume it would be I would say include both. Given that this isn't the case, the only universally available ID we have remains runName. I think we just need to rename this field in the schema and all affected services from runId to runName and call it a day for now

**Comment by lepsalex** [comment]
@junjun-zhang I think session and job are very close concept however a job is something that you submit and that would have it's own state/status (scheduled, started, finished, etc) whereas a session represents a collection of activities, in our case it's a collection of runs, where the session itself has no state but is rather just a UUID linking runs together (one original and n number of resumed runs)

**Comment by junjun-zhang** [comment]
I don't have strong preferences in terms of what exact terms to use, it's clear to all of us indeed there are two concepts and have one to many relationship.

Since WES already picked up `run_id` which symantically represents the ID for one of the above mentioned two concepts, just wonder whether it's worth an attempt to still stay inline with WES. Also, although NF is currently the underlying workflow engine, if we intend to make our workflow orchestration system able to incorporate with other engines (not to say doing it anytime soon), it may not need to mirror NF terms that closely.

**Comment by rosibaj** [comment]
- we are staying in line with wes and staying with `run_id` not `run_name` (so this is consistent)
- for now, the easiest solution is to stay with session_id and not transform that as we don't have additional requirements from other systems.

**Comment by junjun-zhang** [comment]
just a minor note, the parent concept can have states, like `started`, `completed`, it can be reviewed as an agregated state of the children's states. Particular from bussiness point of view, operational state maybe not as important.

**Comment by junjun-zhang** [comment]
> * we are staying in line with wes and staying with `run_id` not `run_name` (so this is consistent)

That's  good, didn't realize the specs updated.

> * for now, the easiest solution is to stay with session_id and not transform that as we don't have additional requirements from other systems.

Sounds good. As it's very simple, will be easy to change in the future if needed.
