### ISSUE TITLE
Variant class not being indexed

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#471]
1. https://github.com/icgc-argo/argo-metadata-schemas/blob/master/mappings/maestro_file_centric.json <-- i see variant class in mapping 
2. i see the variant class in the payload
curl --location --request GET 'https://song.rdpc.cancercollaboratory.org/studies/OCCAMS-GB/analysis/e7e4ab0a-ee0c-42a4-a4ab-0aee0c92a4c2' \
3. I dont see variant_clas in the portal, or the api
![image.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/0c3a128d-0461-46ae-bea7-e193ef26cea2)
4. i assume its not in maestro and something is stopping the indexing?

**Comment by blabadi** [comment]
the problem is that the variant class is not nested under analysis object in the mapping

https://github.com/icgc-argo/argo-metadata-schemas/blob/master/mappings/maestro_file_centric.json#L228-L230

i checked the source document in elastic it's there under `analysis.variant_class`

**Comment by blabadi** [comment]
PR to fix this: https://github.com/icgc-argo/argo-metadata-schemas/pull/38

**Comment by blabadi** [comment]
I updated the mapping in DEV & QA but arranger and the gateway require an update to see the changes

**Comment by hlminh2000** [comment]
I'll update the gateway for this :)

**Comment by hlminh2000** [comment]
Gateway updated in this PR: https://github.com/icgc-argo/platform-api/pull/261

**Comment by rosibaj** [comment]
@hlminh2000 looks good in qa!
