### ISSUE TITLE
End-to-End Test Architecture 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#478]
Assess the architecture of the end-to-end tests and come up with a plan of implementation 

## Expected Outcome 

- develop a list of specific changes/standardization in test
- list of standard libraries the tests can use 
- documentation on how to add a new test for a new feature 

**Final task: Schedule a meeting with Rosi  to:**
- write follow-up tickets for test implementation 
- talk about the PROCESS of creating/running/fixing tests

**Comment by hlminh2000** [comment]
@ciaranschutte @rosibaj @anncatton I'd like to get some inputs from you guys about this so would be great if we can schedule a meeting to discuss in details :) Maybe we can wait for Dusan's return so he is in the loop.

Here's some ideas I've jot down after playing around with the test and thinking about our test strategy.

The findings and proposals can be found here: https://docs.google.com/document/d/1GYagt0XN6CZkRqbgSe6nbBLYrFcMYw3b6BlatqjrKAg/edit?usp=sharing
