### ISSUE TITLE
Separate ARGO QA Environment 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#48]
Migrate all of the argo services to argo environments
- [x]  EGO
- [x]  Program service 
- [x] Gateway 
- [x] Platform

**Comment by blabadi** [comment]
steps done so far: 

argo env setup:
- install helm charts 
-- first installation require secrets (ego client ids for google, facebook etc), ones after will reuse values and merge with -f values
- sign user in ego (will get no access) 
- login to db and change user to admin
- register the program service, platform ui as applications

**Comment by blabadi** [comment]
the config values are stored here: https://github.com/OICR/argo-infra

**Comment by blabadi** [comment]
next step is to update each of the argo components to trigger deploy on the new envs in their CI pipeline
