### ISSUE TITLE
RDPC: Make Song / Score Public 

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/roadmap#480]
Currently, song/score are on the public ingress behind an allow list. This ticket represents the work to remove the allow list to make the services publicly available.

**Comment by yalturmes** [comment]
Song/score services are now public.
**Details:**
A new security group `public_access_https` has been created in Openstack project `ARGO_RDPC_Yung` to allow inbound HTTPS connectivity from everywhere (0.0.0.0/0). The security group has been associated with kubernetes ingress nodes:
k8s-ingress-rdpc-0
k8s-ingress-rdpc-1
k8s-ingress-rdpc-2

**Note:**
A number of security groups have been created previously to allow access to Song/Score services for individual team members. With introduction of the changes above these security groups became redundant and no longer needed. Flagging this for later audit and clean-up.
