### ISSUE TITLE
ARGO Platform: Shutdown and restart test

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/roadmap#481]
IT has a maintenance window from July 17-19. During this window, they will require us to shut down ARGO Platform services. We will be responsible for taking all of the services down gracefully (including Ego) and restarting those services once the maintenance period is over. 

This ticket is meant to capture the work required for us to test a similar shut down. This ticket will also include documentation for the resulting steps to shutdown and restart. 

Suggestions: 
- We cannot use the Staging environment as this is in the same cluster as Production. We can instead use the DEV / QA environments to perform the test. 
- Order of operations will be important when shutting down and restarting.

# Steps for shutdown (WIP)
1. Scale down all externally exposed APIs: platform UI, gateway, ego, clinical
2. Scale down internal microservices: program service, vault, others...
3. Scale down stateful sets: elasticsearch, DB's, Kafka

**Comment by andricDu** [comment]
@akachru-github I believe this can be closed.

**Comment by henro001** [comment]
when the cluster came back up, we experience issues with Jenkins, where a restore was required.
https://wiki.oicr.on.ca/display/icgcargotech/Jenkins+restore

**Comment by akachru-github** [comment]
https://github.com/OICR/argo-infra/blob/master/argo-k8s/argo/argo-prod/script/scale-platorm-prod.sh
