### ISSUE TITLE
RDPC/Platform: Upgrade Jenkins helm charts

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/roadmap#483]
Upgrade Jenkins helm charts for following envs:
Argo Platform Jenkins
RDPC Dev Jenkins
RDPC Prod Jenkins

Maintaining helm charts for Jenkins up to date with upstream version is required for following reasons:
- to keep Jenkins installations supportable through helm
- to resolve compatibility breaking changes introduced in version 2 of the chart
- to enable better support for JCasC support

**Comment by akachru-github** [comment]
@henro001 and @yalturmes , had to delete the original issue because it was created in the wrong org. Created a new version of the ticket here in the ARGO org.

**Comment by yalturmes** [comment]
Not relevant anymore. Jenkins instances upgrades are performed on regular basis following Jenkins LTS release cycle.
Closing ticket.
