### ISSUE TITLE
Design: Ego Application to Application Token

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/roadmap#485]
This ticket is meant to capture a proposed design for Ego application to application tokens. Currently application tokens exist, but scopes needs to be added. Song and Score would need to change to support this as well. 

output: tech spec / roadmap fo what needs to be changed to support this. 

reference wiki: https://wiki.oicr.on.ca/pages/viewpage.action?spaceKey=DCCSOFT&title=Application+Level+Authorization

**Comment by andricDu** [comment]
Outlined specs here: https://wiki.oicr.on.ca/display/icgcargotech/Ego+Application+JWT+Integration
