### ISSUE TITLE
Design: RDPC-gateway-api integration with platform-gateway-api

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/roadmap#486]
https://wiki.oicr.on.ca/display/icgcargotech/RDPC+Gateway+Design

This ticket captures effort to reach a design of integrating the RDPC-gateway-api with the platform-gateway-api using the Apollo federation approach. 

Currently, RDPC-gateway is integrated with workflow-search and song-search. This final integration will provide the ability to include clinical data to complete the workflow query picture. 

Changes in the platform-api may be required to support this, Jon / Minh will be consulted.

**Comment by akachru-github** [comment]
After discussion in CM sprint planning, it was decided that this should be driven from the Platform side, as a request from the RDPC. Moving into the next platform sprint.

**Comment by andricDu** [comment]
Exit criteria: Technical Specs with plan

**Comment by andricDu** [comment]
Concluded discussions with @hlminh2000 @blabadi and @rosibaj 

Appropriate solution will be to provide a proxy service for the platform api gateway. This proxy service will be providing the Apollo federation compliant graphql and be deployed inside the RDPC and allowing queries against a subset of the platform API.

We will not be making changes to the platform API to support this.

Goals were to minimize disruption of platform while not introducing RDPC specific concerns to platform API allowing us to join and enrich data on platform entites that comply to the use cases of the RDPC.

Next steps are a short spec which will be linked to the ticket here.

**Comment by andricDu** [comment]
Added to the rdpc gateway document with a section about our way forward for this. 
 https://wiki.oicr.on.ca/display/icgcargotech/RDPC+Gateway+Design
