### ISSUE TITLE
Design: Support "emptyDir" in Nextflow

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/roadmap#490]
https://wiki.oicr.on.ca/pages/viewpage.action?spaceKey=icgcargotech&title=Local+Disk+Usage

From the wiki to improve network utilization using local disk: 
- It turns out that while we have modified our workflows to be able to specify a temp directory, Nextflow support persistent volumes or ramdisk when running in Kubernetes. What we need is the emptyDir option but that is not currently possible. There is an open PR (https://github.com/nextflow-io/nextflow/pull/1389) to add this functionality, however given that it was opened in November of 2019 the chances of it becoming a priority now for the Nextflow authors is quite low.

We have a couple options to evaluate here, could even do them in order as they escalate in effort:

1. Attempt to revive the existing PR by commenting on our specific use case and see what the NF authors respond with
2. Attempt to do something in workflow-management that could modify the process pods to always mount a local directory
3. Continue where the PR left off, make it work for us, offer it back to Nextflow but of not operate it on our own either as a fork or patch

Output of this ticket is a spec'd approach to how to support this.

**Comment by rtisma** [comment]
Refer to **Update 2020/07/17 **
https://wiki.oicr.on.ca/display/icgcargotech/Local+Disk+Usage
