### ISSUE TITLE
COVID: Model-Tee - Update Kafka event listener placeholder

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/roadmap#492]
Model-Tee Covid: Update the Kafka event listener placeholder to use the real Kafka events payload as provided by @andricDu via https://app.zenhub.com/workspaces/argo-mega-board-all-repos-5c8c8637777e5f767e486217/issues/icgc-argo/workflow-roadmap/21.

**Comment by rosibaj** [comment]
Closing as no longer valid.
