### ISSUE TITLE
Jenkins - Platform/RDPC - Mysterious "Jenkins has been upgraded" msg after restart

### ISSUE THREAD

**Issue by henro001** [icgc-argo/roadmap#495]
- Investigate why we are getting this message. Check image tag to prevent automatic upgrades
- check volume size - currently 8GB
-- we had increased platform to 32GB
- [x] argo dev - upgraded 2.235.1 > 2.235.3
- [x] argo prod
- [x] rdpc dev
- [x] rdpc prod

**Comment by akachru-github** [comment]
- Jenkins starts: war file gets extracted to the home directory. The file always seems to be extracted when the container starts. We need to specify the version in the helm chart to stop this automatic upgrade. LTS tag is causing this.

**Comment by yalturmes** [comment]
Helm values updated for all Jenkins instances:
master: tag: lts => master: tag: 2.235.3.
TODO:
- [x] Clean up backup snapshots taken prior to applying changes.

**Comment by yalturmes** [comment]
Backup snapshots taken prior to introducing the tag change have been cleaned-up.
