### ISSUE TITLE
Audit Donor, Specimen and Sample expected immutable data

### ISSUE THREAD

**Issue by rtisma** [icgc-argo/roadmap#496]
Due to the bug described in https://github.com/overture-stack/SONG/issues/646, all the fields affected by that bug must be audited to identify which fields (if any) do not have matching metadata with clinical. This may also apply to the info fields, for which bioinfo may have.

This also needs to be done for ICGC-DCC with the help of bioinfo

**Comment by rosibaj** [comment]
@junjun-zhang @hknahal lets discuss - this is something that we might need to check!
