### ISSUE TITLE
E2E Testing: Script to initialize boilerplate test code

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#498]
Inspired by the create-component script in platform-ui that is used for creating uikit components. This lowers the friction in writing boiler-plate code that is necessary for standardization. Making writing tests easy is important so we don't hate doing it.
- [ ] make an interactive npm script to create a new test boiler plate
include these parameters:
- Test suite name
- Test suite expert name (see process improvement below)
- plop is a good tool we've used

**Comment by ciaranschutte** [comment]
@rosibaj closing this. nothing to test.
