### ISSUE TITLE
CI/CD Setup

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#5]
Set up CI/CD.  Jenkins server is already set up

- [x] Auto deploy ego to QA environment
- [x] Auto deploy program-service to QA-environment

**Comment by d8660091** [comment]
@rosibaj Sorry, it's still in progress

**Comment by rosibaj** [comment]
@d8660091 Apologies!!!!! It was in the review column, so I assumed it was ready for code review as that is what that column reprents :)
