### ISSUE TITLE
Vault Setup

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#50]
- [ ] Set up Vault to configure ARGO secrets

**Comment by blabadi** [comment]
https://github.com/OICR/argo-infra/pull/2

**Comment by blabadi** [comment]
I've installed vault in argo qa
created an argo chart for vault
documented the steps to setup vault for new envs

However due the problem that vault gets sealed whenever it's restarted, as agreed with @andricDu, For production we think setting up vault better be done outside of Kubernetes and instead directly in VMs and we should consider high availability setup

**Comment by blabadi** [comment]
Note that each service has to register itself and its secrets into the vault engine and define its policy based on its Kubernetes service name to isolate services secrets, and that is not part of this ticket.

I have updated ego to show that as an example
