### ISSUE TITLE
Set up initial typescript build system for E2E

### ISSUE THREAD

**Issue by andricDu** [icgc-argo/roadmap#501]
Do the boilerplate, foundational stuff to setup typescript in the E2E test suites.

**Comment by ciaranschutte** [comment]
@rosibaj nothing to manually test here

**Comment by rosibaj** [comment]
@ciaranschutte is there anything to deploy to prod here at all?  if not we can close now!

**Comment by ciaranschutte** [comment]
@rosibaj nothing to deploy, dockerfile remains unchanged too
