### ISSUE TITLE
Platform disaster recovery procedure: Cluster Restore

### ISSUE THREAD

**Issue by henro001** [icgc-argo/roadmap#508]
Research and document the process to restore the cluster in DR 

Related to https://app.zenhub.com/workspaces/argo-mega-board-all-repos-5c8c8637777e5f767e486217/issues/icgc-argo/roadmap/378

--

https://wiki.oicr.on.ca/display/icgcargotech/Kubernetes+cluster+recovery

**Comment by akachru-github** [comment]
This process will be reusable for the RDPC.
