### ISSUE TITLE
Deploy Spring Boot Admin to QA

### ISSUE THREAD

**Issue by rtisma** [icgc-argo/roadmap#51]
Requirments:
- should be secure (tls and basic auth, sign up on request as with jenkins qa)
- should not be exposed publically
- should be central place to view all running services and their version

Issues:
- should not expose secrets. need to find away to hide this without hiding all properties or environment variables

**Comment by blabadi** [comment]
Just a note since we are migrating to argo-qa, this should be deployed there not to the 'qa' env since it's deprecated
