### ISSUE TITLE
Workflow Run Failure - 600GB bam upload

### ISSUE THREAD

**Issue by rtisma** [icgc-argo/roadmap#510]
https://wes.rdpc.cancercollaboratory.org/api/v1/runs/wes-a4d4a719c6524b63a5dcb32294dd0e18

As per linda's issue with a 600gb bam, the upload is missing parts
`ERROR: Data transfer has been interrupted. Some parts are missing. Waiting`

This is the error message I copied from the .command.err under work_dir:
```
Finalizing...
ERROR: Data transfer has been interrupted. Some parts are missing. Waiting to retry...
Total execution time:         3.240 h
Total bytes read    :               0
Total bytes written : 595,583,724,921
^M                                                                           
MERROR: Command error: java.io.IOException: Storage server error: {"timestamp":"2020-07-11T22:45:14.239+0000","status":503,"error":"Service Unavailable",
"message":"com.amazonaws.services.s3.model.AmazonS3Exception: null (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: tx0000000000000004cde3c-005f0a40fa-10f44bc6-default; S3 Extended Request ID: 10f44bc6-default-default), S3 Extended Request ID: 10f44bc6-default-default","path":"/upload/4528e1fb-f93e-5749-a79c-c5479afa3cf5"
```

**Comment by rosibaj** [comment]
- can't be recreated on a VM, only in WF environment 
- non-trivial 
-

**Comment by rosibaj** [comment]
@lindaxiang i belive that this issue was fixed; Can you confirm?

**Comment by lindaxiang** [comment]
@rosibaj yes. I can confirm. The ~600GB bam file is already uploaded into the prod with analysis:
https://song.rdpc.cancercollaboratory.org/studies/PACA-CA/analysis/84c8e815-04f2-4a98-88e8-1504f29a9835
