### ISSUE TITLE
Data Modeling: ERD of workflow automation graph

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#521]
ERD: Nodes, Edges, Graphs [collection of nodes and edges) 

- Design and ERD Diagram showing the communication of the Nodes/Edges
- language codification of concepts in diagrams

**Comment by andricDu** [comment]
I have recorded in UL and ERD stuff here: https://wiki.oicr.on.ca/display/icgcargotech/Model

Currently incomplete but need further review sessions with @lepsalex to identify concerns around message schemas.
