### ISSUE TITLE
Deploy lectern v 1.7.0

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/roadmap#528]
Please deploy lectern version 1.7.0 for ticket https://github.com/icgc-argo/argo-clinical/issues/494

**Comment by rosibaj** [comment]
@blabadi since this is an overture product, im not sure if we can `tag` a version here.  

How does the update happen? should there be a PR to some argo repository that should be done to do this upgrade?

**Comment by blabadi** [comment]
@rosibaj what do you mean by we can't tag a version here? this ticket is just to have something to move through the board for non argo stuff.

yeah for the PR it can be done to the argo-infra by updating the helm values, what we did before is creating a  branch with the release name in argo-infra to PR all values changes to stage and prod, and then the release manager reviews and merges the PR when they do the release

**Comment by rosibaj** [comment]
@blabadi sorry i was confusing!  I meant `github label with the argo version to be deployed` not tag! 

so as a process, here i should look for an `argo-infra` PR to be commented to the ticket to be prepared for release then?

**Comment by blabadi** [comment]
we can label it with 1.7.0 if that what you mean, but you still need to check the ticket to know which service it is 1.7.0 refers to because this is in roadmap, the labeling works better for argo stuff, this is explicitly a deploy ticket and mentions the version in the title

**Comment by blabadi** [comment]
and yeah ideally at the beginning of the sprint we know the release name and someone should create a branch in argo-infra 
for the next release for everyone to PR their stuff to
if we miss that then the first person to notice and need it can do it

**Comment by rosibaj** [comment]
https://github.com/OICR/argo-infra/tree/release/furies  

for release of this version
