### ISSUE TITLE
Tech Spike: Investigate Access Resolution 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#532]
1.  Design the scopes for access to decide PUBLIC versus PRIVATE access 
2. Private is broken into 
--- program permission s
--- full and associate permissions 

3. Architect the changes need in 
--- program service ?
--- ego ?
--- gateway? 

2.  Flowchart of access checks in platform and score (to make sure they align). 

## Expected outcome 
- Architectural plan on wiki 
- Set of next step tickets created

**Comment by hlminh2000** [comment]
Technical spec and implementation plan has been posted in wiki here: https://wiki.oicr.on.ca/display/icgcargotech/File+Metadata+Access+Control

Implementation tickets:
- program service: https://github.com/icgc-argo/program-service/issues/337
- ego token util: https://github.com/icgc-argo/ego-token-utils/issues/46
- gateway: https://github.com/icgc-argo/platform-api/issues/294, blocked by:
  - Arranger: https://github.com/overture-stack/arranger/issues/601
  - ego token util: https://github.com/icgc-argo/ego-token-utils/issues/46

Some tests were written to stress test the idea for the gateway here: https://github.com/icgc-argo/file-metadata-acl-stress-test

**Comment by rosibaj** [comment]
@rtisma Lets connect on this topic here - we've devised a way to limit visualization of metadata from the platform, but we need to make sure that this is respected by download form score as well.  

basically score needs to check many scopres [daco, program.read/write, program_membership.read/write]

**Comment by rtisma** [comment]
@rosibaj  sure. There is already a similar ticket for this:
https://github.com/overture-stack/score/issues/245
