### ISSUE TITLE
Redeploy Kubernetes  etcd/master nodes on SSD

### ISSUE THREAD

**Issue by henro001** [icgc-argo/roadmap#539]
Right now, ETCD/Master is running spinning disk and does not meet the hardware requirements for low latency storage. We will need to move these to SSD. We had experienced fallout from this:
1) high latency caused the RDPC Prod .... <<@henro to fill out>>
2) ARGO Platform QA we are getting constant latency alerts 

Low complexity but High risk
- Each environment seems to be a new experience. This can be done without effecting prod in theory. We should plan for a maintenance window for this deployment. 

Kube master nodes run etcd component and need to be redeployed on SSD flavors

- [x] Argo platform dev/qa
- [x] RDPC dev/qa
- [x] RDPC prod

---
The following is the most impacting scenario when it actually affects running job.
Workflow management app makes Kubernetes API calls to work with nextflow child pods. If the etcd is slow in response the Kube API pod will be fine with that, but the workflow management app wouldn't tolerate the API call failure and the running job will fail instead of retrying. This has been observed on a few occasions.

--

Documented here: https://wiki.oicr.on.ca/display/icgcargotech/Replace+Kubernetes+nodes
Maintenance plane: https://wiki.oicr.on.ca/display/icgcargotech/20201001-Redeploy+kubernetes+master+nodes+on+ssd+instances

Infrastructure: https://wiki.oicr.on.ca/display/Collabor/k8s+master+etcd+requirements

**Comment by akachru-github** [comment]
We will be at capacity of SSDs. We want SSDs for workflows but also for ETCD nodes. We would not want the workflows and ETCD to share an SSD. Ideally we would have dedicated SSDs for ETCD. 

currently worker nodes for the workflows do not use local storage which will be SSD and will cause contention with the ETCD. We do not have the spare capacity to dedicate nodes for ETCD instances. 

This will become a problem when EmptyDir is implemented as that will enable workflows to use local SSD storage. 

Ideally: More SSDs. 

nexts steps: 
- what is our capacity right now?

FYI @andricDu , @rtisma , @lepsalex

**Comment by akachru-github** [comment]
Questions: 
- Are SSD's a requirement for running workflows? Rob / Alex
- How are we benchmarking workflows, against spinning or SSDs? Ask Junjun

**Comment by akachru-github** [comment]
From @jmimico :
We only have 12 compute nodes equipped with SSD’s. We have about 88 cores available in any c3 flavour type. It is by nature of cloud computing that multiple instances are run on a compute node, thus sharing resources (including the underlying SSD’s), so unless we scale back RDPC worker nodes to free up 3 whole c3 nodes or buy more hardware we will likely always be sharing. 

@lepsalex and @rtisma , any thoughts on the potential conflicts above? Workflows running on SSDs is not an explicit requirement correct?

**Comment by lepsalex** [comment]
given that we do not directly use the HDs currently that is fine, if we can mark the nodes with something in kube that remain in the RDPC non-infra pool then when we do the emptyDir stuff we can "prefer" those nodes for alignment runs

**Comment by akachru-github** [comment]
Maintenance window for 1 day required for deploying this.
