### ISSUE TITLE
Deploy Latest RDPC versions to Production 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#553]
List of Services to deploy: 
- [x] Workflows with new song/score update
- [x] Re-index relay
- [x] deploy relay 2.0.1 --> 2.3.0
- [x] deploy  workflow management  2.2.1 -->  2.8.0
- [x] deploy  rdpc-gateway 1.1.0 --> 1.2.0
- [x] Update Network policies in PROD to mirror QA

Deploying:
Feature Request: Creating K8s secrets for workflows
https://github.com/icgc-argo/workflow-roadmap/issues/34
https://github.com/icgc-argo/workflow-roadmap/issues/35
https://github.com/icgc-argo/workflow-management/issues/105
https://github.com/icgc-argo/workflow-management/issues/66
https://github.com/icgc-argo/workflow-search/issues/94

Tasks After deploy: 
- [x] Cancel the failed jobs that are stuck in "running"

**Comment by rosibaj** [comment]
use new devops jenkins deploy magic stuff

**Comment by lepsalex** [comment]
RDPC upgrade complete

**Comment by rosibaj** [comment]
@lepsalex i think you meant `fixed` :p
