### ISSUE TITLE
Cannot deploy Program Service DEV/QA

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/roadmap#555]

**Comment by yalturmes** [comment]
The issue resolved.
Details:
Problem: 
Jenkins slave pods were missing most of the containers defined in the pipeline yaml. As result, pipeline stage for running java/maven code doesn't get executed complaining that the container environment for execution is missing.
Resolution: 
First hyphen (-) in `program-service-executor` label in Jenkinsfile for the pipeline seems to conflict with Jenkins Kubernetes plugin. It requires further testing to determine if it's a combination `program-service` that causes the conflict or the issue has to do with using multiple hyphens in the label name. For now changing pod label to `programservice-executor` seems to fix the issue. This change doesn't impact any networking policies in place as it the labels in question get applied as additional one when `jenkins-slave` is the primary label that will be applied on every jenkins executor pod and used for all network policies.
