### ISSUE TITLE
Create ES Index to develop against 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#556]
Create a index against the new mapping with fake data to develop against:

https://github.com/icgc-argo/argo-metadata-schemas/issues/41 
- `release_stage` should have the values from here: https://wiki.oicr.on.ca/display/icgcargotech/Program+Membership+Metadata+Access+Control

Make new index and alias it in:

- PACA-CA Associate program with all publicly released files  
- OCCAMS-GB - FULL program  with all full release files 
- DASH-CA - Associate program with all associate release files 
- TEST-CA - Associate program with files in each stage stage

@anncatton has written a script in the past to generate some files - perhaps we can edit and reuse that!?!?!?!  modify and run script.

**Comment by ciaranschutte** [comment]
adding @hlminh2000 as assignee in case follow up questions with script
