### ISSUE TITLE
Data Release 2 for Platform - backup infrastructure

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#558]
- [ ] @rosibaj  Prep release and suppress any analysis
- [ ] @blabadi To record files list of DR1, backup the ES documents to to same location as the platform backups (cumulus to collab @akachru-github info)

**Comment by blabadi** [comment]
https://wiki.oicr.on.ca/pages/viewpage.action?pageId=150634679

**Comment by blabadi** [comment]
done experimentation, results here: https://wiki.oicr.on.ca/pages/viewpage.action?pageId=150634679 


will need to:
- upgrade elastic chart version in all envs
- work with devops on setting prod nfs directory
- enable backups for prod
- take the backup for file_centric_1.0
- test restoring it in staging.
- update wiki and if possible create jenkins task to do the snapshots

**Comment by rosibaj** [comment]
For Release, QC steps/process prepared here: https://wiki.oicr.on.ca/display/icgcargotech/Data+Relase+QC

**Comment by blabadi** [comment]
this ticket needs this : https://github.com/icgc-argo/roadmap/issues/577

to proceed

**Comment by blabadi** [comment]
Henro notified me he created the nfs export, so I assume this is unblocked now.

**Comment by blabadi** [comment]
snapshot of the index is taken and now in the nfs under 
/prod/data-releases
