### ISSUE TITLE
Update the platform-maestro file_centric mapping 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#559]
Using the mapping from this ticket: https://github.com/icgc-argo/argo-metadata-schemas/issues/41 

- [ ] update the Argo instance of maestro to the to use the latest mapping 

# Exit Criteria 
Fields can be seen in ES documents (not populated with data)

**Comment by Buwujiu** [comment]
Updated file_centric_1.0 in argo dev and qa.

**Comment by rosibaj** [comment]
@Buwujiu this has not yet been in production so reopening.

**Comment by blabadi** [comment]
deferred to next release due to : https://github.com/overture-stack/arranger/issues/615

**Comment by rosibaj** [comment]
@hlminh2000 we had issuess with the data release again (discussed in sprint planning), so i will again hold this from release

**Comment by hlminh2000** [comment]
ok I did not do anything fr this ticket for now.

**Comment by rosibaj** [comment]
@blabadi i think we probably still dont want to do this as we have not released - should we close this ticket in favour of an index update later with  the release-management changes?
