### ISSUE TITLE
Create Score "Lab" environment to test upload/download as a part of infrastructure upgrades

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/roadmap#563]
Score “lab” environment. Request comes from score upload issues, long term regular testing on score upload / download

Notes:
- Good spot for this is in Overture kubs cluster, in a new namespace. Score/Song instance to point to Jared’s lab.
- Let’s try to have in place for the next Ceph / Openstack upgrade. 
- Score relying on S3 compliant API from Ceph. So that should be the focus.

**Comment by puneet-oicr** [comment]
Tabled till the next Ceph upgrade.

**Comment by puneet-oicr** [comment]
Closing this ticket as scope is no longer relevant
