### ISSUE TITLE
Upgrade Ego to 3.2.0

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#564]
- includes application to application jwt for auth instead of user api keys

**Comment by anncatton** [comment]
https://github.com/overture-stack/ego/releases/tag/3.2.0

**Comment by rosibaj** [comment]
No issues observed in platform or RDPC

**Comment by rosibaj** [comment]
@blabadi is there a version number to add to this ticket?

**Comment by blabadi** [comment]
yeah it's in the title

**Comment by rosibaj** [comment]
@blabadi I apologize that that my question was not clear enough.  As per the established process for me to move this ticket to the awaiting release stage, as the developer responsible for this ticket in the sprint can you label this ticket with the version number of whatever requires updating for the next release manager? If that is not required or no additional information is required to communicate to the release manager, can you indicate that here as a comment so that it is clear to other as to why I moved this forward without the version tag that is usually expected.

**Comment by rosibaj** [comment]
- We will rollback to the last working version of Ego as part of the release 
- this ticket will be closed as wont-do 
- we will make another ticket for the next working version of Ego

**Comment by hlminh2000** [comment]
Ego version in dev and QA has been rolled back to previous version `3.1.1`

**Comment by rosibaj** [comment]
done and ticket is linked.
