### ISSUE TITLE
Create NFS exports for each environment to backup elastic search

### ISSUE THREAD

**Issue by blabadi** [icgc-argo/roadmap#577]
- [x] ARGO dev/qa
- [x] ARGO staging/prod

**Comment by akachru-github** [comment]
@blabadi and @rosibaj do we know how long the retention period is for this ES snapshot data? Are we trying to keep this indefinitely? Or is this temporary in order to facilitate the data release?

**Comment by blabadi** [comment]
> @blabadi do we know how long the retention period is for this ES snapshot data? Are we trying to keep this indefinitely?

for the files data releases (happens every few months)  yes indefinitely .

**Comment by b-f-chan** [comment]
@henro001 to follow-up with @blabadi as this may no longer be required - Close if not needed
