### ISSUE TITLE
Deploy new "Submission" instance of Song and Score

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/roadmap#578]
As a part of the Molecular Data Release, we will be setting up a dedicated instance of Song and Score for external users to submit their data to. This is INDEPENDENT of the current instances that are running (Song/Score and Intermediate Song/Song)

This will be a net new instance we will need to set up in DEV, QA, PROD. Ultimately, this "Submission" Song/Score will be publicly accessible in production. 

- [x] "Submission" Song / Score set up in rdpc-collab-dev
- [x] "Submission" Song / Score set up in rdpc-collab-qa
- [x] "Submission" Song / Score set up in rdpc-collab (RDPC prod)

**Scope update**:
Pre-reqs:
- [x] Add new Kafka topics for submission song through Maestro helm values
- [x] Add DNS entries for new submission ingress objects

Clean-up:
- [x] Update wiki with resources urls
- [x] Add new endpoints to zabbix monitoring
- [ ] Push/merge updated yamls and helm values to infra repos

Follow up on following issues after closing the ticket:
* Pipeline for submission-song and submission-score deployment
* Document security context patching for postgres statefulset in song helm chart
* Address issue with piling unused pvc volumes in Openstack

**Comment by yalturmes** [comment]
Reviewed requirements for additional "submission-song" and "submission-score" app instances in RDPC namespaces.
Following details require clarification to progress this further:
* Assumption - we are using already deployed ego instance for auth in Song/Score. To be confirmed.
* Assumption - each song app instance comes with its own postgres db from chart. Submission song instance will also use its own db instance. To be confirmed.
* Do we need a separate set of S3 buckets for submission score configuration or do we reuse one that already exists?
Will work with @rtisma to clarify these details.

Aside from the above - confirm where to find details for the intermediate-song intermediate-score charts configurations in case it is needed to compare configs.

**Comment by yalturmes** [comment]
Status update:
Most details necessary for submission song/score setup have been clarified and config drafts are being prepared.

**Scope update**:
Pre-reqs:
* Add new Kafka topics for submission song through Maestro helm values
* Add DNS entries for new submission ingress objects

Clean-up:
* Update wiki with resources urls
* Add new endpoints to zabbix monitoring
* Push updated yamls and helm values to infra repos

**Comment by yalturmes** [comment]
Progress update:
* Maestro values have been updated for rdpc dev/qa environments.
* DNS records for ingress has been created for all environments.
* Added networkpolicies for submission-song in dev/qa environments.
* Deployed submission-song and submission-score in dev/qa environments.

**Comment by akachru-github** [comment]
Spoke to the team to confirm that this deployment to production will be on the PRIVATE INGRESS to start.

**Comment by yalturmes** [comment]
Progress update:
* Maestro helm values have been updated for rdpc prod env
* Added networking policies for submission-song/score in prod env
* Added networking policies to allow submission-score to communicate with kafka
* Deployed submission-song/score in prod
* Configured zabbix monitoring for the new submission ingress endpoints
* Updated monitoring wiki page with details/urls
* Pull requests with updated netpols and new helm values have been issued

Things are ready for testing - @rosibaj over to you. Please let me know if something is missing.
