### ISSUE TITLE
Design and Architecture for Reporting

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#581]
Investigate how to query the required elements in the `workflow-graph-node` for reporting purposes
- for example, we need to answer 
-- How many workflows are queued at a specific graph-node?
-- How many workflows are currently running at a specific node and at all graph-node? 
-- How many workflows are in the dlq for each graph-node? 
-- in the case of dlq, how/why/reason for dlq entry? 
-- How can we intervene with queues manually  to push/pop from a graph-node queue? 

- some might make sense at the graph-node
- any usable rabbitMQ tools?

## Expected Outcome 
Wiki page detailing the investigation/design for:
- API Specification for manipulating graph-nodes
- API/service specification for high-level graph-node reporting at a system and node level 
-

**Comment by lepsalex** [comment]
@rosibaj @andricDu please review when you have a chance: https://wiki.oicr.on.ca/display/icgcargotech/Graph+Manager+Design%3A+RabbitMQ+Reporting+and+Queue+Management
