### ISSUE TITLE
Deploy Schema Registry 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#582]
When a workflow is registered, it has:
- workflow name/repo etc
- a schema for input params

For workflows, we need a schema registry for workflows.  Basically, when a workflow is registered it should also be registered with an "input schema" the defines how the parameters should be shaped to launch the workflow. 

- deploy the local schema registry spring/cloud schema registry (api included)

**Comment by andricDu** [comment]
Created: 
- Repo https://github.com/icgc-argo/workflow-graph-registry
- Dockerfile
- Jenkinsfile

**Comment by andricDu** [comment]
https://hub.docker.com/repository/docker/icgcargo/workflow-graph-registry

**Comment by andricDu** [comment]
Postgres deployed with bitnami/postgresql helm chart.

**Comment by andricDu** [comment]
Helm chart created.
