### ISSUE TITLE
Deploy test ego song and score to Jared's Lab

### ISSUE THREAD

**Issue by rtisma** [icgc-argo/roadmap#584]
In order to test ceph upgrades done in the lab, we need a disposable environment.

I believe this is even easier and less work. Create a new namespace called `test-lab` and deploy ego, ego-ui, score, song. There will be ingress

**Comment by yalturmes** [comment]
Looks like a duplicate to ticket:
https://app.zenhub.com/workspaces/argo-mega-board-all-repos-5c8c8637777e5f767e486217/issues/gh/icgc-argo/roadmap/563
Closing ticket.
