### ISSUE TITLE
Migrate wf jobs to new namespace for Managment

### ISSUE THREAD

**Issue by rtisma** [icgc-argo/roadmap#585]
Update deployment of management to deploy pods to the `rdpc-wes-{{ .Release.Namespace }}`. This is not a trivial task. It was partially done, but needs more time.

Will need support for @yalturmes / @henro001

**Comment by rosibaj** [comment]
- correct PRs not linked 
- Cannot be reviewed,

**Comment by rosibaj** [comment]
- network policies are blocking traffic from one namespace to the other
- @yalturmes  and @lepsalex worked on this, but it is still blocked.  need input from @henro001

**Comment by rosibaj** [comment]
Followup after develpoment: 
https://github.com/icgc-argo/workflow-roadmap/issues/70 
https://github.com/icgc-argo/workflow-roadmap/issues/71
