### ISSUE TITLE
Reverse Proxy Song/Score URLS to one 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#594]
This is for https://song.rdpc.cancercollaboratory.org AND https://score.rdpc.cancercollaboratory.org 
We will do a future rev-proxy for Submission-song

- Reverse Proxy Song/Score URLS to one URL `https://storage.rdpc.cancercollaboratory.org`
- Reverse Proxy Song/Score URLS to one URL `https://storage.rdpc-qa.cancercollaboratory.org`
- Reverse Proxy Song/Score URLS to one URL `https://storage.rdpc-dev.cancercollaboratory.org`
- Reverse proxy will be handles by the ingress layer which can be passed to future RDPC's
-  Maybe as Kubernetes Ingress [be mindful of future deployemnts).  If not possible, then NGINX

**Comment by rosibaj** [comment]
@henro001 @akachru-github this is pretty high priority so can we please discuss!

**Comment by blabadi** [comment]
@rosibaj 
you can test the urls if you want to double check, it's currently deployed in all rdpc environments, if everything looks good it can be closed
