### ISSUE TITLE
Maestro connectivity issue to rdpc song 

### ISSUE THREAD

**Issue by blabadi** [icgc-argo/roadmap#602]
cluster: argo-dev
ns: argo-qa
deployment: maestro

there seem to be a network connectivity problem between platform and rdpc qa (maestro -> song)
```
io.netty.channel.ConnectTimeoutException: connection timed out: song.rdpc-qa.cancercollaboratory.org/142.1.177.177:443
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$2.run(AbstractEpollChannel.java:575)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ Request to GET https://song.rdpc-qa.cancercollaboratory.org/studies/all [DefaultWebClient]
```
I tested the url form the browser and everything works ok:
 https://song.rdpc-qa.cancercollaboratory.org/studies/all
 this is a very fast api, shouldn't timeout

**Comment by akachru-github** [comment]
from henro: 
there was a missing taint  on the new master nodes, so the maestro pod ran on master nodes, I added the taint and restarted the pod, can you confirm it works

**Comment by blabadi** [comment]
I confirmed there is no timeout anymore, requests are going through as expected.
Thanks
