### ISSUE TITLE
Implement pull-through cache using local Docker Registry

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/roadmap#604]
As a result of the Dockerhub rate limiting put in place on Nov 2 2020, we will be implementing a pull-through cache that will allow us to stay under the rate limits of Dockerhub is imposing.

While we have migrated the core RDPC services to use Github Packages, we will still rely on third party Dockerhub pulls for tooling and infrastructure components that we do not own. The pull-through cache will reduce the number of times we have to reach out to Dockerhub for a live pull. 

- [x] ARGO DEV/QA
- [x] RDPC DEV/QA

- [x] ARGO STAGING/PROD
- [x] RDPC PROD

**NOTE:** Ticket scope has been extended to include following:
- re-organize ansible projects structure to enable consistent and predictable project structure setup across the board and standardize on location reusable project componenets
- The original ticket scope included creation of ansible role `docker_tweaks` that sets up docker daemon on kubernetes nodes to use pull through cache. It has been decided pilot ansible-galaxy as a mechanism for including role into ansible project from a dedicated role repo.

**Comment by akachru-github** [comment]
Decisions to be made:
1) How many cache instances do we need? Per data centre or per cluster?

**Comment by yalturmes** [comment]
At this point we have agreed to try configuring a pull through cache registry on per kubernetes cluster basis.
Updated environments in ticket description.

**Comment by yalturmes** [comment]
Progress update:
Docker registry with caching enabled has been configured on argo dev/qa and rdpc dev/qa clusters.
Docker daemon has been configured to use respective docker registries for caching on all cluster nodes in argo dev/qa and rdpc dev/qa.

**Comment by yalturmes** [comment]
Progress update:
Docker registry with cachning has been configured on argo prod and rdpc prod clusters
Docker daemon has been configured to use respective docker registries for caching on all cluster nodes in argo prod and rdpc prod clusters.
Pull request to argo-infa repo includes following:
- docker-registry helm values
- re-organized ansible project structure
- playbook and role references for ansible-galaxy installation of `docker_tweaks` role

Aside from mentioned above changes included into argo-infra repo PR, a new dedicated role repository has been created in OICR github org - ansible-role-docker-tweaks.

Ticket will be closed as soon as PR is merged.
