### ISSUE TITLE
Updates to RDPC Registry 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#606]
- No open properties (i.e free form JSON as metadata)
- Make sure these are the properties: 
```
    {
        "code": "song.collab",
        "contactEmail": "jared@oicr.on.ca",
        "organization": "rdpc-collab",
        "name": "Cancer Genome Collaboratory",
        "storageType": "S3",
        "country": "CA",
        "url": "https://song.rdpc.cancercollaboratory.org" (should be the "unified" proxied RDPC URL specific to each RDPC
   }
```

## Expected Outcome 
- DataCenters Service does not accept any JSON, but only accepts the established parameters
- should be prod ready.

**Comment by blabadi** [comment]
urls:
https://dc.platform.staging.icgc-argo.org/api-docs/
https://dc.platform.icgc-argo.org/api-docs/
