### ISSUE TITLE
icgcargo / daco2ego: Migrate from Dockerhub to Github Packages

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/roadmap#624]

**Comment by yalturmes** [comment]
All confusion with branches aside, looks like the image was already being published to the ghcr registry.
Jenkinsfile was updated to remove leftovers from outdated DIND instructions.

Next up:
- Communicate changes with @rosibaj 
- Provide details for redeploying image to the IT team
- Image:tag to use for redeployment - `ghcr.io/icgc-argo/daco2ego:d750ab5`

**Comment by b-f-chan** [comment]
Fixed, image published, just waiting for Monday for confirmation there's no issues after redeploy

Check with @rosibaj if any formal testing required or just confirm nothing is breaking

**Comment by rosibaj** [comment]
no formal testing - just need to make sure it works over the next 2-3 days!

**Comment by yalturmes** [comment]
Updated Daco2ego image has been redeployed by the IT team. 
@rosibaj confirmed service looks healthy after redeployment.
Closing ticket.
