### ISSUE TITLE
Request to expand argo dev/qa cluster in collab

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/roadmap#641]
- Some math needs to be done to determine the amount of expansion.
- Let's get some numbers from @hlminh2000 and @blabadi. How much should we expand? Both storage and compute?

**Comment by akachru-github** [comment]
cc. @henro001 , @yalturmes , @jmimico

**Comment by akachru-github** [comment]
Hi @blabadi  and @hlminh2000 , do you have any thoughts on what is needed for the expansion of the Argo DEV/QA cluster?

**Comment by puneet-oicr** [comment]
Outdated.

**Comment by puneet-oicr** [comment]
Outdated.
