### ISSUE TITLE
Helm Upgrade Vault

### ISSUE THREAD

**Issue by henro001** [icgc-argo/roadmap#646]
- Upgrade the chart 
- Migrate from Helm2 to Helm3
- Argo DEV env - Migrate from ETCD to consul backend

--
https://wiki.oicr.on.ca/display/icgcargotech/Vault+upgrades
--

- [x] argo dev 
- [x] argo prod

- [x] rdpc dev 
- [x] rdpc prod

**Comment by akachru-github** [comment]
Current status:
- ARGO DEV: new vault setup and switched over
- RDPC DEV: done (only used by backup charts)
- ARGO PROD: new vault setup. TODO - SWITCH OVER (migrate the data, then switch over the ingress. Outage expected. This will be done as a part of the ARGO release. We will coordinate with @rosibaj on when this can be done. 
- RDPC PROD: done (only used by backup charts)

**Comment by rosibaj** [comment]
Confirmed via slack with @joneubank that the switchover went well - this is completed in ARGO prod env now, so closing this ticket (cc @akachru-github).
