### ISSUE TITLE
Test Data for RDPC-Platform Connections 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#652]
Devleop test Data for Testing Dashboard

For DASH-CA Submit data based on:

- WXS Tumour BAM analysis: https://song.rdpc-qa.cancercollaboratory.org/studies/TEST-PR/analysis/1d891219-5b8e-4bc3-8912-195b8ebbc3d7
  alignment running duration: ~15mins

- WXS Normal BAM analysis:  https://song.rdpc-qa.cancercollaboratory.org/studies/TEST-PR/analysis/56847fc7-7457-4df2-847f-c77457edf2a4
  alignment running duration: ~12mins

- Sanger-WXS running duration:  ~10mins 

Once rosi submits these payloads, @lepsalex can use Model-T to 

- Analysis formatted for model t `alignment` here: 
[test_analysis_for_qa_model_tee.txt](https://github.com/icgc-argo/roadmap/files/5644028/test_analysis_for_qa_model_tee.txt)
- Analysis formatted for model t `sanger` and `mutect` here: 
<<<------ NEEED SHEET ------>>>>>

**Comment by rosibaj** [comment]
- data is ready
- payloads are ready 
- sample registration is ready, but QA is not working

**Comment by rosibaj** [comment]
data has been submitted to submission-qa-song 
```
curl --location --request GET 'https://submission-song.rdpc-qa.cancercollaboratory.org/studies/DASH-CA/analysis?analysisStates=PUBLISHED' \
--header 'Authorization: Bearer ------'
```

**Comment by rosibaj** [comment]
Analysis formatted for model t here: @lepsalex 
[test_analysis_for_qa_model_tee.txt](https://github.com/icgc-argo/roadmap/files/5644028/test_analysis_for_qa_model_tee.txt)

**Comment by lepsalex** [comment]
thank you @rosibaj, will get that going next week once everything is deployed to prod

**Comment by rosibaj** [comment]
https://github.com/icgc-argo/platform-ui/pull/1805

**Comment by rosibaj** [comment]
Closing this ticket as the scope has been changed for https://github.com/icgc-argo/roadmap/issues/711
