### ISSUE TITLE
Add Jenkins Pipeline Shared Libraries for Docker Build / Publish

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/roadmap#653]
Background:
- As a result of Dockerhub rate limits, we had introduced docker pull-through caches in our clusters to avoid doing live pulls from Dockerhub all the time. 
- It was found the DinD (Docker in Docker) builds were not respecting the cache, instead doing live pulls **all the time**, adding to our rates unnecessarily
- The team found they needed to make changes to our Jenkins pipelines to ensure that DinD respects the pull-through cache

Scope:
- We want to make the changes to all Jenkins Pipelines in a modular way, to pave the way for a cohesive, fully modularized approach to our Jenkins file. 
- This epic is focused on **modularizing only the Docker Publish and Docker Build** portions of the pipeline for all our services. This means that each service pipeline will have standardized shared code for publishing and building docker images.
- This shared code will also include the necessary changes to have the DinD respect the pull-through cache
- Another epic will be created for further modularization of the pipelines at a later date. 

cc. @henro001 , @andricDu , @yalturmes

**Comment by puneet-oicr** [comment]
Closing, irrelevant.
