### ISSUE TITLE
Kubernetes upgrade 1.17.9

### ISSUE THREAD

**Issue by henro001** [icgc-argo/roadmap#659]
https://wiki.oicr.on.ca/display/icgcargotech/20201123+-+Upgrade+Kubernetes+to+1.17.9

- [x] Argo Dev
- [x] RDPC Dev
- [x] Argo Prod
- [x] RDPC Prod
- [x] Cancogen Prod

**Comment by akachru-github** [comment]
RDPC dev upgrade (DEV and QA envs) went smoothly. 
- REMEMBER! Update the playbook for kubespray vars to update metrics interface for kube proxy. 

RDPC Prod:
- Ghost Pods (oouuuuuu)
  - wf job, associated nextflow pods. but it seems like they disappear. 
  - potentially: pods that are completed and the node is drained, they may disappear entirely. 
  - We need to confirm this before going to production on RDPC upgrade.
