### ISSUE TITLE
Emptydir - Setup network policies to allow traffic between the WES-RDPC-<<ENV>> pods and the infra pods from the existing (old) namespace 

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/roadmap#679]
- [x] RDPC DEV
- [x] RDPC QA
- [x] RDPC PROD

**Comment by yalturmes** [comment]
Status update
* Netpols have been updated in RDPC DEV/QA/PROD env to allow communication with respective dedicated workflow namespace
* PRs with changes for DEV/QA env are already merged
* PRs for prod have been issued and will be merged as soon as reviewed
* Documentation updated: https://wiki.oicr.on.ca/pages/viewpage.action?pageId=154537283b namespace
