### ISSUE TITLE
Emptydir - Create (or move) persistent volumes and their claims in the new namespace

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/roadmap#681]
Disruptive. 

- [x] RDPC DEV
- [x] RDPC QA
- [x] RDPC PROD

**Comment by yalturmes** [comment]
Status update
* Nextflow PVs/PVCs have been moved to designated workflow namespace in RDPC DEV/QA/PROD env
* PRs with changes for DEV/QA env are already merged
* PRs for prod have been issued and will be merged as soon as reviewed
* Documentation updated: https://wiki.oicr.on.ca/pages/viewpage.action?pageId=154537283b namespace
