### ISSUE TITLE
[Kafka Backup] - Backup additional topics 

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/roadmap#692]
- The current implementation of Kafka backups is only backing up weblog. 
- This ticket represents the work reuiqred to backup additional topics. 

---

Kafka connect chart has been updated to support list of topics to back up. The following has been configured in all RDPC environments

`topicList: "weblog,graphlog_info_debug,graphlog_error_warning"
`

**Comment by akachru-github** [comment]
Topics are explicitly defined. This will need to be added purposefully. 
This is a value in the helm chart that gets written to a config file.

**Comment by akachru-github** [comment]
@lepsalex , @andricDu , just wanted to confirm that this is still something you want as a part of the kafka backup? If so, we will add the config to include this topic.

**Comment by lepsalex** [comment]
there are two new topics, `graphlog_info_debug` and `graphlog_error_warning`, they will have different retention periods and so the backup policy should reflect that as well
