### ISSUE TITLE
icgcdcc: dcc-iobio - Migrate from Dockerhub to Github Package

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/roadmap#693]
https://hub.docker.com/repository/docker/icgcdcc/dcc-iobio

**Comment by yalturmes** [comment]
The image has been pulled from dockerhub and pushed to ghcr.io as is. New docker image location url:
ghcr.io/icgc-argo/dcc-iobio

Next steps as agreed with @andricDu :
- [ ] Update ansible playbook with new image location - https://github.com/icgc-dcc/dcc-iobio-infra/blob/master/roles/iobio/tasks/main.yml#L7
- [ ] Re-deploy application using the new playbook.

**Comment by akachru-github** [comment]
Image has been migrated as is. 
Ansible playbooks need to be updated to use the new Github Packages.

**Comment by rosibaj** [comment]
@rosibaj pull into next CM sprint

**Comment by jmimico** [comment]
I am not familiar with dcc-iobio but I have access to prod system and here's what's running:

```
root@iobio-collab:~# docker ps
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS              PORTS                  NAMES
8a07f6814242        icgcdcc/dcc-iobio:latest-vcf   "/bin/sh -c /entrypo…"   3 months ago        Up 2 months         0.0.0.0:8080->80/tcp   vcf
deec059b1458        icgcdcc/dcc-iobio:latest-bam   "/entrypoint.sh"         3 months ago        Up 5 days           0.0.0.0:80->80/tcp     bam
```

**Comment by jmimico** [comment]
Security group for this server is only allowing the following traffic:

iobio

```
        ALLOW IPv4 8443/tcp from 0.0.0.0/0
        ALLOW IPv4 80/tcp from 0.0.0.0/0
        ALLOW IPv4 53/tcp from 0.0.0.0/0
        ALLOW IPv4 to 0.0.0.0/0
        ALLOW IPv6 to ::/0
        ALLOW IPv4 icmp from 0.0.0.0/0
        ALLOW IPv4 443/tcp from 0.0.0.0/0
```

**Comment by jmimico** [comment]
@yalturmes can you check to see if ghcr should be building two versions of iobio? On dockerhub we leverage two tags `latest-vcf` and `latest-bam`. Github repo mentions both tags here too: https://github.com/icgc-dcc/dcc-iobio . Reason I ask is on github package I only see `:latest`

**Comment by jmimico** [comment]
root@iobio-collab:~# docker ps --all
CONTAINER ID        IMAGE                                   COMMAND                  CREATED             STATUS              PORTS                  NAMES
46d3214b9829        ghcr.io/icgc-dcc/dcc-iobio:latest-vcf   "/bin/sh -c /entrypo…"   13 minutes ago      Up 13 minutes       0.0.0.0:8080->80/tcp   vcf
123ce44b72a4        ghcr.io/icgc-dcc/dcc-iobio:latest-bam   "/entrypoint.sh"         13 minutes ago      Up 13 minutes       0.0.0.0:80->80/tcp     bam

**Comment by jmimico** [comment]
Created a small script in root directory to cycle the containers if needed too
