### ISSUE TITLE
DAC UI updates

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/roadmap#696]
Footer:
- [x] About DAC should go to: https://www.davosalzheimerscollaborative.org/
- [x] Contact Us should go to: https://www.davosalzheimerscollaborative.org/contact-us
- [x] copyright should read: ©2021 Davos Alzheimer’s Collaborative

Fonts: see zeplin for where these are used: https://zpl.io/a7XlrGR
- [x] body font: poppins google: https://fonts.google.com/specimen/Poppins
- [x] title font they use is: AcuminVariableConcept (I have a otf file, but if too hard to implement can just use Poppins everywhere)

Other
- [x] update favicon to same one used on their website: https://www.davosalzheimerscollaborative.org/
- [x] query box - the connector words "in, and, is" are too light. Use the same colour as the field name text
![image](https://user-images.githubusercontent.com/18424138/104653415-94632a80-5688-11eb-9026-3066ef577605.png)

Facet Changes: 
<pending> 
![image](https://user-images.githubusercontent.com/15824252/105065222-9e4fa980-5a4b-11eb-9d42-efa2bdb931ec.png)

**Comment by rosibaj** [comment]
Data update to support the changes above: 
https://github.com/IHCC-cohorts/data-harmonization/blob/fc4f77bcb8f0bb5487f68766b449601399406892/data/cohort-data.json
