### ISSUE TITLE
Configure automation for icgcargo/backup-psql image

### ISSUE THREAD

**Issue by yalturmes** [icgc-argo/roadmap#702]
icgcargo/backup-psql image is used for backups with psql services in ARGO and RDPC.
It is necessary to configure Jenkins job that can publish the image to Github Packages registry and provides a reliable mechanism for updating image later.

**Comment by akachru-github** [comment]
on which jenkins instance should we configuring CI CD pipeline jobs for backups in general?

**Comment by yalturmes** [comment]
Automation for psql-backup image build is configured on argo QA jenkins cluster.
All changes merged.
