### ISSUE TITLE
Initialize Legacy Program `PACA-AU` --> `APGI-AU` in ICGC ARGO 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#706]
The Legacy Program PACA-AU is ready to be initialized in ICGC.  

SOP: 
https://wiki.oicr.on.ca/display/icgcargotech/Activating+Legacy+ICGC+Programs+in+ARGO 

1. We are activating `APGI-AU`, formerly known as `PACA-AU`. 
> NOTE: we have a problem. An accident happened, and someone forgot that we needed to do an import process wiht Legacy programs.  The Program was already created in prod (so in Ego + Program Service) but is not linked correctly
This needs to be deleted? or massaged? Discuss in planning. 
2. Three batches of data are ready here: 
- PCAWG WGS: https://github.com/icgc-argo/argo-meta/tree/master/icgc_song_payloads/APGI-AU/WGS/batch1-pcawg
- non-PCAWG WGS: https://github.com/icgc-argo/argo-meta/tree/master/icgc_song_payloads/APGI-AU/WGS/batch2-non-pcawg 
- WXS: https://github.com/icgc-argo/argo-meta/tree/master/icgc_song_payloads/APGI-AU/WXS/batch3-wxs

**Comment by rosibaj** [comment]
Will hold until the ESAD-UK Data Issue is resolved.

**Comment by rosibaj** [comment]
@hknahal Can you confirm that this data batch looks good for you to start running?

**Comment by hknahal** [comment]
@rosibaj I confirmed the three APGI-AU batches look good:

WGS PCAWG (29 donors): https://github.com/icgc-argo/argo-meta/blob/master/icgc_song_payloads/APGI-AU/report-WGS-batch1-pcawg.json
WGS non-PCAWG (19 donors): https://github.com/icgc-argo/argo-meta/blob/master/icgc_song_payloads/APGI-AU/report-WGS-batch2-non-pcawg.json
WXS (45 donors): https://github.com/icgc-argo/argo-meta/blob/master/icgc_song_payloads/APGI-AU/report-WXS-batch3-wxs.json

These should be good to start running.
