### ISSUE TITLE
Investigate/Design - Clinical Data Integration with File Service 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#709]
Assuming we have the `file/analysis` information, we need to add clinical data: 

- Define the difference between `released` clinical data and `unreleased` clinical data and what users should see 
- Show how/when the clinical data will be updated with the Release mechanism.

# Expected Outcome 
- [ ] WIki Page describing the compilcations/plans 
- [ ] More Tickets for followup

**Comment by akachru-github** [comment]
This dupes another design ticket with a wiki: 
https://app.zenhub.com/workspaces/icgc-argo-platform-dk-production-board-5e542d38415f5034e9fed89d/issues/icgc-argo/files-service/56

Closing.
