### ISSUE TITLE
Audit stale and invalid volumes in all Kube environments

### ISSUE THREAD

**Issue by henro001** [icgc-argo/roadmap#713]

**Comment by jmimico** [comment]
Offending volumes:

ID / Volume Name / Status / Size (GB)
6e3d7bde-31ec-4dd0-a43d-8770d5f1dbc4 kubernetes-dynamic-pvc-83829338-69ed-405e-a3d3-d84ad5ac5afe error_deleting 30
5e277595-7d70-4db1-be83-c111d4463e7d kubernetes-dynamic-pvc-5cf74387-3713-409e-acec-c6aecf152e2a error_deleting 30
1ff31c9c-abaf-455e-a59f-93605105c7a0 kubernetes-dynamic-pvc-7f00d1db-3a39-4570-bcf6-8e06f8cefd13 error_deleting 30
13316f0f-f370-438b-9d83-3630a6dfc516 kubernetes-dynamic-pvc-0dfdb2eb-cf69-48d5-b7a5-6617ff1ebfcc error_deleting 5
a66d3a99-2349-4410-8d2d-6fe1570d3beb kubernetes-dynamic-pvc-a83f24ab-b9f2-45d3-9a45-9d375a83aac8 error_deleting 2
17952d3a-6f3a-4e37-a580-14ee40666eaf kubernetes-dynamic-pvc-0fcb1ae9-523b-40ed-80cb-1993359be805 error_deleting 3
cdc166b6-c5c9-498a-86a9-caf853e2aa08 kubernetes-dynamic-pvc-af061d07-744b-4a03-b563-baf30d9f5e14 error_deleting 5
655a6884-ecb6-4150-9cd5-c9ec56641bfc kubernetes-dynamic-pvc-32a74655-eb07-444d-949c-d227b2197c6a error_deleting 2
33d66aab-2478-4fc3-981a-3cb970f9aebb kubernetes-dynamic-pvc-5089822c-d004-4e08-b3ac-f54950d54a1d error_deleting 3
eabdcea7-92d8-40c2-8a10-36adcb20860c kubernetes-dynamic-pvc-52a9509f-de8b-4e71-aea1-26c7892730d7 error_deleting 2
525a4113-9cd3-4b4f-89ba-1c15eed3bd96 kubernetes-dynamic-pvc-ab6be7e2-b0cb-49df-a4d6-d53f45f29c21 error_deleting 5
33d2b854-8042-4a5e-99e9-82c7b177554c kubernetes-dynamic-pvc-38bd8917-2053-4b50-ba41-69d2422e54dd error_deleting 3
f6004512-e5d8-4ca3-ac43-264d1e64cc26 kubernetes-dynamic-pvc-73abc795-ce84-11e9-91e6-fa163e1faed5 error_deleting 30
c0e573fc-5643-4591-8714-ee3802990166 kubernetes-dynamic-pvc-73a4b793-ce84-11e9-91e6-fa163e1faed5 error_deleting 30
57d6eca9-7e68-4103-baf2-4b8f0e792385 kubernetes-dynamic-pvc-73af9225-ce84-11e9-91e6-fa163e1faed5 error_deleting 30
2739a67e-c686-4e8c-8a21-25f50696f9ce kubernetes-dynamic-pvc-e1d6beea-3153-43c4-84a4-9cb7cccf356b available 8
4b493500-06ae-4ba2-85e9-6708e696792b kubernetes-dynamic-pvc-50ff6303-9cf4-4fb6-9c6f-60e0e1cf5b89 available 10
35629e9d-ae71-4dc0-a14c-20e0a9477ceb kubernetes-dynamic-pvc-6da49a63-009b-4791-91d7-6c305f5763f2 available 20
1c7971d9-956f-44c9-98f8-9a70b4c5b78b kubernetes-dynamic-pvc-5d8de8f5-bcbb-47a2-9baf-2a439415f5ae available 50
90204178-e7bb-44db-9a35-2c3acb6d2ba6 kubernetes-dynamic-pvc-964640c3-cf9f-41b7-a0f1-c9c9ca8a2d98 available 2
d4a917cb-952a-476b-85ca-ce4a0203c68e kubernetes-dynamic-pvc-d51f880a-ffc6-48f0-84f6-e8206a716e32 available 2
4fbcba4b-ced8-4d80-bdde-ee22fe1dcb8e kubernetes-dynamic-pvc-83c456ad-2498-4125-8c83-68307a5631fe available 2
34f68fb1-679b-4e23-8e7e-71876eec9e32 kubernetes-dynamic-pvc-b8b2f895-f820-40f4-b8d0-a6623321abf1 available 2
59efd199-cd39-46c2-879b-1728e265c53b kubernetes-dynamic-pvc-43bc5d0b-ebe2-401a-89c3-65074cb7f4cf available 20
9bc2401c-dbd1-4305-8dfe-bcf55f52acf2 kubernetes-dynamic-pvc-1709478e-7e5e-44c6-b464-da57b686cf0d available 50
4c671515-6a09-4d4f-ab4a-e43ffdc0fc1b kubernetes-dynamic-pvc-a377d4e9-04d8-4186-b109-3e9c46932328 available 10
a863f8ac-eb2b-4575-a824-531121f02298 kubernetes-dynamic-pvc-440cb892-c8e6-470e-9946-59b79e747b7b available 8
09dcae94-07a9-4b16-812e-e4bb5fce40af kubernetes-dynamic-pvc-77111eb8-e40e-413b-9694-54e00ee358d3 available 8
70bb763a-d910-42bf-a4f8-6f9fc0f9e009 kubernetes-dynamic-pvc-f3f11379-95f7-491e-b5ac-59a5652aaa7d available 8
b3753f44-b2a8-48e7-97c1-7a870f66a07e kubernetes-dynamic-pvc-0bc4bbbb-02e1-4142-bf75-5021526261ff available 8
57f54b49-83ac-4a90-90fe-1065c31a6e3e kubernetes-dynamic-pvc-9f0177e1-8c97-40f7-84ee-f2deb6dbd230 available 1
ea1448b6-67b5-45a8-9190-90756768f48b kubernetes-dynamic-pvc-5f3acb46-8b3e-4adf-a2f9-071c368fdefe available 1
26f557c5-8f72-4a11-8574-1084ce6eb715 kubernetes-dynamic-pvc-a33739c1-9500-4f83-8850-2bacba6da8ab available 8
109b5a8c-6415-45ab-8d1f-a2b1936b9e8b kubernetes-dynamic-pvc-a9b915bb-d866-46e9-baa0-ae2e8bc168fc available 8
2b197282-c3d5-4ef9-8e10-e6fa1d65fd51 kubernetes-dynamic-pvc-ed81c751-4534-4782-b3c6-0bc0d549bf18 available 8
ea84f733-f0d1-4169-a434-9468b31d5ea9 kubernetes-dynamic-pvc-36cd6911-fbdc-4bd3-b5e5-125e0c1942cb available 1
5a592957-a375-40aa-871d-aefa2b41829f kubernetes-dynamic-pvc-319b4f40-ba66-4951-ae43-52a29f340c72 available 8
edeca3ca-11c3-43b5-a379-6186b504f164 kubernetes-dynamic-pvc-a1c51836-03e1-4880-b701-4614e82e6053 available 1
0c8dade2-809a-4f80-bcbd-808868a5b945 kubernetes-dynamic-pvc-64863c38-9d72-40b1-8ef7-4ce78307981a available 10
2160eb5e-fd2e-4488-a55e-5d1dff4df636 kubernetes-dynamic-pvc-199a2d8a-825d-4cba-b491-ac9983889afa available 10
d17f9da4-a2ef-4afb-bd1d-c4fa14dd9646 kubernetes-dynamic-pvc-22c8b9a8-97b5-42c4-8eee-476d183948d8 available 5
21f0ffb7-9c60-41e6-baae-7c4925ad3fa2 kubernetes-dynamic-pvc-b5795e8e-73b7-4c5c-840c-2b2f4e04af4e available 2
1c7a9aa7-85a4-4a30-98d9-897b76b69c34 kubernetes-dynamic-pvc-796d5ed6-42dc-41ea-bd70-108b42e21d86 available 3
c98d27ff-66f8-4dd0-ba08-0cbae321c958 kubernetes-dynamic-pvc-ecacaa06-bc88-42c2-98b2-b60b43771652 available 8
62cf9518-9051-4341-82f4-1797194ad373 kubernetes-dynamic-pvc-41cc723d-e068-4b21-97e6-3ddb833b2bdb available 8
cb19889a-c5ea-460c-95ad-8acd308dc51e kubernetes-dynamic-pvc-a4ead030-1061-4b33-9980-c55eeb3fb9fe available 8
60827f35-8db9-4818-9d60-91824bcf3126 kubernetes-dynamic-pvc-71c0a0c5-2504-40f8-9cb1-9203b99b7e2f available 8
3cbddc11-ab71-4dbf-9624-6ff286fd67a7 kubernetes-dynamic-pvc-7e80503e-50ef-49f5-81b3-ed8e74e6ee4b available 8
948f24e3-fa07-4e49-9a34-1569c6782721 kubernetes-dynamic-pvc-8a85c7d9-887f-4165-9457-338ef1f92b9e available 8
989ccc09-3f1a-4eb6-8516-82cfc9281b01 kubernetes-dynamic-pvc-e1b8d295-5ff5-4a76-9ed8-e7abe349d208 available 8
c74eb4f0-1757-44b5-a700-51ba5abd1216 kubernetes-dynamic-pvc-3541b30d-fba6-4c16-b803-5796550f8b97 available 50
03de69f9-2f9e-4a9d-9744-6df8433b3a75 kubernetes-dynamic-pvc-295a7e9b-616a-4808-9a7f-fa027b8df148 available 8
7efe4a8e-a5e9-4f49-8b86-f4c44c349424 kubernetes-dynamic-pvc-1e457651-17a8-4b76-b6ae-b8cafc90e322 available 30
2c2954bc-a1fb-485c-8a22-54fe1703504f kubernetes-dynamic-pvc-22a0ed8a-9322-49df-b068-fd1a56778bc3 available 30
2695ec49-5ae6-49e6-81c5-384e7b19d0d5 kubernetes-dynamic-pvc-d8b3cac8-08cd-4cfc-8c53-8073d520a43b available 30
24e6ed83-9ab6-42e1-8e7f-4c191cd7cee9 kubernetes-dynamic-pvc-e503ae51-ae30-4c09-bd2c-26246e2c993a available 1
96e34cdf-e55f-4bd0-ad57-e74a46272279 kubernetes-dynamic-pvc-ca8a08f1-cc41-4d3b-a149-2654985eba82 available 1
60f8c7ab-e713-4e3b-83b9-538f3cdfd853 kubernetes-dynamic-pvc-684d994d-6516-4471-975d-a59009bddd17 available 1
da1f6c35-0a68-498c-8343-57d55b9da752 kubernetes-dynamic-pvc-b995025f-3556-4ec6-836a-ba60f870363a available 8
95ad2b3b-2fca-488b-a05d-3922d7930294 kubernetes-dynamic-pvc-3bb664bc-b4a8-4b4f-baa9-cfa4ae38c067 available 8
c28f1e29-a303-4511-b2e2-1b8d57e83aea kubernetes-dynamic-pvc-20d4e145-c9b7-41a9-8860-c40f08ace4fe available 1
ed46a46d-5972-4bf8-ace3-58f4949de55f kubernetes-dynamic-pvc-7dd6cd44-1df2-4b60-91ee-93a1a0dbb647 available 1
8b8e785b-232d-45e1-a8c5-a38257a1ef5f kubernetes-dynamic-pvc-c5199383-b577-4e45-996e-409bb4ea09f4 available 1
8b87b80f-1e54-4e75-921f-e7e14a1684b1 kubernetes-dynamic-pvc-a59fd6d9-d33d-4497-8938-6f39cd634d55 available 4
0e01283f-cb2b-454c-a4d2-7687353378cc kubernetes-dynamic-pvc-073c90fd-a298-44a5-ab32-88ebe593103b available 4
1345a195-3b88-41d4-bc5b-412588ad53dc kubernetes-dynamic-pvc-c362cf8e-fee0-46a0-bce8-728232f47bc0 available 4
662447dc-b237-4fd9-828c-768ee11c6a06 kubernetes-dynamic-pvc-ffe9c24e-017f-4bbc-9543-8d304edb1869 available 1
6e76a5db-5101-471e-9f10-e371e35eeae7 kubernetes-dynamic-pvc-b1f717c5-82da-45b4-ab73-d19b442a4391 available 1
274bb2b6-d989-4bc1-8fc9-72336d7f9e35 kubernetes-dynamic-pvc-020a02a7-5dc3-43aa-8861-0ad6018a7725 available 1
9390d62b-5b44-482a-81ed-4cd909e57a70 kubernetes-dynamic-pvc-c211d6ee-5849-448a-948c-1877b825cd6c available 16
4f508101-9698-42a6-bcc5-2fa54cef8da9 kubernetes-dynamic-pvc-e5e53c9a-6493-4057-a112-d2f23d076e91 available 16
6571fef9-73e4-4d13-9906-3789cf4c0fee kubernetes-dynamic-pvc-f03dfad8-55ce-4755-94dd-d2ccd2ed8e37 available 20
31d3e1f6-4472-4d93-9fb7-e33ad5763a48 kubernetes-dynamic-pvc-840ddc9f-cc64-46de-9c86-2e5c868a26e5 available 200
fc015d37-7173-4dfc-bdb0-8808bd98ffff kubernetes-dynamic-pvc-922482c0-b2d5-11e9-af27-fa163e18711a available 8
f80499ec-3fed-44db-a570-fdd7863fdfcb kubernetes-dynamic-pvc-4ae3b5c5-ae54-11e9-af27-fa163e18711a available 8
49571b36-0158-43e7-85cf-580a18808f14 kubernetes-dynamic-pvc-3739d544-aa3e-11e9-af27-fa163e18711a available 5
c7365617-44ef-4bf5-8345-25c14e650006 kubernetes-dynamic-pvc-2fc48cc6-aa3e-11e9-af27-fa163e18711a available 3
c0037254-7757-40cc-a495-f6329ed29431 kubernetes-dynamic-pvc-2fc6a395-aa3e-11e9-af27-fa163e18711a available 2
c1b44998-a1f7-4428-9fff-c6de28e4aaa1 kubernetes-dynamic-pvc-2af5b2f7-aa3e-11e9-af27-fa163e18711a available 5
2f13e0fb-edf8-4f1f-9b87-c4f34d1b56be kubernetes-dynamic-pvc-21605ced-aa3e-11e9-af27-fa163e18711a available 2
2e339a95-5221-4223-b8d8-42cbf9b93129 kubernetes-dynamic-pvc-216245ad-aa3e-11e9-af27-fa163e18711a available 3
98c320ca-144d-4ca1-94a6-a2d569e352fd kubernetes-dynamic-pvc-17a579d2-aa3e-11e9-af27-fa163e18711a available 5
979e50e9-cf63-4f4f-8173-52a20fb9ead2 kubernetes-dynamic-pvc-17cc9edd-aa3e-11e9-af27-fa163e18711a available 3
a1110414-3584-4311-a41b-69a07381fec9 kubernetes-dynamic-pvc-17cbf589-aa3e-11e9-af27-fa163e18711a available 2
f09b35cb-4c7f-4f49-8786-958aa7c21bb3 kubernetes-dynamic-pvc-de481cef-a454-11e9-af27-fa163e18711a available 8
a72d084a-1403-4071-afdc-396b5d08e80d kubernetes-dynamic-pvc-2dd48b61-a029-11e9-af27-fa163e18711a available 8
4ba35ffc-4ff1-405f-be01-be3f817e8aca kubernetes-dynamic-pvc-29eb5ac2-9f4f-11e9-af27-fa163e18711a available 8
b2d15ffc-9352-45e4-9730-19d60d575eb4 kubernetes-dynamic-pvc-cc77e685-9f2c-11e9-af27-fa163e18711a available 8
2c0a9ff9-1032-4138-bb96-f3e1fe4bcb04 kubernetes-dynamic-pvc-0a062775-98ef-11e9-af27-fa163e18711a available 8
310612b1-8f2c-4f82-86b6-d5461e057923 kubernetes-dynamic-pvc-c3239824-8b93-11e9-9ebe-fa163e1bc7e4 available 8
16394a46-fb80-458e-a7a7-ddafa612a8e8 kubernetes-dynamic-pvc-c0929eee-8b93-11e9-9ebe-fa163e1bc7e4 available 8
50ebefc9-f24a-474c-99f5-3a9fbaaa0ac8 kubernetes-dynamic-pvc-ece450bd-8b92-11e9-9ebe-fa163e1bc7e4 available 8
d109af9e-6636-4727-8d90-0fe5fa387b24 kubernetes-dynamic-pvc-cba8f6f4-8b92-11e9-9ebe-fa163e1bc7e4 available 8
d953b613-1865-4606-ba2a-4376a58c9433 kubernetes-dynamic-pvc-2292b37f-80b1-11e9-a286-fa163e18711a available 2
926563e9-0645-46f3-aa90-c65a12f56c4c kubernetes-dynamic-pvc-229186ca-80b1-11e9-a286-fa163e18711a available 3
a2621a08-20d4-4dbf-ad55-d22c70365865 kubernetes-dynamic-pvc-0985f513-80b1-11e9-a286-fa163e18711a available 3
edd7c62c-0abb-4811-a6c5-a221f6820f09 kubernetes-dynamic-pvc-0986eab9-80b1-11e9-a286-fa163e18711a available 2
965b0be8-f655-4227-836d-d0ba8377c3d5 kubernetes-dynamic-pvc-07ce76a1-80b1-11e9-a286-fa163e18711a available 5
fec4ad84-cd04-44cc-b40a-d91560452015 kubernetes-dynamic-pvc-f6e40570-80b0-11e9-a286-fa163e18711a available 2
39155698-90b1-4969-9cb6-80c003191015 kubernetes-dynamic-pvc-fd1931ca-80b0-11e9-a286-fa163e18711a available 5
662ef5e9-049f-476d-b2dc-e825e4f22ba2 kubernetes-dynamic-pvc-f6e2cf0d-80b0-11e9-a286-fa163e18711a available 3
2b9552ec-daed-4dc2-a1be-73243f85fc35 kubernetes-dynamic-pvc-f6da51e6-80b0-11e9-a286-fa163e18711a available 5
dca235b0-1e1b-4c94-9840-3574443f57a1 kubernetes-dynamic-pvc-d8d57753-809c-11e9-a286-fa163e18711a available 1
cbd4b9bc-2497-409d-9c3d-af9b7d20e79d kubernetes-dynamic-pvc-d8cda8d5-809c-11e9-a286-fa163e18711a available 1
6e153d72-9ae5-46ad-b7d0-5cb5d180642e kubernetes-dynamic-pvc-d8c8b346-809c-11e9-a286-fa163e18711a available 1
c07ba419-bbec-4d49-a845-8397c53570ab kubernetes-dynamic-pvc-99ff4d69-809a-11e9-a286-fa163e18711a available 3
75ec0959-84a2-4d83-bceb-bb7111105f8d kubernetes-dynamic-pvc-9a82260a-809a-11e9-a286-fa163e18711a available 5
3f8b9542-87c1-4322-93eb-9201fc868edb kubernetes-dynamic-pvc-99fc2d17-809a-11e9-a286-fa163e18711a available 2
ab28cd5e-c94c-4b8a-a90d-6589aa21d50d kubernetes-dynamic-pvc-8fef98ed-809a-11e9-a286-fa163e18711a available 5
7af248fd-b64f-4b54-8c9b-8c0fa522dfea kubernetes-dynamic-pvc-8fba47a8-809a-11e9-a286-fa163e18711a available 3
21ffad4c-e2b5-472a-be97-1b5cccfc51c8 kubernetes-dynamic-pvc-8fbc7b54-809a-11e9-a286-fa163e18711a available 2
e8be84e5-f9d6-4094-8059-13ed4218ea03 kubernetes-dynamic-pvc-86fd91e2-809a-11e9-a286-fa163e18711a available 3
8cbdc46e-7309-454c-883b-689ebc771ac1 kubernetes-dynamic-pvc-86eb171c-809a-11e9-a286-fa163e18711a available 5
106cfa73-87ac-4583-80fe-246643f3bd2a kubernetes-dynamic-pvc-86fe53b1-809a-11e9-a286-fa163e18711a available 2
ecc40fbc-f3d0-4cb0-b31a-302fc513463a kubernetes-dynamic-pvc-7da204e0-7e4e-11e9-a286-fa163e18711a available 2
501ae6ec-346d-46ea-b643-b77ca4bf6818 kubernetes-dynamic-pvc-7da0ef42-7e4e-11e9-a286-fa163e18711a available 3
8d02696f-baca-4c54-b6ac-34032528622d kubernetes-dynamic-pvc-66bc281b-7e4e-11e9-a286-fa163e18711a available 5
f41b618a-235c-4600-b14c-0b16a5dce2cb kubernetes-dynamic-pvc-60c52036-7e4e-11e9-a286-fa163e18711a available 3
dd841ad6-f9de-43e2-8663-0dcef9f06a95 kubernetes-dynamic-pvc-60c9f93e-7e4e-11e9-a286-fa163e18711a available 2
84b6546e-9b98-4020-8c63-239111334245 kubernetes-dynamic-pvc-59f20cf3-7e4e-11e9-a286-fa163e18711a available 5
ddd29cdb-f70b-435f-8e0f-906b38ae1fc2 kubernetes-dynamic-pvc-40e835dd-7e4e-11e9-a286-fa163e18711a available 3
d07abe54-2142-4f61-a125-d6e4bf25f290 kubernetes-dynamic-pvc-40e8fda6-7e4e-11e9-a286-fa163e18711a available 2
3ed21c15-6e84-4fa2-99c9-50f6b3fd6e0c kubernetes-dynamic-pvc-40cc5ff1-7e4e-11e9-a286-fa163e18711a available 5
8d7523e1-b805-42df-a221-b1455f2bfe62 kubernetes-dynamic-pvc-e50a51fb-7da1-11e9-a286-fa163e18711a available 8
f843f73e-18d7-4aed-9411-78210af0bd7f kubernetes-dynamic-pvc-32d94ac8-7d95-11e9-a286-fa163e18711a available 1
061f27c5-757f-4845-9a47-60577976497e kubernetes-dynamic-pvc-32dd6491-7d95-11e9-a286-fa163e18711a available 1
6ee47500-182a-4d57-b938-aed36eab169b kubernetes-dynamic-pvc-32e4a29e-7d95-11e9-a286-fa163e18711a available 1
d6a9d2a8-8d5d-49cd-b7de-b94e67abc549 kubernetes-dynamic-pvc-b968826a-7d68-11e9-a286-fa163e18711a available 1
e6f6ac1c-ef2b-4778-9fff-d3e1a564f8e0 kubernetes-dynamic-pvc-9d279f15-7d66-11e9-a286-fa163e18711a available 1
1f5c25d9-85db-4452-b280-4c17166f8d56 kubernetes-dynamic-pvc-9d413a57-7d66-11e9-a286-fa163e18711a available 1
fd8c116e-ac08-4400-835e-cac3d031f389 kubernetes-dynamic-pvc-da12c4d0-7ca5-11e9-a286-fa163e18711a available 8
bea0e374-bf7e-45bf-8c55-e3b6bcb77180 kubernetes-dynamic-pvc-fbeeb2ca-7ca2-11e9-a286-fa163e18711a available 8
6bad9c3b-8c9c-4b0d-b953-1935c08d3cf0 kubernetes-dynamic-pvc-bf9d264b-7c89-11e9-a286-fa163e18711a available 8
f045fadb-9816-4c96-99ea-7861521b6dd4 kubernetes-dynamic-pvc-f9a01646-6c3e-11e9-a8e5-fa163e1bc7e4 available 8
49c89f58-deff-4097-aa31-b540566c702d kubernetes-dynamic-pvc-0f616a44-36d9-11e9-8259-fa163e18711a available 8
32eca69d-431f-426f-9941-588e642d88eb kubernetes-dynamic-pvc-dd9b516a-3625-11e9-8259-fa163e18711a available 8

**Comment by henro001** [comment]
removed the following

argo-dev/overture-qa 21

datadir-0-confluent-qa-cp-kafka-0
datadir-0-confluent-qa-cp-kafka-1
datadir-0-confluent-qa-cp-kafka-2
datadir-confluent-qa-cp-zookeeper-0
datadir-confluent-qa-cp-zookeeper-1
datadir-confluent-qa-cp-zookeeper-2
datalogdir-confluent-qa-cp-zookeeper-0
datalogdir-confluent-qa-cp-zookeeper-1
datalogdir-confluent-qa-cp-zookeeper-2

datadir-0-kafka-overture-qa-cp-kafka-0
datadir-0-kafka-overture-qa-cp-kafka-1
datadir-0-kafka-overture-qa-cp-kafka-2
datadir-kafka-overture-qa-cp-zookeeper-0
datadir-kafka-overture-qa-cp-zookeeper-1
datadir-kafka-overture-qa-cp-zookeeper-2
datalogdir-kafka-overture-qa-cp-zookeeper-0
datalogdir-kafka-overture-qa-cp-zookeeper-1
datalogdir-kafka-overture-qa-cp-zookeeper-2
elasticsearch-master-elasticsearch-master-0
elasticsearch-master-elasticsearch-master-1
elasticsearch-master-elasticsearch-master-2




argo-dev/argo-dev 17

data-intermediate-song-argo-dev-postgres-0
data-program-service-argo-dev-postgres-0
data-song-argo-dev-postgres-0
data-ulterior-rabbit-postgres-0
data-stultified-molly-postgres-0
data-warped-deer-postgres-0
data-pruning-sparrow-postgres-0
data-test-argo-dev-postgresql-0
datadir-0-kafka-argo-dev-cp-kafka-0
datadir-0-kafka-argo-dev-cp-kafka-1
datadir-0-kafka-argo-dev-cp-kafka-2
datadir-kafka-argo-dev-cp-zookeeper-0
datadir-kafka-argo-dev-cp-zookeeper-1
datadir-kafka-argo-dev-cp-zookeeper-2
datalogdir-kafka-argo-dev-cp-zookeeper-0
datalogdir-kafka-argo-dev-cp-zookeeper-1
datalogdir-kafka-argo-dev-cp-zookeeper-2


argo-dev/argo-qa 22

datadir-0-kafka-argo-qa-cp-kafka-0
datadir-0-kafka-argo-qa-cp-kafka-1
datadir-0-kafka-argo-qa-cp-kafka-2
datadir-kafka-argo-qa-cp-zookeeper-0
datadir-kafka-argo-qa-cp-zookeeper-1
datadir-kafka-argo-qa-cp-zookeeper-2
datalogdir-kafka-argo-qa-cp-zookeeper-0
datalogdir-kafka-argo-qa-cp-zookeeper-1
datalogdir-kafka-argo-qa-cp-zookeeper-2
data-intermediate-song-argo-qa-postgres-0
data-program-service-argo-qa-postgres-0
data-song-argo-dev-postgres-0
data-song-argo-qa-postgres-0
data-song-argo-qa2-postgres-0
datadir-test-mongo-mongodb-replicaset-0
datadir-test-mongo-mongodb-replicaset-1
elasticsearch-master-elasticsearch-master-0
elasticsearch-master-elasticsearch-master-1
elasticsearch-master-elasticsearch-master-2
security-master-security-master-0
security-master-security-master-1
security-master-security-master-2


argo-dev/argo-prod 9
datadir-consul-0
datadir-consul-1
datadir-consul-2
datadir-consul-vault-0
datadir-consul-vault-1
datadir-consul-vault-2
datadir-vault-consulchart-0
datadir-vault-consulchart-1
datadir-vault-consulchart-2


rdpc-dev/rdpc-collab-qa 6

model-tee-app-model-tee-0
datadir-0-kafka-cp-kafka-0
datalogdir-kafka-cp-zookeeper-0
datadir-kafka-cp-zookeeper-0
data-intermediate-song-rdpc-collab-postgres-0
data-song-rdpc-collab-postgres-0


rdpc-dev/rdpc-collab-dev 10

data-management-postgres-postgresql-0
data-management-postgres-0
data-registry-postgres-0
data-wfg-rabbit-rabbitmq-0
model-tee-app-model-tee-0
data-postgres-test-0
data-intermediate-song-test-postgres-0
data-song-test-postgres-0
data-intermediate-song-rdpc-collab-postgres-0
data-song-rdpc-collab-postgres-0
