### ISSUE TITLE
Investigate Molecular Data Aggregation: Charts

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#717]
We know the data format that we need for input into the molecular charts:

https://wiki.oicr.on.ca/pages/viewpage.action?spaceKey=icgcargotech&title=Program+Dashboard+Page+Specs#ProgramDashboardPageSpecs-2.5ChartDataFormat

## Expected Outcome 
- [x] Meet with Alex and review the review the requirements for what data we need counted, and the format we need it delivered in 
- [x] Decision on where to aggregate this data (will it be from RPDC api, or somewhere else)
- [ ] Prioritize ^ who can work on that

**Comment by samrichca** [comment]
had a meeting, Rosi is updating the wiki & creating tickets.
