### ISSUE TITLE
OCCAMS-GB non-PCAWG WGS data (batch3) ready to import to intermediate-song

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/roadmap#718]
SONG payloads for 108 non-PCAWG WGS donors ready to import to intermediate-song: https://github.com/icgc-argo/argo-meta/tree/master/icgc_song_payloads/OCCAMS-GB/WGS/batch3-wgs-non-pcawg (** These do not have ID rename issues ;) **)

**Comment by rosibaj** [comment]
Feb 16- Asked linda to check, but hte ingress is still not open.  waiting to close until verified.

**Comment by rosibaj** [comment]
confirmed and data has begun processing in the RDPC
