### ISSUE TITLE
Provision Covid portal infrastructure

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#745]
- [x] No Network Policies 
- [x] Create a new org + private repository with the infra values to deploy as Terraform setup:
- ego
- song
- score
- arranger
- maestro
- kafka
- dms-ui
- [x] Create the helm values to deploy:
- ego
- song
- score
- arranger
- maestro
- kafka
- dms-ui
- [x] One Jenkins job to manually provision the deployment of the applications 

## Expected Behavior 
- Rosi can submit and publish and analysis and see it on the covid platform.

**Comment by akachru-github** [comment]
- Re: "No Network Policies" - We will still need to put in default policies. We won't create custom netpols.

**Comment by andricDu** [comment]
Jenkins job wired up. Terraform updated. Portal in prod.

**Comment by andricDu** [comment]
@rosibaj i'm ready to close this, but leaving it here if you want one more look.

**Comment by rosibaj** [comment]
@andricDu i saw the portal working! id just like to make sure Justin can deploy now then i will close!
