### ISSUE TITLE
Investigate Keycloak + Ego

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#747]
- [x] Keycloak as an OIDC ID Provider 
- [x] spin up keycloak; register an application 
- [x] maybe add support in ego to use a generic OAUTH2.0 provider 
- [x] login to ego with an account created in keycloak

**Comment by andricDu** [comment]
https://github.com/overture-stack/ego-ui/pull/146
https://github.com/overture-stack/ego/pull/582

Functionality added to Ego and Ego-UI.

Default behaviour of Ego-UI is the same, when Keycloak is enabled, it modifies the login screen slightly.

**Comment by andricDu** [comment]
Keycloak and updated Ego deployed to Overture QA

**Comment by rosibaj** [comment]
I tested this on the Cancogen ENV
- was able to register under my institutional email (rosita.bajari@oicr.on.ca) 
- was able to open incognito browser and successfully login with the newly made account.
