### ISSUE TITLE
ICGC 25k - Investigate remaining blade server for decommissioning

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/roadmap#748]
- The next IT maintenance window is April 16 starting at noon (since electrical work will be done as a part of this window). 
- IT is not sure that the blade server will be able to start back up
- We will need to investigate our remaining services being hosted on the blade and determine whether they can be shut down or whether they need to be migrated. 

Miki let us know from their wiki that the following services are running: 
MongoDB
Key/Value NoSQL database.

Two instances:
Cluster for Submissions Site - stores metadata, verification results, schema
- hmongodb1-dcc (hcn-116)
- hmongodb2-dcc (hcn-117)
- hmongodb3-dcc (hnn2-dcc, arbiter only)

ETL Pipeline
- hmon
- godb-etl-dcc

root@hcn-116:~# mongo admin -u admin -p
MongoDB shell version: 2.4.1
Enter password:
connecting to: admin
rs1:PRIMARY> show dbs
$SERVER (empty)
admin   0.203125GB
dcc-download    3.9521484375GB
dcc-metadata    0.953125GB
dcc-metadata-151217-bak 0.203125GB
icgc    0.953125GB
icgc-140303-2-bak       0.203125GB
icgc-140303-bak 0.203125GB
icgc-140311-bak 0.203125GB
icgc-151217-bak 0.453125GB
local   130.0146484375GB
test    (empty)
rs1:PRIMARY>
 
PostgreSQL
Traditional RDBMS.
Stores user data for Portal Site (e.g. Analysis results).
Runs on hpgdb-etl (aka hmongodb2-dcc, hcn-117).

**Comment by andricDu** [comment]
I can confirm, both the psql and mongodb databses need to be migrated to something more robust. They are in use by production systems.

**Comment by andricDu** [comment]
Email sent to IT for further coordination.
