### ISSUE TITLE
Overture.bio routing 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#750]
DNS in AWS; verify www alias/.routing

**Comment by joneubank** [comment]
Issue is found to be on Netlify, trouble with their load balancer. Tracking their status can be done here: https://www.netlifystatus.com/

Netlify has stated they know of the issue and a fix is underway, they place the blame on one of their providers.

No action is required from us to fix. We should monitor this issue and if it persists we have options for restoring access.

Some interesting findings from the overture.bio DNS config:
 - `www.overture.bio` has a CNAME record to the netlify.com site URL
 - `overture.bio` has an A record to the netlify load balancer IP

I have no explanation for why these are different.

**Comment by rosibaj** [comment]
Clsoing this as netlify is now back up and running; issues are resolved.
