### ISSUE TITLE
Upgrade Ego chart 3.0.0 & Upgrade to Ego 3.6.1

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#759]
- Have a new version to Ego 4.4.1 
- Migrate the ARGO environments to the latest chart 3.0.0 + new db chart + data migrations
- Test and make sure Ego has no issues with 4.411

Notes: 
- Will require Ego downtime 
- coordinate with the RDPC team for production env
- Targeting April13th Tuesday for the dev K8s upgrade 

# Environments 
- [x] dev
- [x] qa
- [x] staging
- [x] production

**Comment by blabadi** [comment]
Migration documentation: https://wiki.oicr.on.ca/display/icgcargotech/Ego+migration
