### ISSUE TITLE
Audit logs rejected by elasticsearch

### ISSUE THREAD

**Issue by henro001** [icgc-argo/roadmap#760]
Audit logs from all master nodes are forwarded to elasticsearch but intermittently  get rejected by ES and the sending no longer works until fluentd restarted

effects two envs:
- RDPC DEV
- RDPC PROD
- VIRUSSEQ PROD

Looks to be a result of the number of fields and the field mapping.

---

Proper fix - upgrade the chart

Workaround - update liveness probe to match latest chart values

https://github.com/OICR/argo-infra/pull/809

**Comment by akachru-github** [comment]
This is hard to reproduce. We revisit this as it comes up. Majority of the logs work, just Audit requires Fluentd restart. This only affects the RDPC cluster.

**Comment by akachru-github** [comment]
Attempts are being made to resolve this, but feedback takes a few days at a time. Will keep this ticket open.

**Comment by akachru-github** [comment]
@henro001 , just wondering if we learned any more about this? If there is no issue right now, we can close this.

**Comment by puneet-oicr** [comment]
Irrelevant now. Closing the ticket
