### ISSUE TITLE
Data Release 3.0

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#763]
Epic for Bioinfo QA on release: https://github.com/icgc-argo/roadmap/issues/756
QC tickets: https://github.com/icgc-argo/workflow-roadmap/issues/112 
https://wiki.oicr.on.ca/display/icgcargotech/Files+Data+Release

**Comment by rosibaj** [comment]
**in progress not complete yet**
- [x] Exclude anything with `firstPublishedAt > May 04, 20201`
- [x] Exclude any data from this donor list: 

``` 
DO35226
DO35158
DO224624
DO52372
DO52374
DO234005
DO231493
DO231311
```

- [x] Exclude this data from the OCCAMS-GB program

|Donor|Status|Note|Action|
|-----|-----|-----|-----|
DO234165;DO50319|Missing Normal Aln| 2 donors|Exclude donors
[92_donors.txt](https://github.com/icgc-argo/workflow-roadmap/files/6423282/92_donors.txt) |Missing Sanger| 92 donors|Exclude donors
[51_donors.txt](https://github.com/icgc-argo/workflow-roadmap/files/6423283/51_donors.txt) |Missing both Sanger and Mutect2| 51 donors|Exclude donors
DO234327|Missing both Sanger and Mutect2 for tumour sample SA130945; Missing Sanger for tumour sample SA130946|  |Exclude donors
DO234150 [analysis_ids_for_excludedSampleId.txt](https://github.com/icgc-argo/workflow-roadmap/files/6424068/analysis_ids_for_excludedSampleId.txt)|Missing Sanger for tumour samples SA596951 and SA596942| donor is in the release as it has another full datasets|Exclude tumour samples
DO234328 [analysis_ids_for_excludedSampleId.txt](https://github.com/icgc-argo/workflow-roadmap/files/6424068/analysis_ids_for_excludedSampleId.txt)|Missing Sanger for tumour sample SA130952| donor is in the release as it has another full datasets|Exclude tumour samples
DO234444 [analysis_ids_for_excludedSampleId.txt](https://github.com/icgc-argo/workflow-roadmap/files/6424068/analysis_ids_for_excludedSampleId.txt)|Missing Sanger for tumour sample SA594885| donor is in the release as it has another full datasets|Exclude tumour samples
[25_donors.txt](https://github.com/icgc-argo/workflow-roadmap/files/6423284/25_donors.txt) |Missing both Normal and Tumour Aln;Raw data only exist in Intermediate SONG| 25 donors|Exclude donors
DO234180;DO10859;DO10842|Info only exist in Clinical, No data in SONG| 3 donors|Exclude donors

**Comment by joneubank** [comment]
Latest data retrieved from RDPC Collab Song and placed into index `file_centric_release_3.0` .

Original Counts of files:
```
{
      "key" : "OCCAMS-GB",
      "doc_count" : 10129
    },
    {
      "key" : "PACA-CA",
      "doc_count" : 6294
    },
    {
      "key" : "PTC-SA",
      "doc_count" : 5536
    },
    {
      "key" : "LUCA-KR",
      "doc_count" : 3939
    }
```

Excluding any files generated after EOD May 4, 2021:
```
{
      "key" : "OCCAMS-GB",
      "doc_count" : 10063
    },
    {
      "key" : "PACA-CA",
      "doc_count" : 6294
    },
    {
      "key" : "PTC-SA",
      "doc_count" : 5536
    },
    {
      "key" : "LUCA-KR",
      "doc_count" : 3939
    }
```

Excluding all other files specified in the exclusion list:
```
{
      "key" : "OCCAMS-GB",
      "doc_count" : 7995
    },
    {
      "key" : "PACA-CA",
      "doc_count" : 6279
    },
    {
      "key" : "PTC-SA",
      "doc_count" : 5499
    },
    {
      "key" : "LUCA-KR",
      "doc_count" : 3924
    }
```
    
Next step is to backup this index and copy it to staging for validation.

**Comment by lindaxiang** [comment]
Summary of data to exclude this data from the PACA-CA program



Donor | Status | Issue | Note | Action
-- | -- | -- | -- | --
DO35226 | Has two WGS Tumour Alns but not WGS Normal Aln | | Has data in Current Release. The same donor has WXS data | [DO35226.wgs.exclude_analysisId.txt](https://github.com/icgc-argo/workflow-roadmap/files/6435495/DO35226.wgs.exclude_analysisId.txt)
DO35140 | Has two Tumour Alns but missing Normal Aln | | The same donor has WGS data. WXS share one same tumour sample with WGS| [DO35140.wxs.exclude_analysisId.txt](https://github.com/icgc-argo/workflow-roadmap/files/6435504/DO35140.wxs.exclude_analysisId.txt)
DO35158 | Missing Sanger and Mutect2 | https://github.com/icgc-argo/workflow-roadmap/issues/94 | |Exclude donor

## Action Items  

- [ ] DO35226 has a good WXS dataset that can be released'; we do NOT want exclude the donor. ONLY exclude the files relating to these 4 analysis ids:
  - [DO35226.wgs.exclude_analysisId.txt](https://github.com/icgc-argo/workflow-roadmap/files/6435495/DO35226.wgs.exclude_analysisId.txt)
  - this should be 21 files 

- [ ] DO35140 has a good WGS dataset that can be released. we do not want to exclude the donor, but we do want to exclude the incomplete WXS pipeline. 
  - [DO35140.wxs.exclude_analysisId.txt](https://github.com/icgc-argo/workflow-roadmap/files/6435504/DO35140.wxs.exclude_analysisId.txt)
  - This should be 10 files 

- [x] Exclude all files from all analyses from these donors from OCCAMS-GB program; they are all missing a complete DNA Seq pipeline (either missing normal or one wf)
```
DO234165
DO50319
DO234327
```

**Comment by rosibaj** [comment]
This has been confirmed on production and was released May 10, 2021
