### ISSUE TITLE
Login, Permissions and Routes

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#767]
Login permissions and routes - **this may need some revisions**

1. **DACO Applicant Dashboard** 
URL: daco.icgc-argo.org/applications/ 
(DACO ADMIN and APPLICANT see different displays on their dashboards)
Scope: DACO-APPLICATION.WRITE 

2. **DACO Admin Dashboard** 
URL: daco.icgc-argo.org/applications/
Scope: DACO-SERVICE.WRITE  
Scope: DACO-REVIEW.WRITE

3. **Application Page** 
URL: daco.icgc-argo.org/applications/{APP-ID}

Needs permission scope defined in EGO (proposal above tbd)

**Comment by anncatton** [comment]
Issue moved to [icgc-argo/dac-ui #3](https://github.com/icgc-argo/dac-ui/issues/3) via [**ZenHub**](https://www.zenhub.com/)
