### ISSUE TITLE
Azure Setup 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#773]

**Comment by andricDu** [comment]
Validated song/score uploads and downloads:
![azure_policies.png](https://images.zenhubusercontent.com/59ccfffeb0222d5de4797e77/970c9449-eb3d-403a-9375-98c3ba671714)
![container.png](https://images.zenhubusercontent.com/59ccfffeb0222d5de4797e77/805103ee-74aa-4eb5-8594-3eae834aa4a3)
![upload.png](https://images.zenhubusercontent.com/59ccfffeb0222d5de4797e77/180e8b63-c38d-41ab-8e41-7bcad693dc63)
![download.png](https://images.zenhubusercontent.com/59ccfffeb0222d5de4797e77/a5665e8a-c1bf-4cb5-a12a-9b73364be4b3)

**Comment by andricDu** [comment]
Continuing work here: https://github.com/icgc-argo/azure-infra
