### ISSUE TITLE
ICGC 25K Technical Debt - Parent POM Mega Issue

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#776]
- Fix Dependency Management 
  - parent pom is really old can has a lot of items that are not needed
  - Spring made changes to the maven repos; we were using the internal repos that have been made private
  - the Jenkins servers cant build the services
  - to modify teh dependencies, you have to modify the parent pom
  - Then need to update the Postegres version, and fix the JDBC version
  - Maven plugins (ex enforncer) so the new versions of maven/Java can build in jenkins 
- This work will fix ICGC legacy builds so they can be built off of Dusan's laptop

**Comment by rosibaj** [comment]
need to install Java 8

**Comment by jaserud** [comment]
PR: https://github.com/icgc-dcc/dcc-parent/pull/8

**Comment by jaserud** [comment]
Blocked repo parent pom prs:
- dcc-id: https://github.com/icgc-dcc/dcc-id/pull/22
- dcc-common: https://github.com/icgc-dcc/dcc-common/pull/23
- dcc-download: https://github.com/icgc-dcc/dcc-download/pull/44
- dcc-portal: https://github.com/icgc-dcc/dcc-portal/pull/736
- dcc-repository: https://github.com/icgc-dcc/dcc-repository/pull/41

**Comment by rosibaj** [comment]
- Blocked by OICR Artifactory not updating correctly
- @andricDu is following up to get antifactory unblocked

**Comment by jaserud** [comment]
Parent POM new version is available now: [37](https://artifacts.oicr.on.ca/artifactory/dcc-release/org/icgc/dcc/dcc-parent/37/)
