### ISSUE TITLE
🐛 First login leads to 404 for a user with no program or role - Redirect issue?

### ISSUE THREAD

**Issue by ciaranschutte** [icgc-argo/roadmap#778]

**Comment by ciaranschutte** [comment]
Having trouble recreating this exactly.
Cleaned up some of our routing logic and ensured we're using Next router from our `logged-in` router rather than window assign

**Comment by rosibaj** [comment]
Tested May 18, 2021 9:00 pm

Testing the original scope of this bug, it appears to be working correctly now.  Here is a video showing a success full ogin pre-access, addition of permission by a DCC member, and then successful joining and a redirection: 

https://drive.google.com/file/d/1LihF0C9maLhO3xEbAlK8s_RFqQTqx4pm/view

https://github.com/icgc-argo/platform-ui/issues/1939 was identified in testing, but is not related to this. 

Looks good thank you @ciaranschutte !
