### ISSUE TITLE
Upgrade to Ego 4.x

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#791]
- [ ] Check profile page, token generation. fix bugs if found 
- [x] upgrade in DEV
- [ ] upgrade in QA

**Comment by rosibaj** [comment]
- tests in staging with   KCullion@oicr.on.ca
- test in prod with RBajari@oicr.on.ca

**Comment by anncatton** [comment]
Includes:
- update to ego-token-utils 8.1.1 for platform-ui and platform-api
- update to `o /scopes` and `o/api_key` to reflect ego changes

**Comment by anncatton** [comment]
Service versions in this ticket:
Ego = `4.5.1`
Ego UI = `4.3.0`
Platform UI = `1.97.0`
Platform API = `3.17.0`
Ego-token-utils = `8.1.1`

**Comment by rosibaj** [comment]
deployed to production - confirmed login on all sites.

**Comment by rosibaj** [comment]
- tested in prod with RBajari@oicr.on.ca
- only have the one user, and the email is updated to lowercasing 
- providerid is set to google provider id
