### ISSUE TITLE
Azure deployment to prod 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#803]
Once the domain name is provisioned, then we can go forward with the production environment.

**Comment by andricDu** [comment]
Massive improvements have been made to the terraform and it is now stable. It can be re-run without blowing k8s or having ingress rules be deleted.

**Comment by andricDu** [comment]
However due to permission issues, we are currently blocked by IT until they give us permissions to do the deploy

**Comment by andricDu** [comment]
song.azure.icgc.overture.bio
score.azure.icgc.overture.bio

Follow up tasks:
- backup cron for song
- icgc.org domain names

**Comment by rosibaj** [comment]
Followup: https://github.com/icgc-argo/roadmap/issues/817

@andricDu is this for devops or you?

**Comment by andricDu** [comment]
@rosibaj @akachru-github hopefully devops if they have the capacity

**Comment by rosibaj** [comment]
Waiting for icgc.org to be transferred to us.

**Comment by akachru-github** [comment]
@andricDu, this is complete right? If so, will close!

**Comment by andricDu** [comment]
@akachru-github I have yet to add the new domain (icgc.org) to the ingress controller.

**Comment by andricDu** [comment]
The following domains work:
Song:
song.azure.icgc.org
song.azure.icgc.overture.bio

Score:
score.azure.icgc.org
score.azure.icgc.overture.bio
