### ISSUE TITLE
Deploy Release Management to QA

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#810]
- outline the deploy steps for production 
- [ ] Get all data in files-service from Song, and promote current list to `PUBLIC`  
- [ ] Replicate the existing public index, but with the new fields added in the correct stages
- [ ] Highlight all service dependencies for redeploy
- [ ] Verify the helm/alisas configurations to ensure maestro does not wantonly contribute data to the portal.  API only, no publication. 
- [ ] Swap current `file_centric` index to the new ones from file_service

**Comment by rosibaj** [comment]
@joneubank do we have a list of steps to perform on production release? what/how/when do we need to reindex?

Any services need to be modified or turned on during release?

**Comment by joneubank** [comment]
not right now, can write a SOP in our wiki for this.

**Comment by rosibaj** [comment]
yes please @joneubank - can you paste the wiki link here before i close this?
