### ISSUE TITLE
Pensato updates 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#815]
- [x] Report/write up to present to DACO/Glasgow 
- [x] S3 library is forked; it needs to be added to artifactory to it can be used in future builds 
- [x] Automate build on Jenkins

**Comment by rosibaj** [comment]
Note for testing 
- set up in QA env
- @rosibaj to follow-up and copy/paste the ticket link for UI update
- test some various file sizes to see the Collab latency

**Comment by andricDu** [comment]
s3fs lib has been uploaded to artifactory. The version is `2.3.0-overture`

I will attempt to push it back upstream to the maintainer via pull request at a future date.
