### ISSUE TITLE
Azure Production Followup: backups + domain

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#817]
Follow up tasks:

- backup cron for song
- icgc.org domain names

**Comment by rosibaj** [comment]
@akachru-github can i assign this to devops team?

**Comment by akachru-github** [comment]
Yep. will take this up in our grooming session.

**Comment by akachru-github** [comment]
Created separate ticket for Song backup: https://github.com/icgc-argo/infra-devops-roadmap/issues/56

**Comment by edsu7** [comment]
Will bring up with @justincorrigible . Safe to close?

**Comment by justincorrigible** [comment]
Pending from this ticket:
- Backup is still required, but doesn't need a cron job as the data is permanently "frozen". Automation for this task would be nice (but not sure whether it is strictly necessary).
- Domain work is likely unnecessary as the site will be decommissioned soon.
