### ISSUE TITLE
Fix URL Encoding 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#822]
Daco2Ego cannot revoke data in one instance: 

```
Error: Can't revoke daco access for user '{[SENSITIVE DATA ask @rosibaj for detauils](None)'
 -- LookupError('No matches for [SENSITIVE DATA ask @rosibaj for detauils] from ego endpoint /users ', 
"{'limit': 20, 'offset': 0, 'count': 0, 'resultSet': []}")
```

- URL encoding is the issue.  using the screened email, an encoded url resolved but a non-encoded url does not

- [ ] Make sure all requests are encoded.

**Comment by anncatton** [comment]
Fix: https://github.com/icgc-argo/Daco2Ego/pull/3
