### ISSUE TITLE
Netlify builds using the Trusty build image will fail after September 19

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/roadmap#824]
The Netlify build system maintains multiple build images, which set the environment in which your sites build. One or more of your sites is using the “Trusty” image, built on Ubuntu 14.04 (“Trusty Tahr”). The Trusty image moved into legacy support in 2019, after Ubuntu 14.04 reached end of life.

On September 19, 2021, we will end all support for the Netlify Trusty image. 

We have identified the following impacted sites belonging to your team:

**Legacy: OICR-Softeng:**
hcmi-assets
icgc-dcc

**Softeng-OICR:**
arranger-storybook
overture
oicr-softeng
icgc-dcc-docs
ego-ui
ncigdc

Select a site name above to access specific site settings in the Netlify UI where you can change the site’s build image. For more information about changes between images, how to run a test build, and how to troubleshoot issues with upgrading, please visit the Trusty build image migration guide in the Netlify Support Forums.

As always, we’re here to help! If you have any questions, feel free to reply to this email directly.

TO DO LIST:
**Legacy: OICR-Softeng:**
~hcmi-assets  - DELETE~
~icgc-dcc  - DELETE~

**Softeng-OICR:**
~arranger-storybook  - **DELETE**~
overture  - UPDATE 
oicr-softeng  - UPDATE 
icgc-dcc-docs  - UPDATE 
~ego-ui  - DELETE~
~ncigdc  - DELETE~

**Comment by rosibaj** [comment]
September 07, 2021
- removed hcm-assets
- removed ncigdc
- removed ego-ui
- removed icgc-dcc
- removed arranger-storybook

**Comment by rosibaj** [comment]
discussed with @samrichca - She will look into the update of the `oicr-softeng` site for update.

**Comment by joneubank** [comment]
FYI - https://answers.netlify.com/t/please-read-end-of-support-for-trusty-build-image-everything-you-need-to-know/39004

**Comment by joneubank** [comment]
Setting up preview deploys (not changing what is live) of the sites. We can test the preview deploys using the newer version of ubuntu, and once approved we can publish these and enable auto publishing again.

OICR-SOFTENG: https://613bc7d2bd67ab4c1c0c6967--oicr-softeng.netlify.app/
DCC-DOCS: https://613bca9486acee4d6073b06f--icgc-dcc-docs.netlify.app/

**Comment by joneubank** [comment]
DCC-DOCS cannot be upgraded to the most recent Ubuntu 20.04 because it does not have python 3.5 installed. We could either: upgrade DCC docs to python 3.8, or deploy on Ubuntu 16. The preview link provided uses Ubuntu 16 so that the application doesn't have to be changed.

**Comment by joneubank** [comment]
Overture Requires update to Ruby version. Ideal version would be Ruby 2.7.2, but 2.6.6 would be acceptable. Will follow up on Monday with someone that is familiar with developing this site.

**Comment by samrichca** [comment]
ubuntu 16 build image works for overture.bio

https://6140c43b3e19e57ce09a8ca1--overture.netlify.app/

**Comment by samrichca** [comment]
build is OK. link includes dusan's docs changes.

https://app.netlify.com/sites/overture/deploys/6143988332687c0008461c98

https://deploy-preview-169--overture.netlify.app/

**Comment by rosibaj** [comment]
@samrichca i have checked the overture site.  it looks good we can publish these changes.

**Comment by rosibaj** [comment]
@joneubank DCC docs looks good as well! Can we go ahead and publish those changes as well?

**Comment by joneubank** [comment]
Will make the preview versions live and enable autopublish again.

**Comment by rosibaj** [comment]
@joneubank Softwng also looks good! can we publish as well?

**Comment by joneubank** [comment]
@rosibaj DCC Docs and Softeng Blog are both published and deploy settings returned to original setup (auto publish on build enabled)

**Comment by rosibaj** [comment]
Excellent- thank you @samrichca and @joneubank for the help!

**Comment by samrichca** [comment]
overture.bio is live & auto publishing again too
