### ISSUE TITLE
Update Jenkins flow for updating services in RDPC DEV and QA

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/roadmap#826]
- Cancogen is the template for this. RDPC DEV and QA should follow this model. 
  - two envs for RDPC, so this is a bit different than Cancogen
  - larger number of services

**Comment by jaserud** [comment]
Checked ones have already been merged into dev:
- [x] workflow-management-scheduler: https://github.com/icgc-argo/workflow-management-scheduler/pull/11
- [x] workflow-api: https://github.com/icgc-argo/workflow-api/pull/135
- [x] song-search: https://github.com/icgc-argo/song-search/pull/55
- [x] workflow-management: https://github.com/icgc-argo/workflow-management/pull/171
- [x] workflow-gateway: https://github.com/icgc-argo/workflow-gateway/pull/25
- [x] rdpc-gateway: https://github.com/icgc-argo/rdpc-gateway/pull/74
- [x] workflow-relay: https://github.com/icgc-argo/workflow-relay/pull/123
