### ISSUE TITLE
Design - Workflow Automation: Cleaning up stale / orphaned pods and jobs

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/roadmap#832]
- Cleaning up stale / orphaned pods/jobs with Model Tee 
  - When collab crashes, we are left with inconsistent states. Jobs left hanging
  - When we resume, we rip through these and manually emit a “failed” event into relay to kill these. 
- For automating this, we can create a Bookkeeper / Reaper process
  - Detect the stale jobs since they might appear as “running” since they are in an inconsistent state. This service would migrate these to a system error state
  - Automatically emit “kill” signal. 

- Output of this ticket will be a design wiki.

**Comment by andricDu** [comment]
https://wiki.oicr.on.ca/display/icgcargotech/Workflow+Garbage+Collection
