### ISSUE TITLE
ICGC 25K docs updates: for DACO release on May 16

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/roadmap#834]
There are some content and links that will have to be updated on the ICGC 25 docs site.

I listed some links below, but could help to do a quick search with “DACO”: there may be more than this.

1. Change the links to the DACO website to: `https://daco.icgc-argo.org/`
2. Where DACO procedures are explained, we can remove a lot of this and link to the new DACO docs, which will be here: `https://docs.icgc-argo.org/docs/data-access/daco/applying`
3. Also, if there's anywhere pointing to EGA helpdesk email address, please change from `ega-helpdesk@ebi.ac.uk` to `helpdesk@ega-archive.org`

- https://docs.icgc.org/portal/access/ 
- https://docs.icgc.org/portal/access/#pcawg-data-pan-cancer-analysis-of-whole-genome
- https://docs.icgc.org/download/guide/#authorization - I don't know if this DACO Cloud Access is still a thing???
- We need to remove all of this documentation and point to  the new ARGO docs: https://docs.icgc.org/download/data-access/#the-daco-approval-process (- https://docs.icgc.org/download/data-access/#how-to-apply-for-access-through-daco )
- https://docs.icgc.org/download/downloading-data/#prerequisites_2 
- https://docs.icgc.org/download/repositories/#obtaining-data-access 
- Could add links to this page where reference DACO https://docs.icgc.org/download/data-access/#data-access-control-bodies
- https://docs.icgc.org/download/repositories/#obtaining-data-access 
- https://docs.icgc.org/download/guide/  `Apply for DACO Cloud Access if not already approved Upon approval, login to the Data Portal Generate an Access Token for cloud download - not sure if this is relevant anymore??
`- https://docs.icgc.org/portal/methods/ 
- https://docs.icgc.org/submission/faq/#13-what-does-open-and-controlled-access-mean `(contact DACO link - should this go to platform contact page?)`
- https://docs.icgc.org/portal/access/#analyzed-germline-data 
- https://docs.icgc.org/download/downloading-data/#download-data-instructions `(is all of this relevant still?)`

**Comment by hknahal** [comment]
@kcullion You can preview the changes here: https://6269a67aaab443000a3493e7--icgc-dcc-docs.netlify.app/ The code changes are in this PR: https://github.com/icgc-dcc/dcc-docs/pull/77.

**Comment by kcullion** [comment]
@hknahal @blabadi this PR looks great and I think it's good to go for May 16!

**Comment by b-f-chan** [comment]
Waiting to release with DACO May 16

**Comment by kcullion** [comment]
@hknahal released on May 16 and all looks great, thanks Hardeep!!
