### ISSUE TITLE
ICGC25K Azure transfer - onhold jobs

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/roadmap#836]
**Project**|**#onhold jobs**|**Action**|**Status of regenerated jobs**|**Issue**
:-----:|:-----:|:-----:|:-----:|:-----:
ESAD-UK|16|Regenerate the jobs and add to backlog| 800 complete
LAML-KR|2|Regenerate the jobs and add to backlog| 64 complete
LICA-FR|1|Regenerate the jobs and add to backlog| 49 complete
LINC-JP|346| Regenerate the jobs(20 analysis) and add to backlog| 806 completed, 59 failed
LIRI-JP|36|Regenerate the jobs(20 analysis) and add to backlog | 55 completed, 34 failed
MELA-AU|11|Regenerate the jobs and add to backlog| 525 complete
ORCA-IN|3|Regenerate the jobs and add to backlog| 105 complete
OV-AU|12|Regenerate the jobs(20 analysis) and add to backlog | 28 completed, 1 failed
PACA-AU|15|Regenerate the jobs and add to backlog| 745 backlog | Onholad due to https://github.com/icgc-argo/workflow-roadmap/issues/187
PAEN-AU|8|Regenerate the jobs and add to backlog| 392 regenerated jobs are complete
PAEN-IT|6|Regenerate the jobs and add to backlog| 288 regenerated jobs are complete
PRAD-CA|19|Regenerate the jobs and add to backlog| 915 complete
PRAD-UK|9|Regenerate the jobs and add to backlog| 142 complete, 9 failed, 252 backlog| Onholad due to https://github.com/icgc-argo/workflow-roadmap/issues/190
RECA-EU|25|Regenerate the jobs and add to backlog | 244 complete, 3 failed

**Comment by akachru-github** [comment]
- When regenerating the job, we split the analyses up to try to reduce the number of analysis per job
- This introduced another problem based on overhead wait time, because of Github API rate limiting
- We are working to tweak this to find the right sweet spot.

**Comment by lindaxiang** [comment]
Other than PRAD-UK and PACA-AU, all the other jobs have been regenerated and queued.
