### ISSUE TITLE
QC Staging data for next data release 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#837]
- Staging is up=to-date with all data
- QC the data for next data release (everything except MUTO-INTL)

**Comment by akachru-github** [comment]
Some examples of checks: 
- tumour, normal pair + variant... need complete datasets 
  - partial data may be available and is technically fine, but it's not ready for public release, because donor is still missing some of the analysis. 
- Another aspect of QC is quality of the data that can be part of this QC check. 
- Some of these checks could be automated in the future (automated QC tools)

Practically:
- Using the staging UI to execute these checks. 
- Raw info from the Song server, compare to the UI to ensure things line up.

**Comment by lindaxiang** [comment]
@rosibaj here are the donors/analysis need to be excluded from the data release. 

- [ ] OCCAMS-GB: exclude the following 8 donors 

**Donor**|**Experiment**|**Exclude Reason**
:-----:|:-----:|:-----:
DO234196|WGS|Only Tumour aln
DO234235|WGS|Sanger ASCAT failed: https://github.com/icgc-argo/workflow-roadmap/issues/144
DO234197|WGS|Sanger ASCAT failed: https://github.com/icgc-argo/workflow-roadmap/issues/145
DO234216|WGS|Sanger ASCAT failed: https://github.com/icgc-argo/workflow-roadmap/issues/146
DO50319|WGS|Only Tumour aln
DO234427|WGS|Sanger ASCAT failed: https://github.com/icgc-argo/workflow-roadmap/issues/146
DO234206|WGS|Only Normal aln
DO234201|WGS|Only Normal aln

- [ ] PACA-CA 

Donor | Experiment| Status | Note | Action
-- | -- | -- | -- | --
DO35226 | WGS| Only Tumour Aln | The same donor has WXS data | **Exclude analysis**. [DO35226.wgs.exclude_analysisId.txt](https://github.com/icgc-argo/workflow-roadmap/files/6435495/DO35226.wgs.exclude_analysisId.txt)
DO35140 | WXS | Only Tumour Aln | The same donor has WGS data. WXS share one same tumour sample with WGS| **Exclude analysis** [DO35140.wxs.exclude_analysisId.txt](https://github.com/icgc-argo/workflow-roadmap/files/6435504/DO35140.wxs.exclude_analysisId.txt)
DO35158 | WXS | Missing Sanger and Mutect2 | Data issue: https://github.com/icgc-argo/workflow-roadmap/issues/94 | **Exclude donor**


- [ ] PTC-SA Exclude the following donors

**Donor**|**Status**|**Note**
:-----:|:-----:|:-----:
DO234005|Missing Sanger|Data issue: https://github.com/icgc-argo/workflow-roadmap/issues/95
DO231493|Missing Sanger and Mutect2| Data issue: https://github.com/icgc-argo/workflow-roadmap/issues/29
DO231311|Missing Sanger and Mutect2| Data issue: https://github.com/icgc-argo/workflow-roadmap/issues/29

- [ ] APGI-AU: exclude the following 2 donors

**Donor**|**Experiment**|**Exclude Reason**
:-----:|:-----:|:-----:
DO32887|WXS|Only Tumour aln
DO49123|WXS|Only Tumour aln

**Comment by rosibaj** [comment]
Excellent - i checked all of these linda and it looks good.  

I see that some of the exclude are missing raw reads and may need additional import from legacy song.  
@lindaxiang  Do we yet have tickets to deal with all of these issues?

**Comment by rosibaj** [comment]
@lindaxiang the above has been confirmed and Data Release 4.0 is live with these results.
