### ISSUE TITLE
Create a repo with our custom graalvm Dockerfile

### ISSUE THREAD

**Issue by jaserud** [icgc-argo/roadmap#838]
- currently this images exists in docker hub: https://hub.docker.com/r/icgcargo/graalvm/tags?page=1&ordering=last_updated
- the docker file is available here: https://github.com/andricDu/graalvm-docker-image
- we should make this follow our ci/cd flow to deploy 
- maybe move it to github packages

**Comment by lepsalex** [comment]
**New repo here:** https://github.com/icgc-argo/graalvm-docker-image/

**Docker container in GitHub package registry:** https://github.com/icgc-argo/graalvm-docker-image/pkgs/container/graalvm-docker-image

**CI/CD:** just using a simple GitHub Action that will build, tag, and push a docker image whenever a tag is pushed to the repo, labeling it with that tag - https://github.com/icgc-argo/graalvm-docker-image/blob/main/.github/workflows/docker-create-publish.yml
