### ISSUE TITLE
Upgrade ARGO Platform to Maestro 4.0.0 

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/roadmap#849]
includes: 
- https://github.com/overture-stack/maestro/issues/167
- https://github.com/overture-stack/maestro/issues/212
- https://github.com/overture-stack/maestro/issues/222
- https://github.com/overture-stack/maestro/pull/230

**Comment by b-f-chan** [comment]
Added #731 since #167 is blocked/dependent on it

**Comment by Buwujiu** [comment]
Version 3.11.0 also includes this ticket: https://github.com/overture-stack/maestro/issues/222

**Comment by akachru-github** [comment]
I think this will need to be changed to v3.12.0 now that this is deployed into prod on the RDPC side of things.

**Comment by akachru-github** [comment]
New version: 4.0.

**Comment by b-f-chan** [comment]
@Buwujiu - Please list breaking change for @blabadi to do upgrade
