### ISSUE TITLE
Enforcing clinical data completion before indexing files

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/roadmap#860]
- Right now, we document that ARGO requires full completion of core clinical data before molecular data is made available
  - Technically, we do not enforce this right now. This ticket is about supporting this enforcement. 

Rules:
- flag to every file which indicates whether the file can be included in the index even if does not meet the clinical reqs (the allowlist / exception list)
  - everything in currently in the index needs to be set to this "allowed" state
- Every new file (once the above change is done) that is added will not be included on this exception / allow list
- modify file manager when processing update to a file, that it will need to check the allowlist flag + core completion status before changing the file state. 

Corner case:
- If clinical WAS complete but was made invalid due to a schema update, we will need to discuss this case further.

**Comment by akachru-github** [comment]
Dependency on reading the clinical data. This needs to be done, but will be done when the data is available.

**Comment by Buwujiu** [comment]
Was done under file service PR 135
