### ISSUE TITLE
Donor centric index design

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/roadmap#864]
- Do we restructure what we hav now as file-service to handle this, or is this a new thing altogether?

**Comment by joneubank** [comment]
https://wiki.oicr.on.ca/display/icgcargotech/Implementing+Donor+Centric+Data

**Comment by joneubank** [comment]
Wiki linked in previous comment details a plan to restructure the file manager into a combined Data Indexer, including some major refactor and modification to our system. Notably, this should include combining the Donor Submission Aggregator into the same service.

As a lower effort approach, we could just continue with our system as is and add the new funcitonality into the file manager, but long term I think this restructure will benefit the team. Especially looking at the nightmares of maintaining ICGC 25k nowadays, this type of simplification and opportunity for code maintenance would be very valuable.
