### ISSUE TITLE
Design: How to handle files that are currently published that do not meet clinical requirements?

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/roadmap#865]
- We should have some kind of property that allows us to ignore the clinical requirement. ICGC25k data exists in this state. 
- Donor entity page won't have any info for files that fall into this category. 
- Almost all the files that exist now will need this property / flag
  - Maybe need a "reason" as well. 
- Will need to have a conversation with stakeholders on go forward plan. 

Wiki will be generated to describe our approach to flagging these files. This will be required to ongoing development, as we will need to tell that they will be exempt from the clinical data requirement.

**Comment by joneubank** [comment]
https://wiki.oicr.on.ca/display/icgcargotech/File+Indexing+and+Clinical+Completeness
