### ISSUE TITLE
RNA-Seq: BA requirements, specs, implementation plan

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/roadmap#867]
## Goal

To spec out the addition of the RNA-seq raw reads and workflows into the platform UI (program dashboard). 

After our meeting about the molecular chart/table for DNA workflows (program dashboard), I think it's best that we get some requirements decided on before starting the implementation. 

## Current State

- The RNA additions have been worked into the design, but may need some updates if you discover new requirements
- Zeplin mocks: https://zpl.io/299rxRB
- **NOTE ABOUT MOCKUPS**: there are some things that have been worked in that aren't implemented, and relate to future features (like the program actions card). Just ignore those.
Also - the chart legend just shows 3 workflows checked off - this is just to make the design easier. By default the chart would show all lines checked off as it does now.
- An epic has been created and some tickets were made (working off the addition for Open access filtering), but more tickets may be needed (especially for the API), and these tickets may need to be updated.
https://github.com/icgc-argo/roadmap/issues/868

## To investigate
- [ ] This table is populated with donors when samples are registered for them...the counts go into the "samples" column. Is there a correlation between the DNA Raw Reads column and the Sample column that will need to be changed for the RNA-seq  raw reads column? 
![image](https://user-images.githubusercontent.com/18424138/151202569-0ea51292-4089-460d-b4ac-1f3e0f2c0b59.png)
- [ ] We found out from Linda that a submitter is not required to have a tumour/normal pair (as they are with the DNA raw reads). How will this affect the dashboard table and chart. E.g. does the current raw reads filter apply to this new RNA column? 
![image](https://user-images.githubusercontent.com/18424138/151202987-91ff7d72-9857-4ef7-a35b-f41f2cabdf4a.png)
- [ ] How will the chart plots for RNA be different than DNA because of the above (tumour/normal pair not required)
![image](https://user-images.githubusercontent.com/18424138/151223194-ad988717-1c0d-4d49-954f-6405b051da88.png)

## To do
- [ ] Work with Linda to understand the requirements and nuances of the RNA-seq workflows 
- [ ] Update this wiki page with what's needed for RNA-seq data inclusion to the Donor table and Molecular Chart: https://wiki.oicr.on.ca/pages/viewpage.action?spaceKey=icgcargotech&title=Program+Dashboard+Page+Specs
- [ ] Review the epic and update the tickets needed for this
- [ ] Let Kim know if there are any UI/design changes needed

**Comment by akachru-github** [comment]
Let's keep this ticket open as there are a few more things to discuss around the spec before we have a complete picture of the impact of including the RNA workflow.
