### ISSUE TITLE
Upgrade ARGO to Ego 5.3.0

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/roadmap#872]
Change

**Comment by blabadi** [comment]
updated title to 5.3.0 since there is a fix needed : https://github.com/overture-stack/ego/pull/635

**Comment by blabadi** [comment]
Confirmed no issues in RDPC by running workflow which covers using app credentials
also submission to song score  

what's left to confirm is the invite user flow issue investigation  https://github.com/icgc-argo/platform-ui/issues/2215
