### ISSUE TITLE
Increase Timeout in RDPC dev/qa Maestro to allow indexing

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/roadmap#874]
## The issue
RDPC Maestro currently is unable to index large studies such as PACA-CA and TEST-PR due to the timeout issue. This is causing platform donor dashboard reporting outdated data. 

## Solution
The proper fix would be updating Maestro to use the paginated song get analysis endpoint, this endpoint has upgraded performance which will solve the timeout issue.

As a temporary solution, increasing maestro timeout threshold should be sufficient to allow index song.

**Comment by akachru-github** [comment]
@Buwujiu I think this change was made in RDPC prod right? We can close this.
