### ISSUE TITLE
🐛 TEST-QA raw reads and alignment should both plot 4 donors on the chart

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/roadmap#875]
## Describe the bug
On QA there are 4 donors that have matched T/N pairs and those same donors have at least one completed alignment runs. But the chart looks like there are a different amount of donors for those two plots.
![image](https://user-images.githubusercontent.com/18424138/152829842-7344154c-82bd-4713-9547-7cfc0de4b0f4.png)

## Steps To Reproduce

Steps to reproduce the behaviour:
1. Go to the program Dashboard for TEST-QA and compare table and chart

## Expected behaviour
I would expect that those lines both reach the same point on the graph at 4 donors

**Comment by kcullion** [comment]
@Buwujiu @lindaxiang is this still a bug, or did we say TEST-QA has a lot of garbage data?

**Comment by lindaxiang** [comment]
@kcullion it looks correct now. :-)

**Comment by kcullion** [comment]
Thanks @lindaxiang 
Closing now as this is not a bug anymore
