### ISSUE TITLE
Program Dashbaord errors in Staging for the Huntress Release

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/roadmap#876]
- Errors do not appear in QA, just in STAGING.
- Currently blocking the Huntress release
![image (24).png](https://images.zenhubusercontent.com/5d55b1b74d335f147c3e6dc0/29c40360-1ecb-4002-bdd7-39ab346f4fb6)

**Comment by kcullion** [comment]
this was fixed by clicking some buttons :)
