### ISSUE TITLE
Cross-site scripting audit: ICGC ARGO platform

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/roadmap#882]
- Investigate options for performing a pen-test. 
- There will be a ramp up here as research will need to be done to identify the best way to determine if we are vulnerable. 
  - Veracode an option? Can reach out to IT to see what they have done in the past for OICR. 
- Wikis with tables and diagrams and stuff.

**Comment by b-f-chan** [comment]
Doing pen-test now may be counterproductive given major changes coming to EGO

However, if just research to prepare ourselves, this would be useful

**Comment by b-f-chan** [comment]
Sam did research this, to update Wiki with notes on her progress/findings, then close

**Comment by samrichca** [comment]
Added a page to the wiki about XSS/CSRF, closing.
