### ISSUE TITLE
Program dashboard in PROD does not get updated when raw data was submitted and job is kicked off and completed

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/roadmap#883]
For project `TEST-INTL` in Prod:
Raw WXS data submissions:
Normal: https://submission-song.rdpc.cancercollaboratory.org/studies/TEST-INTL/analysis/9e1a98a4-069c-4bc5-9a98-a4069c8bc55d
Tumour: https://submission-song.rdpc.cancercollaboratory.org/studies/TEST-INTL/analysis/5457ab5b-1b5a-4a5f-97ab-5b1b5a0a5fa3

Completed alignment WXS:
https://song.rdpc.cancercollaboratory.org/studies/TEST-INTL/analysis/912473d1-2db0-4afd-a473-d12db0bafd85
runId: wes-797de988b2e74a2daccb9b9e0a8b95c1

Program dashboard: https://platform.icgc-argo.org/submission/program/TEST-INTL/dashboard

![Screen Shot 2022-02-24 at 1 47 11 PM](https://user-images.githubusercontent.com/7522294/155588025-c9aa946d-79bc-4d9a-8c13-135ac79f3c78.png)

Expected:
Raw Reads: 1N 1T
Alignment: 1(green bar)

**Comment by b-f-chan** [comment]
@lindaxiang - Re-test/re-run, if still happening, @Buwujiu can take a look after RNA-Seq work (before security alert stuff)

**Comment by b-f-chan** [comment]
Assigning to @Buwujiu since she is investigating related ticket:
https://github.com/icgc-argo/argo-clinical/issues/775

**Comment by kcullion** [comment]
related to the raw data submisison..I tested registering a donor in QA for KIMC-CA and then submitting some clinical files for that donor. The dashboard updated after about 30 seconds, as expected without me needing to press the sync button or refresh. Thanks @Buwujiu !
@lindaxiang and team can test the molecular submission :)

**Comment by b-f-chan** [comment]
@edsu7 actually tested this with a workflow run and data is showing up correctly --> Moving to Release
