### ISSUE TITLE
Import APGI-AU ICGC25K RNA-Seq data to intermediate-song

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/roadmap#894]
@hknahal commented on [Mon Apr 04 2022](https://github.com/icgc-argo/argo-meta/issues/42)

The following SONG payloads are ready to be imported to intermediate-song:  
https://github.com/icgc-argo/argo-meta/tree/master/icgc_song_payloads/APGI-AU/RNA-Seq/batch1 
- The ARGO project code is `APGI-AU` (was called `PACA-AU` in ICGC25K)

https://wiki.oicr.on.ca/display/icgcargotech/Initializing+the+ICGC+dataset+in+ARGO+Clinical
https://wiki.oicr.on.ca/display/icgcargotech/Importing+Legacy+ICGC+objects+into+Intermediate-Song

**Comment by b-f-chan** [comment]
Priority 3 for @joneubank this sprint; to check if can offload this task to anyone else in future

**Comment by b-f-chan** [comment]
Push another sprint, no immediate need

**Comment by b-f-chan** [comment]
@joneubank to consider others who can support this type of task in future as he goes through the process

**Comment by joneubank** [comment]
Report for uploaded data: https://github.com/icgc-argo/argo-meta/commit/af4eb547c0e8d347b40487882472e141ea150cfd

**Comment by joneubank** [comment]
@b-f-chan 
For a user to perform this task in the future they need:
* Kubernetes access to Argo RDPC (all clusters including prod)
* ssh access to the legacy song server in cancercollab
* legacy ego api key with `collab.WRITE` permission (can be setup in ego)

None of the steps are particularly technical, it's about trust in manipulating production data and confidence in following all steps and troubleshooting errors as they come up.  That leaves us with several candidates on our team, such as Justin, Bashar, Henro, Yelizar. Any dev doing backend work involving the clinical data, indexing services, or song/score may also be interested , so Rakesh and Dan are in mind as well as they get more familiarity with Argo.

**Comment by Buwujiu** [comment]
Confirmed with @lindaxiang that this ticket is done.

**Comment by b-f-chan** [comment]
Thanks @Buwujiu - @lindaxiang will still need to run some jobs in QA RDPC once Collab is back up, as a final sanity check

**Comment by b-f-chan** [comment]
Closing, @lindaxiang or @Buwujiu to create separate ticket to finish the sanity testing
