### ISSUE TITLE
Requirements generation for Clinical Exceptions

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/roadmap#895]
Expected outcomes:

- [x] Spec with user stories complete: https://wiki.oicr.on.ca/display/icgcargotech/Core+Clinical+Data+Exceptions
- [x] Exceptions list complete and signed off by stakeholders (ARGO clinical working group): https://docs.google.com/spreadsheets/d/1RVSojKGfxZauP4Y38fkhCznDQKlxe3rk/edit#gid=1162714021

**Comment by hknahal** [comment]
Wiki page: https://wiki.oicr.on.ca/display/icgcargotech/Core+Clinical+Data+Exceptions

**Comment by hknahal** [comment]
- Wiki page: https://wiki.oicr.on.ca/display/icgcargotech/Core+Clinical+Data+Exceptions
- GoogleDoc table of draft list of core clinical fields indicating whether exceptions can be allowed or not: https://docs.google.com/spreadsheets/d/1RVSojKGfxZauP4Y38fkhCznDQKlxe3rk/edit?usp=sharing&ouid=114256323068113275795&rtpof=true&sd=true

**Comment by Buwujiu** [comment]
Closing this, no longer needed as requirements are complete.
