### ISSUE TITLE
Create Standardized Test Program for DEV & QA

### ISSUE THREAD

**Issue by b-f-chan** [icgc-argo/roadmap#904]
Create a standardized test program with happy day scenario data for that is consistent for both Dev & QA environments, that Devs, BAs, and Bioinfo can all make use of.
 
**Criteria:**

- [x] The program (DATA-CA) should have data for all dictionary entities to the extent possible
- [x] The data should be consistent between Dev and QA
- [x] There should be a large enough amount of data to test UI features such as pagination, table scroll, downloads, etc

## For testing Submitted Data section
@hknahal when you add more data in DEV for the new DATA-CA program we made, can you please try to do the submission in pieces and test these items in the submitted data section? 

- Make sure all of the correct file types are loading in for each donor when you submit them
-  If a donor does not have a data file submitted, make sure the tab is disabled

**Comment by Buwujiu** [comment]
Test program `DATA-CA` is created in dev, next step is to create the test clinical submission files for DATA-CA on Dev.

**Comment by b-f-chan** [comment]
Scope of this ticket is JUST clinical

@Buwujiu create separate ticket for standardized testing data for molecular data (USE SAME TEST PROGRAM YO!)

**Comment by b-f-chan** [comment]
@edsu7 to assist with some of the sample data generation - Thanks Edmund!  @hknahal to give template + guidance

**Comment by edsu7** [comment]
Google drive with mock data:
https://drive.google.com/drive/folders/1oghz5COEF_7vARDJN-mtHkKk6hZPbDL4?usp=sharing

**Comment by kcullion** [comment]
@edsu7 @hknahal can I use these files to upload to the DATA-CA program on QA, once Dan has released his Submitted Data updates to QA? So I can create that program, like Hardeep did in dev.

**Comment by hknahal** [comment]
@kcullion We're still testing these files but we'll let you know as soon as they're ready to use.

**Comment by b-f-chan** [comment]
@edsu7 has sent his part of the data over, @hknahal to give feedback, @edsu7 will make any required fixes

**Comment by b-f-chan** [comment]
All test data from @hknahal and @edsu7 are appended/combined --> ~200 donors

@hknahal will upload Program = DATA-CA

Environments to upload to:

- [ ] DEV
- [ ] QA

**Comment by b-f-chan** [comment]
@b-f-chan to find separate ticket to create test molecular data for these donors (@lindaxiang has created this previously).  Out of scope from this ticket, but related.  Can take that task up separately, but we will only do for a few donors (10? 20?), because creating molecular data for all 200 will be quite onerous.  Have either BAMs or FASTQs, this is just submission data (mimic user data).  Idea is that we would run this standard test data through all our pipelines now and in future.

**Comment by b-f-chan** [comment]
Data is ready!  @hknahal to copy files over to TEST program, then it will be ready to use!  Will add some comments then close off

@hknahal to talk to @demariadaniel to add data that creates errors --> Create separate ticket for this

**Comment by hknahal** [comment]
Test clinical data for 370 donors available in `DATA-CA` in both QA and DEV for all clinical files:
QA: https://platform-ui.qa.argo.cancercollaboratory.org/submission/program/DATA-CA/dashboard
DEV: https://platform-ui.dev.argo.cancercollaboratory.org/submission/program/DATA-CA/dashboard
