### ISSUE TITLE
Sanity Test for APGI-AU ICGC25K RNA-Seq

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/roadmap#908]
Sanity test for APGI-AU ICGC25K RNA-Seq to intermediate song, 
Original import ticket is https://github.com/icgc-argo/roadmap/issues/894

**Comment by lindaxiang** [comment]
@Buwujiu The sanity checks have completed and test run in RDPC-QA completed successfully: 
wes-d58a83f3d71d402eb52130b19ea9c8b0, that confirms that data migration for APGI-AU is all good.

**Comment by b-f-chan** [comment]
This is just sanity test, we still need to run this workflow for real in production

**Comment by b-f-chan** [comment]
Closing, waiting for real production run #271
