### ISSUE TITLE
Expand ARGO Kuberntes cluster

### ISSUE THREAD

**Issue by henro001** [icgc-argo/roadmap#91]
ARGO K8S cluster expansion/upgrade

Overview:

Expand K8S worker nodes:
  Current: 5 nodes 10 cpus
  Future: 16 nodes 32 cpus
Upgrade K8S cluster:
  Current: v1.14.1
  Future: v1.15.3

The upgrade is a part of a quarterly maintenance cycle.
Detailed release notes for the new version: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.15.md#kubernetes-v115-release-notes

 Continuous Improvement
 Project sustainability is not just about features. Many SIGs have been working on improving test coverage, ensuring the basics stay reliable, and stability of the core feature set and working on maturing existing features and cleaning up the backlog.

Impact:
Brief interruption of the active connections during the pods failover. The pods will be gracefully migrated to different nodes during the upgrade.

Details:

Use Kubespray to scale and Upgrade. https://github.com/icgc-dcc/k8s. 
The upgrade process is documented here https://wiki.oicr.on.ca/display/icgcargotech/Kubernetes+maintenance

**Comment by rosibaj** [comment]
@henro001 Have these changes been deployed to qa yet?

**Comment by rosibaj** [comment]
Upgrade was completed so closing issue.
