### ISSUE TITLE
Deploy and test all SONG v5.0.1 instances to RDPC dev/qa

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/roadmap#911]
SONG has a major release v5.0.0: https://github.com/overture-stack/SONG/pull/769, as part of dictionary release 1.15, we need to deploy the new version to RDPC dev and qa for testing purposes. 
Note: the latest version is now **v 5.0.1,** which includes a bug fix. 

Environment to Deploy: 
- [ ] RDPC DEV
   - [ ] SONG
   - [ ] intermediate SONG
   - [ ] submission SONG
- [ ] RDPC QA
   - [ ] SONG
   - [ ] intermediate SONG
   - [ ] submission SONG

Environment to test:
- [ ] RDPC DEV
   - [ ] SONG
   - [ ] intermediate SONG
   - [ ] submission SONG
- [ ] RDPC QA
   - [ ] SONG
   - [ ] intermediate SONG
   - [ ] submission SONG

**Comment by b-f-chan** [comment]
@edsu7 - Testing scope from @Buwujiu above

**Comment by b-f-chan** [comment]
@edsu7 - @Buwujiu confirms we only need to. test the 3 song instances in QA

**Comment by b-f-chan** [comment]
@edsu7 tested on QA SONG, Intermediate SONG, Submission SONG - But waiting for analysis to finish publishing (big data set) to complete testing of publish/unpublish/suppression

**Comment by b-f-chan** [comment]
Deploy and testing done, closing
