### ISSUE TITLE
Add an "allow-replace" parameter to the submit (Program Level) Exception endpoint

### ISSUE THREAD

**Issue by ghost** [icgc-argo/roadmap#916]
## Detailed Description
Add an optional boolean parameter `allow replace` to submit endpoint for replacing existing program level exceptions.
Add the following description to parameter :`this will replace any existing exceptions for the program` 

## Expected System behavior
if true - replace existing exceptions
if false - add exceptions if doesn't exist, give an error if the exception exists for a given field.

**Comment by ciaranschutte** [comment]
our decision was to use the endpoint to replace existing exceptions whenever provided instead of modifying. updating swagger for clarity.
