### ISSUE TITLE
Mockup for Dashboard DNA Table Cell Errors

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/roadmap#920]
## Goal
To create mockups for replacing `registered samples` and `raw reads` column tooltips. ![Screen Shot 2022-11-07 at 10.09.27 AM.png](https://images.zenhubusercontent.com/5c9a3377f234b2000189633c/c0b45916-356a-4482-ab0d-6179b7a709a4)

As discussed with Patrick, possible solution is to 
- For the registered samples column: use red background on cells that have missing samples
- For the raw reads column: use normal background with red text when samples don't match or # of raw reads < # samples.
- Add 2 legends to represent these 2 types of errors.

**Comment by patrickdsantos** [comment]
Hello! Here's the link to the updated mock with new legend items:

https://zpl.io/Am0nqX8

@Buwujiu let me know what you think! :)

**Comment by patrickdsantos** [comment]
Updated mocks! 

https://zpl.io/Am0nqX8
