### ISSUE TITLE
Mockup for Admin Approval on Register Samples Page

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/roadmap#921]
## Goal
Create mockups for this feature: https://github.com/icgc-argo/platform-ui/issues/2434
- 1 mockup for update modal
- 1 mockup for updated samples summary page
- Bonus task! Patrick suggested changing the design on sample register page where the upload button may need relocation, as it's not always the first step : ![Screen Shot 2022-11-07 at 10.20.15 AM.png](https://images.zenhubusercontent.com/5c9a3377f234b2000189633c/ae33d6f8-b249-4626-8194-deda4db22776)

**Comment by patrickdsantos** [comment]
Hello! Here are the links to the updated pages:

- https://zpl.io/awOeOLg
- https://zpl.io/7wLe4Yj
- https://zpl.io/5EMxqYJ
- https://zpl.io/2ZXEgAL

@Buwujiu let me know what you think :)

**Comment by Buwujiu** [comment]
Thanks @patrickdsantos ! can you make 1 small change to https://zpl.io/7wLe4Yj ? 
The content of the modal now is 
```
The DCC will be notified of the following updates to previously released data and your submission will be locked until approval.
```
Can you please remove `following`, so it becomes:
```
The DCC will be notified of the updates to previously released data and your submission will be locked until approval.
```

**Comment by patrickdsantos** [comment]
Hey @Buwujiu ! 

Just made the copy change, check it out:
https://zpl.io/7wLe4Yj

Let me know if there's any other updates!
