### ISSUE TITLE
Design Program Entity Page

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/roadmap#925]
## Goal
The next argo feature is to implement a Public facing program entity page, in terms of functionality, the page will be similar to: 
- ICGC 25K:
https://dcc.icgc.org/projects/RECA-EU
- GDC:
https://portal.gdc.cancer.gov/projects/TCGA-UCEC

Please read the specs: https://wiki.oicr.on.ca/display/icgcargotech/Program+Entity+Page

## Exit Criteria
Mockups for program entity page.

**Comment by patrickdsantos** [comment]
Hey @Buwujiu take a look at this mockup and let me know what you think! 
![Overview](https://user-images.githubusercontent.com/116736040/207145639-137a7cff-a880-4e16-9b50-91a9440400ef.png)

**Comment by patrickdsantos** [comment]
Hey @Buwujiu take a look at the updates I made to the mockup :) 
Let me know what you think!
![Overview](https://user-images.githubusercontent.com/116736040/207444671-f1946cd0-9380-4f3a-a13f-79ce3cd15661.png)

**Comment by Buwujiu** [comment]
@patrickdsantos Mockup looks good! got some feedbacks from Linda:
1. move `Total Registered Donors` to the top item in the right top corner
2. in the card: `Donor and File Counts by Data Category`, `Experimental Strategy` is not a category, so please remove it from the mockup.

**Comment by patrickdsantos** [comment]
Hi @Buwujiu here's the new mockup with the changes! Let me know if there's any further updates. Thank you! ✨ 
![ICGC-ARGO_ProgramEntityPage_v3](https://user-images.githubusercontent.com/116736040/210839161-df499e4c-1e03-4104-9e8f-f89f4a70713e.png)

**Comment by patrickdsantos** [comment]
Hello @Buwujiu ! Take a look at the updated mock :)

![ICGC-ARGO_ProgramEntityPage_v3](https://user-images.githubusercontent.com/116736040/210839545-b2f691f5-c927-4f84-9db9-d3369901cf7c.png)

**Comment by Buwujiu** [comment]
@patrickdsantos Looks great! can you please put it on zeplin? thank you!

**Comment by patrickdsantos** [comment]
No problem @Buwujiu here's the link! 

https://zpl.io/5EM0j8o

**Comment by Buwujiu** [comment]
Design complete! Closing ticket.
