### ISSUE TITLE
Issues on Dashboard

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/roadmap#927]
## Issue 1
Page has error after applying `T or N not registered` DNA filter and changing page size to 100. 

How to reproduce:
https://www.screencast.com/t/LWGlpW2jGg0q

## Issue 2
Random "0" on the legend when certain filter is selected:![Screen Shot 2022-12-12 at 12.49.44 PM.png](https://images.zenhubusercontent.com/5c9a3377f234b2000189633c/9fc4c18a-17b8-46b1-85a1-f5f746ca335d)

https://platform-ui.qa.argo.cancercollaboratory.org/submission/program/DATA-CA/dashboard

**Comment by samrichca** [comment]
I can't reproduce the first issue on dev/local so I think it's been fixed in another PR.

**Comment by Buwujiu** [comment]
Can't test because of DATA-CA dashboard showing no data, will test after it's resolved.

**Comment by Buwujiu** [comment]
Tested in QA, issues are fixed!

**Comment by Buwujiu** [comment]
Tested in Prod, working as expected!
