### ISSUE TITLE
Database Backups

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#93]
We need a regular backup and restore methodology for all datasources
- program service
- ego
- song
-  clinical 
- Elasticsearch

Experimenting with snapshots/data-dumps right now 

https://docs.google.com/document/d/1SG9qWWjutr01rYg-bk1Ba1_cnM_g6tMur4WHBmh0_-0/edit?ts=5e593fb0&pli=1

**Comment by rosibaj** [comment]
@akachru-github i had this epic - did you have a different one created for all the backup tasks?

**Comment by akachru-github** [comment]
@rosibaj backups tasks are now split into two epics:

Platform: https://app.zenhub.com/workspaces/argo-mega-board-all-repos-5c8c8637777e5f767e486217/issues/icgc-argo/roadmap/166

RDPC: https://app.zenhub.com/workspaces/argo-mega-board-all-repos-5c8c8637777e5f767e486217/issues/icgc-argo/roadmap/179

**Comment by rosibaj** [comment]
ok will close this!
