### ISSUE TITLE
How to Improve the Donor Dashboard Filter By Adding Applied Filters

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/roadmap#933]
## Description
In the program dashboard, there are multiple filters options on the DNA and RNA tables, if users select a filter in the RNA table and switch back to DNA table, they have no way of knowing the applied filters unless they go back to RNA table. We need to add Applied Filters on the page so that users can know what they selected without needing to switch between tabs. 

## Exit Criteria
- [ ] Design applied filters on the program dashboard
- [ ] Provide a design mockup for the team to review

**Comment by patrickdsantos** [comment]
Hello @Buwujiu ! This was a bit of a challenge to solution but I've come up with a potential fix.

Add a button beside Clear Filters that reads "Show Selected Filters" when the user clicks on this button, a modal will appear revealing all selected filters. 

![Screen Shot 2023-02-08 at 12 13 12 PM](https://user-images.githubusercontent.com/116736040/217605622-a61300f3-047b-4d26-bed3-fdb8feda22ef.png)

![Screen Shot 2023-02-08 at 12 13 22 PM](https://user-images.githubusercontent.com/116736040/217604369-777260d2-a091-42bc-8bb0-eaf51d136669.png)

Let me know what you think!

Thank you!

**Comment by Buwujiu** [comment]
@patrickdsantos I like the deisgn! will make a ticket for implementation, thanks!
