### ISSUE TITLE
Improve Styling - File Entity Page - Associated Specimen and Samples

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/roadmap#934]
## Description 
The current File Entity Page - `Associated Specimen and Samples` section is not properly styled, we need UI design to make the section consistent with the rest of the page. 
![Screen Shot 2023-02-02 at 10.41.03 AM.png](https://images.zenhubusercontent.com/5c9a3377f234b2000189633c/9fde00fe-9ab2-40c0-bfa4-a7c12de6e88a)

Example: https://platform-ui.qa.argo.cancercollaboratory.org/file/FL22481

## Exit Criteria
A complete Mockup for the page.

**Comment by patrickdsantos** [comment]
Hey @Buwujiu take a look at this mock and let me know what you think! 
![ARGO_fileentitypage](https://user-images.githubusercontent.com/116736040/218172903-31a194e8-0b6a-4381-a9bc-7637c5f601a6.png)

**Comment by Buwujiu** [comment]
@patrickdsantos thank you Patrick! The mock looks great! I shall transfer it to a ticket!
