### ISSUE TITLE
Audit LUCA-KR

### ISSUE THREAD

**Issue by edsu7** [icgc-argo/roadmap#954]

**Comment by hknahal** [comment]
Breakdown of 1,571 donors showing in [Program Dashboard](https://platform.icgc-argo.org/submission/program/LUCA-KR/dashboard): 

**156 samples need to removed** at request of program (will be addressed in this ticket: https://github.com/icgc-argo/workflow-roadmap/issues/267): 
https://docs.google.com/spreadsheets/d/1ggshqQS9c40nPizDjxuhEG7hHdyvDCSZ/edit#gid=425884767
- 2 donors are published in SONG (highlighted in red in the table) -> these will need to suppressed.
- Remaining 154 donors can be deleted from clinical
- NOTE: During auditing, 2 donors were discovered to have values in the `submitter_specimen_id` field which include commas (highlighted in yellow). The regex in the dictionary should have prevented this, so unclear how these got validated. Created a separate ticket to address this: https://github.com/icgc-argo/argo-dictionary/issues/405

**An additional 1,248 donors have discrepancies** that will need to followed up with program: https://docs.google.com/spreadsheets/d/1ggshqQS9c40nPizDjxuhEG7hHdyvDCSZ/edit#gid=902346357
- Program submitted two different submitter_donor_ids for tumour and normal samples belonging to the same donor.
- 312 donors are published in SONG (highlighted in red) -> these will need to be suppressed.

**167 donors were imported from ICGC25K**: https://docs.google.com/spreadsheets/d/1ggshqQS9c40nPizDjxuhEG7hHdyvDCSZ/edit#gid=60315048
- No action required

**Comment by edsu7** [comment]
Jon will reindex the data.

**Comment by edsu7** [comment]
Multiple issues
- regex for `submitterSpecimenId` will be addressed and fixed in dictionary release 1.19
- data submitter using `submitterSpecimenId` as `submitterDonorId`, @hknahal will share list of discrepancies with data submitter to verify. Followed up with deletion and resubmission.
- Also confirm if molecular data has been processed. If so, will have to reindexing data reflecting new IDs

**Comment by hknahal** [comment]
@lindaxiang @edsu7 Closing this ticket since 156 donors were removed. Followed up with data submitter regarding 1,248 donors with submitter_donor_id discrepancies. Can create a separate ticket for this once data submitter confirms issue and whether they want to have them deleted.

**Comment by lindaxiang** [comment]
@edsu7 can you add update?

**Comment by justincorrigible** [comment]
Superseded by https://github.com/icgc-argo/workflow-roadmap/issues/395
