### ISSUE TITLE
RDPC Portal UI - Add CICD Config

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/roadmap#960]
## Goal
Add terraform, jenkins file,  helm configs, and network policies for the new RDPC portal UI.

**Comment by ciaranschutte** [comment]
https://github.com/OICR/argo-infra/pull/936 - infra helm values PR
https://github.com/icgc-argo/rdpc-ui/pull/3/files - jenkins PR

TODO: Terraform and network policies
@justincorrigible or @UmmulkiramR can help?

**Comment by Buwujiu** [comment]
Task complete, closing.
